// packages/cms-base-layer-react/src/components/block/CmsBlockCategoryNavigation.tsx
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockCategoryNavigation as CmsBlockCategoryNavigationContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockCategoryNavigation({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockCategoryNavigationContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div className={className} style={style}>
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/block/CmsBlockCategoryNavigation.vue
<script setup lang="ts">
import type { CmsBlockCategoryNavigation } from "@shopware/composables";
import { computed } from "vue";

import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockCategoryNavigation;
}>();
const { getSlotContent } = useCmsBlock(() => props.content);
const slotContent = computed(() => getSlotContent("content"));
</script>

<template>
  <div>
    <CmsGenericElement v-if="slotContent" :content="slotContent" />
  </div>
</template>
