// packages/cms-base-layer-react/src/components/block/CmsBlockImageText.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageText as CmsBlockImageTextContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageText({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageTextContent>) {
  const leftContent = getSlotContent(content, "left");
  const rightContent = getSlotContent(content, "right");

  return (
    <div
      className={cx(
        "flex flex-col md:flex-row justify-start items-stretch gap-6 w-full",
        className,
      )}
      style={style}
    >
      <div className="w-full md:flex-1 min-w-0 p-4 flex flex-col">
        <CmsGenericElement content={leftContent} ctx={ctx} className="flex-1" />
      </div>
      <div className="w-full md:flex-1 min-w-0 p-4 flex flex-col">
        <CmsGenericElement
          content={rightContent}
          ctx={ctx}
          className="flex-1"
        />
      </div>
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/block/CmsBlockImageText.vue
<script setup lang="ts">
import type { CmsBlockImageText } from "@shopware/composables";

import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageText;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
</script>
<template>
  <div
    class="flex flex-col md:flex-row justify-start items-stretch gap-6 w-full"
  >
    <div class="w-full md:flex-1 min-w-0 p-4 flex flex-col">
      <CmsGenericElement :content="leftContent" class="flex-1" />
    </div>
    <div class="w-full md:flex-1 min-w-0 p-4 flex flex-col">
      <CmsGenericElement :content="rightContent" class="flex-1" />
    </div>
  </div>
</template>
