// packages/cms-base-layer-react/src/components/block/CmsBlockCrossSelling.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockCrossSelling as CmsBlockCrossSellingContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockCrossSelling({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockCrossSellingContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div className={cx("cms-block-cross-selling", className)} style={style}>
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/block/CmsBlockCrossSelling.vue
<script setup lang="ts">
import type { CmsBlockCrossSelling } from "@shopware/composables";

import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockCrossSelling;
}>();
const { getSlotContent } = useCmsBlock(props.content);
const slotContent = getSlotContent("content");
</script>
<template>
  <div class="cms-block-cross-selling">
    <CmsGenericElement :content="slotContent" />
  </div>
</template>
