// packages/cms-base-layer-react/src/components/block/CmsBlockProductDescriptionReviews.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockProductDescriptionReviews as CmsBlockProductDescriptionReviewsContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockProductDescriptionReviews({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockProductDescriptionReviewsContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div
      className={cx("cms-block-product-description-reviews", className)}
      style={style}
    >
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/block/CmsBlockProductDescriptionReviews.vue
<script setup lang="ts">
import type { CmsBlockProductDescriptionReviews } from "@shopware/composables";

import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockProductDescriptionReviews;
}>();
const { getSlotContent } = useCmsBlock(props.content);
const slotContent = getSlotContent("content");
</script>
<template>
  <div class="cms-block-product-description-reviews">
    <CmsGenericElement :content="slotContent" />
  </div>
</template>
