// templates/react-starter-template/features/checkout/components/CustomerAddressChosen.tsx
import { getTranslatedProperty } from "@shopware/helpers";

import type { Schemas } from "#shopware";

export type ChosenAddress = Pick<
  Schemas["CustomerAddress"],
  "firstName" | "lastName" | "street" | "zipcode" | "city" | "country"
>;

export function CustomerAddressChosen({ address }: { address: ChosenAddress }) {
  const countryName = address.country
    ? getTranslatedProperty(address.country, "name")
    : "";

  return (
    <address
      className="inline-flex flex-col items-start justify-start bg-brand-secondary p-4 not-italic"
      data-testid="checkout-chosen-address"
    >
      <span className="text-base text-surface-on-surface">
        {address.firstName} {address.lastName}
      </span>
      <span className="text-base text-surface-on-surface">
        {address.street}
      </span>
      <span className="text-base text-surface-on-surface">
        {address.zipcode} {address.city}
      </span>
      {countryName ? (
        <span className="text-base text-surface-on-surface">{countryName}</span>
      ) : null}
    </address>
  );
}

// templates/vue-starter-template/app/components/checkout/CustomerAddressChosen.vue
<script setup lang="ts">
import type { Schemas } from "#shopware";
const { address } = defineProps<{
  address: Omit<Schemas["CustomerAddress"], "id" | "customerId">;
}>();
</script>
<template>
  <div
    class="p-4 bg-brand-secondary inline-flex flex-col justify-start items-start"
  >
    <div>
      <div class="text-surface-on-surface text-base">
        {{ address.firstName }} {{ address.lastName }}
      </div>
      <div class="text-surface-on-surface text-base">
        {{ address.street }}
      </div>
      <div class="text-surface-on-surface text-base">
        {{ address.zipcode }} {{ address.city }}
      </div>
      <div
        v-if="address.country?.translated.name"
        class="text-surface-on-surface text-base"
      >
        {{ address.country.translated.name }}
      </div>
    </div>
  </div>
</template>
