// templates/react-starter-template/features/checkout/components/SummaryBox.tsx
"use client";

import { cx } from "@shopware/cms-base-layer-react/client";

import { Price } from "@/components/Price";
import { CheckoutProductTile } from "@/features/cart/components/CheckoutProductTile";
import { useLineItemActions } from "@/features/cart/components/useLineItemActions";
import { useCart } from "@/features/cart/useCart";

const t = {
  checkout: {
    summary: "Summary",
    subtotal: "Subtotal",
    shippingCosts: "Shipping",
    total: "Total",
  },
};

export function SummaryBox({ className }: { className?: string }) {
  const { lineItems, subtotal, totalPrice, shippingCosts } = useCart();
  const { remove, updateQuantity } = useLineItemActions();

  function handleRemove(id: string) {
    void remove(id);
  }

  return (
    <section
      className={cx("sticky top-2 border border-outline-outline", className)}
      aria-labelledby="checkout-summary-heading"
    >
      <div className="border-b border-outline-outline-variant">
        <h2
          id="checkout-summary-heading"
          className="px-6 font-serif text-[40px] text-surface-on-surface"
        >
          {t.checkout.summary}
        </h2>
      </div>
      <div className="p-6 pt-10">
        <ul className="divide-y divide-outline-outline-variant">
          {lineItems.map((item) => (
            <li key={item.id}>
              <CheckoutProductTile
                item={item}
                className="py-4"
                onRemove={handleRemove}
                onChangeQuantity={updateQuantity}
              />
            </li>
          ))}
        </ul>

        <dl className="flex flex-col gap-1 border-t border-outline-outline-variant py-4">
          <div className="flex justify-between">
            <dt className="text-sm font-normal text-surface-on-surface-variant">
              {t.checkout.subtotal}
            </dt>
            <dd>
              <Price
                value={subtotal}
                className="text-sm font-normal text-surface-on-surface"
                data-testid="cart-subtotal"
              />
            </dd>
          </div>
          {shippingCosts.map((delivery, index) => (
            <div
              key={delivery.shippingMethod?.id ?? index}
              className="flex justify-between"
            >
              <dt className="text-sm font-normal text-surface-on-surface-variant">
                {t.checkout.shippingCosts}
              </dt>
              <dd>
                <Price
                  value={delivery.shippingCosts?.totalPrice}
                  className="text-sm font-normal text-surface-on-surface"
                />
              </dd>
            </div>
          ))}
        </dl>
        <dl className="flex justify-between border-t border-outline-outline-variant pt-4">
          <dt className="text-base leading-normal font-normal text-surface-on-surface">
            {t.checkout.total}
          </dt>
          <dd>
            <Price
              value={totalPrice}
              className="text-right text-base leading-normal font-normal text-surface-on-surface"
              data-testid="cart-total"
            />
          </dd>
        </dl>
      </div>
    </section>
  );
}

// templates/vue-starter-template/app/components/checkout/SummaryBox.vue
<script setup lang="ts">
import type { Schemas } from "#shopware";

const props = defineProps<{
  cart: Schemas["Cart"];
}>();

const emit = defineEmits<{
  remove: [id: string];
  updateQuantity: [id: string, quantity: number];
}>();

const { subtotal, totalPrice, shippingCosts } = useCart();

function handleRemoveItem(id: string) {
  emit("remove", id);
}

function handleUpdateQuantity(id: string, quantity: number) {
  emit("updateQuantity", id, quantity);
}
</script>
<template>
  <div class="border border-outline-outline sticky top-2">
    <div class="border-b border-outline-outline-variant">
      <h2 class="text-10 px-6 font-['Noto_Serif']">
        {{ $t("checkout.summary") }}
      </h2>
    </div>
    <div class="p-6 pt-10">
      <div class="divide-y">
        <CheckoutProductTile v-for="item in cart.lineItems" :item="item" :key="item.id" class="py-4" @remove="(id) => handleRemoveItem(id)" @updateQuantity="(id, quantity) => handleUpdateQuantity(id, quantity)" />
      </div>

      <div class="py-4 border-t border-outline-outline-variant flex flex-col gap-1">
        <div class="flex justify-between">
          <div
            class="self-stretch justify-start text-surface-on-surface-variant text-sm font-normal"
          >
            {{ $t("checkout.subtotal") }}
          </div>

          <SharedPrice
            :value="subtotal"
            class="text-surface-on-surface text-sm font-normal"
            data-testid="cart-subtotal"
          />
        </div>

        <div
          class="flex justify-between"
          v-for="shippingCost in shippingCosts"
          :key="shippingCost.shippingMethod?.id ?? Math.random() * 100"
        >
          <div
            class="self-stretch justify-start text-surface-on-surface-variant text-sm font-normal"
          >
            {{ $t("checkout.shippingCosts") }}
          </div>

          <div v-if="shippingCost.shippingCosts?.totalPrice">
            <SharedPrice
              class="text-surface-on-surface text-sm font-normal"
              :value="shippingCost.shippingCosts.totalPrice"
            />
          </div>
        </div>
      </div>
      <div class="pt-4 border-t border-outline-outline-variant flex justify-between">
        <div
          class="self-stretch justify-start text-surface-on-surface text-base font-normal leading-normal"
        >
          {{ $t("checkout.total") }}
        </div>
        <SharedPrice
          :value="totalPrice"
          class="text-right justify-start text-surface-on-surface text-base font-normal leading-normal"
          data-testid="cart-subtotal"
        />
      </div>
    </div>
  </div>
</template>
