// packages/cms-base-layer/app/components/public/cms/element/CmsElementProductBox.vue
<script setup lang="ts">
import type { CmsElementProductBox } from "@shopware/composables";
import { computed } from "vue";

import { useCmsElementConfig } from "#imports";

const props = defineProps<{
  content: CmsElementProductBox;
}>();

const { getConfigValue } = useCmsElementConfig(props.content);
const product = computed(() => props.content.data?.product || {});
</script>

<template>
  <SwProductCard
    v-if="product?.id"
    :product="product"
    :layout-type="getConfigValue('boxLayout')"
  />
  <SwProductCardSkeleton v-else />
</template>

// packages/cms-base-layer-react/src/components/element/CmsElementProductBox.tsx
import { getConfigValue } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsElementProductBox as CmsElementProductBoxContent } from "../../types";
import { SwProductCard } from "../shared/SwProductCard";
import { SwProductCardSkeleton } from "../shared/SwProductCardSkeleton";

export function CmsElementProductBox({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsElementProductBoxContent>) {
  const product = content.data?.product;

  if (!product?.id) {
    return <SwProductCardSkeleton className={className} style={style} />;
  }

  return (
    <SwProductCard
      product={product}
      ctx={ctx}
      layoutType={getConfigValue(content, "boxLayout")}
      className={className}
      style={style}
    />
  );
}
