// packages/cms-base-layer/app/components/public/cms/element/CmsElementHtml.vue
<script setup lang="ts">
import type { CmsElementHtml } from "@shopware/composables";
import { getCmsLayoutConfiguration } from "@shopware/helpers";
import { h } from "vue";

const props = defineProps<{
  content: CmsElementHtml;
}>();

const { cssClasses, layoutStyles } = getCmsLayoutConfiguration(props.content);

const HtmlComponent = () => {
  return h("div", {
    class: ["cms-element-html", "cms-element-text", cssClasses],
    style: layoutStyles,
    innerHTML: props.content.data.content || "",
  });
};
</script>

<template>
  <HtmlComponent />
</template>

// packages/cms-base-layer-react/src/components/element/CmsElementHtml.tsx
import { cx } from "../../helpers/cx";
import type { CmsComponentProps } from "../../registry";
import { sanitizeHtml } from "../../rich-text/sanitize";
import type { CmsElementHtml as CmsElementHtmlContent } from "../../types";

export function CmsElementHtml({
  content,
  className,
  style,
}: CmsComponentProps<CmsElementHtmlContent>) {
  return (
    <div
      className={cx("cms-element-html cms-element-text", className)}
      style={style}
      dangerouslySetInnerHTML={{
        __html: sanitizeHtml(content.data?.content || ""),
      }}
    />
  );
}
