// packages/cms-base-layer/app/components/public/cms/element/CmsElementImageGallery.vue
<script setup lang="ts">
import type { CmsElementImageGallery } from "@shopware/composables";
import { computed, defineAsyncComponent } from "vue";
import { useImagePlaceholder } from "#imports";
import { isSpatial } from "../../../../helpers/media/isSpatial";

// Load SwMedia3D only on client-side to avoid SSR issues with three.js packages
const SwMedia3DAsync = defineAsyncComponent(
  () => import("../../../SwMedia3D.vue"),
);

const props = defineProps<{
  content: CmsElementImageGallery;
}>();

const mediaGallery = computed(() => props.content.data?.sliderItems ?? []);
const placeholderSvg = useImagePlaceholder();

const sliderConfig = computed(() => ({
  navigationArrows: { source: "static" as const, value: "inside" },
  navigationDots: { source: "static" as const, value: "inside" },
  ...props.content.config,
}));
</script>

<template>
  <div
    class="w-full max-w-full relative inline-flex flex-col justify-center items-center gap-2 mx-auto"
  >
    <div class="w-full h-[400px] sm:h-[500px] lg:h-[600px] xl:h-[700px] overflow-hidden relative">
      <!-- Placeholder shown during SSR and until slider is ready -->
      <img
        class="w-full h-full object-cover absolute inset-0"
        :src="placeholderSvg"
        alt="Gallery placeholder"
      />
      <SwSlider
        v-if="mediaGallery.length > 0"
        class="relative z-1"
        :config="sliderConfig"
      >
        <template v-for="item in mediaGallery" :key="item.media?.url">
          <div class="w-full h-full relative">
            <!-- 3D media -->
            <div
              v-if="item.media && isSpatial(item.media)"
              class="w-full h-full relative"
            >
              <client-only>
                <SwMedia3DAsync :src="item.media.url" />
                <template #fallback>
                  <CmsElementImageGallery3dPlaceholder
                    class="w-full h-full absolute inset-0 object-cover"
                  />
                  <span
                    class="absolute bottom-4 right-4 text-sm bg-gray-800 rounded px-2 py-1 text-white"
                  >
                    3D
                  </span>
                </template>
              </client-only>
            </div>
            <!-- regular image -->
            <NuxtImg
              v-else-if="item.media"
              preset="hero"
              loading="lazy"
              class="w-full h-full absolute inset-0 object-cover"
              :placeholder="placeholderSvg"
              :src="item.media.url"
              :alt="item.media.alt || 'Product image'"
            />
          </div>
        </template>
      </SwSlider>
    </div>
  </div>
</template>

// packages/cms-base-layer-react/src/components/element/CmsElementImageGallery.tsx
import { getTranslatedProperty } from "@shopware/helpers";

import { cx } from "../../helpers/cx";
import { getImagePlaceholder } from "../../helpers/imagePlaceholder";
import { isSpatial } from "../../helpers/isSpatial";
import { getConfigValue } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsElementImageGallery as CmsElementImageGalleryContent } from "../../types";
import { CmsMedia } from "../ui/CmsMedia";
import { CmsElementImageGallery3dPlaceholder } from "./CmsElementImageGallery3dPlaceholder";
import { CmsElementImageGallerySlides } from "./CmsElementImageGallerySlides";

const DEFAULT_MIN_HEIGHT = "500px";
const DEFAULT_NAVIGATION = "inside";
const IMAGE_CLASS = "w-full h-full absolute inset-0 object-cover";
const PLACEHOLDER_ALT = "Placeholder image";
const PRODUCT_IMAGE_ALT = "Product image";

export function CmsElementImageGallery({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsElementImageGalleryContent>) {
  const minHeight = getConfigValue(content, "minHeight") || DEFAULT_MIN_HEIGHT;
  const navigationArrows =
    getConfigValue(content, "navigationArrows") || DEFAULT_NAVIGATION;
  const navigationDots =
    getConfigValue(content, "navigationDots") || DEFAULT_NAVIGATION;
  const mediaGallery = content.data?.sliderItems ?? [];
  const placeholderSvg = getImagePlaceholder(ctx.config.imagePlaceholder.color);

  function renderPlaceholder(key: string) {
    return (
      <img
        key={key}
        className={IMAGE_CLASS}
        src={placeholderSvg}
        alt={PLACEHOLDER_ALT}
      />
    );
  }

  const slides = mediaGallery.map((item, index) => {
    const media = item.media;
    if (!media?.url) {
      return renderPlaceholder(`placeholder-${index}`);
    }
    if (isSpatial(media)) {
      return (
        <div
          key={`${media.id}-${index}-3d`}
          className="w-full h-full relative"
          style={{ minHeight }}
        >
          <CmsElementImageGallery3dPlaceholder className={IMAGE_CLASS} />
          <span className="absolute bottom-4 right-4 text-sm bg-gray-800 rounded px-2 py-1 text-white">
            3D
          </span>
        </div>
      );
    }
    return (
      <CmsMedia
        key={`${media.id}-${index}`}
        media={media}
        alt={getTranslatedProperty(media, "alt") || PRODUCT_IMAGE_ALT}
        className={IMAGE_CLASS}
        sizes={ctx.imageSizes}
      />
    );
  });

  return (
    <div
      className={cx(
        "w-full max-w-full relative inline-flex flex-col justify-center items-center gap-2 mx-auto",
        className,
      )}
      style={style}
    >
      <div className="w-full">
        <CmsElementImageGallerySlides
          minHeight={minHeight}
          navigationArrows={navigationArrows}
          navigationDots={navigationDots}
        >
          {slides.length ? slides : renderPlaceholder("placeholder")}
        </CmsElementImageGallerySlides>
      </div>
    </div>
  );
}
