// packages/cms-base-layer/app/components/ui/RadioButton.vue
<script setup lang="ts">
const modelValue = defineModel<string | null>();

const { selected } = defineProps<{
  selected: boolean;
}>();
</script>
<template>
  <input
    type="radio"
    class="sr-only"
    v-bind="$attrs"
    v-model="modelValue"
    name="shipping-method"
  />
  <div
    class="w-4 h-4 rounded-full border border-outline-outline border-spacing-1 flex items-center justify-center"
  >
    <div
      :class="{
        'bg-brand-primary': selected,
      }"
      class="w-2.5 h-2.5 rounded-full"
    ></div>
  </div>
</template>

// packages/cms-base-layer-react/src/components/ui/RadioButton.tsx
"use client";

import type { ComponentProps } from "react";

import { cx } from "../../helpers/cx";

export type RadioButtonProps = Omit<
  ComponentProps<"input">,
  "type" | "className" | "checked" | "onChange" | "value" | "name"
> & {
  value: string;
  modelValue?: string | null;
  selected: boolean;
  onChange?: (value: string) => void;
};

export function RadioButton({
  value,
  modelValue,
  selected,
  onChange,
  ...attrs
}: RadioButtonProps) {
  return (
    <>
      <input
        type="radio"
        className="sr-only"
        {...attrs}
        value={value}
        checked={modelValue === value}
        onChange={() => onChange?.(value)}
        name="shipping-method"
      />
      <div className="w-4 h-4 rounded-full border border-outline-outline border-spacing-1 flex items-center justify-center">
        <div
          className={cx(
            "w-2.5 h-2.5 rounded-full",
            selected && "bg-brand-primary",
          )}
        />
      </div>
    </>
  );
}
