// packages/cms-base-layer-react/src/components/shared/SwProductReviews.tsx
import type { Schemas } from "#shopware";

import type { CmsClientContext } from "../../context";
import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import { WarningIcon } from "../icons";
import { SwProductRating } from "./SwProductRating";

export type SwProductReviewsProps = {
  reviews?: Schemas["ProductReview"][];
  ctx: CmsClientContext;
};

const translationDefaults = {
  product: {
    noReviews: "No reviews yet.",
    reviewNotAccepted: "Your review has not been approved yet",
    reviewFeedback: "Shop feedback",
  },
};

const DATE_FORMAT: Intl.DateTimeFormatOptions = {
  year: "numeric",
  month: "numeric",
  day: "numeric",
  hour: "numeric",
  minute: "numeric",
};

function formatDate(date: string, locale: string): string {
  try {
    return new Intl.DateTimeFormat(locale, DATE_FORMAT).format(new Date(date));
  } catch {
    return date;
  }
}

export function SwProductReviews({ reviews = [], ctx }: SwProductReviewsProps) {
  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );

  if (!reviews.length) {
    return <div>{translations.product.noReviews}.</div>;
  }

  return (
    <div className="flex flex-col gap-6">
      {reviews.map((review, index) => (
        <div
          key={review.id ?? index}
          className={cx(
            "pb-6",
            index < reviews.length - 1 &&
              "border-b border-surface-surface-container-highest",
          )}
        >
          {review.createdAt ? (
            <div className="cms-block-product-description-reviews__reviews-time text-surface-on-surface-variant text-sm">
              {review.externalUser ? (
                <span>{review.externalUser} - </span>
              ) : null}
              <span>{formatDate(review.createdAt, ctx.locale)}</span>
            </div>
          ) : null}
          {!review.status ? (
            <div className="mt-2 text-xs p-2 bg-states-info-container text-states-on-info-container flex gap-2 items-center">
              <WarningIcon className="w-6 h-6" />
              {translations.product.reviewNotAccepted}
            </div>
          ) : null}
          <div className="cms-block-product-description-reviews__reviews-rating inline-flex items-center mt-2">
            <SwProductRating
              rating={review.points ?? 0}
              starSize={20}
              showCount={false}
            />
            <div className="cms-block-product-description-reviews__reviews-title font-semibold ml-2">
              <p>{review.title}</p>
            </div>
          </div>
          <div className="cms-block-product-description-reviews__reviews-content mt-2">
            <p className="break-words">{review.content}</p>
            {review.comment ? (
              <p className="text-surface-on-surface-variant mt-2">
                - {translations.product.reviewFeedback}: {review.comment}
              </p>
            ) : null}
          </div>
        </div>
      ))}
    </div>
  );
}

// packages/cms-base/components/SwProductReviews.vue
<script setup lang="ts">
import type { Schemas } from "#shopware";
import { useProductReviews, useCmsTranslations } from "#imports";
import { computed, onMounted, ref, toRefs } from "vue";
import { defu } from "defu";

const props = defineProps<{
  product: Schemas["Product"];
  reviews?: Schemas["ProductReview"][];
}>();

type Translations = {
  product: {
    noReviews: string;
  };
};

let translations: Translations = {
  product: {
    noReviews: "No reviews yet.",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const { product, reviews } = toRefs(props);

const shouldLoadReviews = !reviews?.value;

const loadingReviews = ref<boolean>(shouldLoadReviews);
const { loadProductReviews, productReviews } = useProductReviews(product);

onMounted(async () => {
  if (shouldLoadReviews) {
    await loadProductReviews();
  }
  loadingReviews.value = false;
});
const reviewsList = computed<Schemas["ProductReview"][]>(
  () => reviews?.value || productReviews.value || [],
);

const format: Intl.DateTimeFormatOptions = {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "numeric",
  hour12: true,
};

const formatDate = (date: string) =>
  new Date(date).toLocaleDateString("en-us", format);
</script>

<template>
  <div
    v-if="loadingReviews"
    class="absolute inset-0 flex items-center justify-center z-10 bg-white/75"
  >
    <div
      class="h-15 w-15 i-carbon-progress-bar-round animate-spin c-gray-500"
    />
  </div>
  <div v-else-if="reviewsList.length">
    <div v-for="review in reviews" :key="review.id">
      <div
        class="cms-block-product-description-reviews__reviews-time mt-3 text-gray-600 text-sm"
      >
        <span>{{ formatDate(review.createdAt) }}</span>
      </div>
      <div
        class="cms-block-product-description-reviews__reviews-rating inline-flex items-center mt-2"
      >
        <div
          v-for="_ in review.points"
          :key="`filled-star-${_}`"
          class="w-5 h-5 i-carbon-star-filled"
        ></div>
        <div
          v-for="_ in 5 - (review.points || 0)"
          :key="`empty-star-${_}`"
          class="w-5 h-5 i-carbon-star"
        ></div>
        <div
          class="cms-block-product-description-reviews__reviews-title font-semibold ml-2"
        >
          <p>{{ review.title }}</p>
        </div>
      </div>
      <div class="cms-block-product-description-reviews__reviews-content mt-2">
        <span>{{ review.content }}</span>
      </div>
    </div>
  </div>

  <div v-else>{{ translations.product.noReviews }}.</div>
</template>
