// templates/react-starter-template/features/layout/components/MainCounter.tsx
import { cx } from "@shopware/cms-base-layer-react/client";

export function MainCounter({
  count,
  className,
}: {
  count: number;
  className?: string;
}) {
  return (
    <span
      className={cx(
        "block size-[18px] rounded-full bg-states-error text-center text-xs leading-[18px] font-bold text-white",
        className,
      )}
    >
      {count}
    </span>
  );
}

// packages/layers/layout/components/MainCounter.vue
<script lang="ts" setup>
defineProps<{
  count: string;
}>();
</script>
<template>
  <div
    class="w-[18px] h-[18px] relative bg-[#d02d23] rounded-full overflow-hidden"
  >
    <div
      class="w-[18px] left-0 top-[-2px] absolute text-center justify-start text-white text-sm font-bold leading-[21px]"
    >
      {{ count }}
    </div>
  </div>
</template>
