// packages/cms-base-layer/app/components/listing-filters/SwFilterPrice.vue
<script setup lang="ts" generic="
    ListingFilter extends {
      code: string;
      min?: number;
      max?: number;
      label: string;
    }
  ">
import { useCmsTranslations } from "@shopware/composables";
import { onClickOutside, useDebounceFn, useEventListener } from "@vueuse/core";
import { defu } from "defu";
import { onMounted, reactive, ref, watch } from "vue";
import type { Schemas } from "#shopware";

const emits =
  defineEmits<
    (e: "select-value", value: { code: string; value: unknown }) => void
  >();

const {
  filter,
  selectedFilters,
  displayMode = "accordion",
} = defineProps<{
  filter: ListingFilter;
  selectedFilters: Schemas["ProductListingResult"]["currentFilters"];
  displayMode?: "accordion" | "dropdown";
}>();

type Translations = {
  listing: {
    min: string;
    max: string;
  };
};
let translations: Translations = {
  listing: {
    min: "Min",
    max: "Max",
  },
};
translations = defu(useCmsTranslations(), translations) as Translations;

const prices = reactive<{ min: number; max: number }>({
  min: 0,
  max: 0,
});

onMounted(() => {
  prices.min = Math.floor(selectedFilters.price?.min ?? filter.min ?? 0);
  prices.max = Math.floor(selectedFilters.price?.max ?? filter.max ?? 0);
});

const isFilterVisible = ref<boolean>(false);
const toggle = () => {
  isFilterVisible.value = !isFilterVisible.value;
};

const dropdownElement = ref(null);
onClickOutside(dropdownElement, () => {
  isFilterVisible.value = false;
});

function onMinPriceChange(newPrice: number, oldPrice: number) {
  if (newPrice === oldPrice || oldPrice === 0) return;
  emits("select-value", {
    code: "min-price",
    value: newPrice,
  });
}
const debounceMinPriceUpdate = useDebounceFn(onMinPriceChange, 500);
watch(() => prices.min, debounceMinPriceUpdate);

function onMaxPriceChange(newPrice: number, oldPrice: number) {
  if (newPrice === oldPrice || oldPrice === 0) return;
  emits("select-value", {
    code: "max-price",
    value: newPrice,
  });
}
const debounceMaxPriceUpdate = useDebounceFn(onMaxPriceChange, 500);
watch(() => prices.max, debounceMaxPriceUpdate);

// Slider drag logic
type DragType = "min" | "max" | null;
const dragging = ref<DragType>(null);
const sliderRect = ref<DOMRect | null>(null);

const getClientX = (event: MouseEvent | TouchEvent): number =>
  event instanceof MouseEvent ? event.clientX : event.touches[0]?.clientX || 0;

const updateSliderValue = (clientX: number) => {
  if (!dragging.value || !sliderRect.value) return;

  const min = filter.min ?? 0;
  const max = filter.max ?? 100;
  const percent = Math.min(
    Math.max((clientX - sliderRect.value.left) / sliderRect.value.width, 0),
    1,
  );
  const value = Math.round(min + percent * (max - min));

  if (dragging.value === "min") {
    if (value >= min && value <= prices.max) prices.min = value;
  } else {
    if (value <= max && value >= prices.min) prices.max = value;
  }
};

const onDrag = (event: MouseEvent | TouchEvent) => {
  if (!dragging.value) return;
  event.preventDefault();
  updateSliderValue(getClientX(event));
};

const stopDrag = () => {
  dragging.value = null;
  sliderRect.value = null;
};

useEventListener(window, "mousemove", onDrag);
useEventListener(window, "mouseup", stopDrag);
useEventListener(window, "touchmove", onDrag, { passive: false });
useEventListener(window, "touchend", stopDrag);

const startDrag = (type: "min" | "max", event: MouseEvent | TouchEvent) => {
  event.preventDefault();
  dragging.value = type;
  const slider = (event.target as HTMLElement).closest(".relative.w-64.h-10");
  if (slider) {
    sliderRect.value = slider.getBoundingClientRect();
  }
};
</script>

<template>
  <div class="self-stretch flex flex-col justify-start items-start gap-4">
    <!-- Accordion header (only in accordion mode) -->
    <template v-if="displayMode === 'accordion'">
      <div class="self-stretch flex flex-col justify-center items-center">
        <div
          class="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-between items-center gap-1 cursor-pointer"
          @click="toggle"
          role="button"
          tabindex="0"
          :aria-expanded="isFilterVisible"
          :aria-controls="`filter-${filter.code}`"
          @keydown.enter="toggle"
          @keydown.space.prevent="toggle"
        >
          <div class="flex-1 flex items-center gap-2.5">
            <div class="flex-1 text-surface-on-surface text-base font-bold leading-normal text-left">
              {{ filter.label }}
            </div>
          </div>
          <span
            class="flex items-center justify-center"
            aria-hidden="true"
          >
            <SwChevronIcon :direction="isFilterVisible ? 'up' : 'down'" :size="24" />
          </span>
        </div>
      </div>
    </template>

    <!-- Filter content -->
    <transition name="filter-collapse">
      <div v-if="isFilterVisible || displayMode === 'dropdown'" :id="filter.code"
        class="self-stretch flex flex-col justify-start items-start gap-2.5">
        <div class="self-stretch flex flex-col justify-start items-start gap-1">
          <div class="self-stretch inline-flex justify-between items-center gap-2">
            <div
              class="w-16 h-10 px-2 py-1 rounded-lg outline outline-1 outline-offset-[-1px] outline-outline-outline-variant inline-flex flex-col justify-center items-start gap-2.5">
              <input type="number" :placeholder="translations.listing.min" v-model.number="prices.min"
                class="w-full bg-transparent border-none outline-none text-surface-on-surface text-sm font-normal leading-tight"
                @change="emits('select-value', { code: filter.code, value: { min: prices.min, max: prices.max } })"
                :min="filter.min" :max="prices.max" />
            </div>
            <div
              class="w-16 h-10 px-2 py-1 rounded-lg outline outline-1 outline-offset-[-1px] outline-outline-outline-variant inline-flex flex-col justify-center items-start gap-2.5">
              <input type="number" :placeholder="translations.listing.max" v-model.number="prices.max"
                class="w-full bg-transparent border-none outline-none text-surface-on-surface text-sm font-normal leading-tight"
                @change="emits('select-value', { code: filter.code, value: { min: prices.min, max: prices.max } })"
                :min="prices.min" :max="filter.max" />
            </div>
          </div>
          <!-- Custom slider UI -->
          <div class="relative w-64 h-10 mt-2 mx-auto flex items-center select-none">
            <!-- Track -->
            <div
              class="absolute left-0 top-1/2 -translate-y-1/2 w-full h-2 bg-surface-surface-container-highest rounded-full">
            </div>
            <!-- Active range -->
            <div class="absolute top-1/2 -translate-y-1/2 h-2 bg-surface-surface-primary rounded-full" :style="{
              left: ((prices.min - (filter.min ?? 0)) / ((filter.max ?? 100) - (filter.min ?? 0))) * 100 + '%',
              width: ((prices.max - prices.min) / ((filter.max ?? 100) - (filter.min ?? 0))) * 100 + '%',
            }"></div>
            <!-- Min thumb -->
            <div
              class="absolute top-1/2 -translate-y-1/2 w-5 h-5 bg-brand-primary rounded-full shadow-[2px_2px_10px_0px_rgba(0,0,0,0.15)] cursor-pointer touch-none"
              :style="{
                left: `calc(${((prices.min - (filter.min ?? 0)) / ((filter.max ?? 100) - (filter.min ?? 0))) * 100}% - 10px)`
              }"
              @mousedown.prevent="startDrag('min', $event)"
              @touchstart.prevent="startDrag('min', $event)"></div>
            <!-- Max thumb -->
            <div
              class="absolute top-1/2 -translate-y-1/2 w-5 h-5 bg-brand-primary rounded-full shadow-[2px_2px_10px_0px_rgba(0,0,0,0.15)] cursor-pointer touch-none"
              :style="{
                left: `calc(${((prices.max - (filter.min ?? 0)) / ((filter.max ?? 100) - (filter.min ?? 0))) * 100}% - 10px)`
              }"
              @mousedown.prevent="startDrag('max', $event)"
              @touchstart.prevent="startDrag('max', $event)"></div>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

// packages/cms-base-layer-react/src/components/shared/SwFilterPrice.tsx
"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";
import type {
  ChangeEvent,
  KeyboardEvent,
  MouseEvent as ReactMouseEvent,
} from "react";

import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import type { CmsTranslations } from "../../translations";
import { ChevronDownIcon } from "../icons";
import type {
  ListingFilter,
  ListingFilterChangeEvent,
  ListingFilterDisplayMode,
} from "./listingFilterTypes";

export type SwFilterPriceProps = {
  filter: ListingFilter;
  selectedFilters: { price?: { min?: number; max?: number } };
  displayMode?: ListingFilterDisplayMode;
  translations?: CmsTranslations;
  onSelectValue: (event: ListingFilterChangeEvent) => void;
};

const defaultTranslations = {
  listing: {
    min: "Min",
    max: "Max",
  },
};

const DEBOUNCE_MS = 500;

type Prices = { min: number; max: number };
type DragType = "min" | "max" | null;

const getClientX = (event: MouseEvent | TouchEvent): number =>
  event instanceof MouseEvent
    ? event.clientX
    : (event.touches.item(0)?.clientX ?? 0);

const toInputNumber = (event: ChangeEvent<HTMLInputElement>): number => {
  const parsed = event.target.valueAsNumber;
  return Number.isFinite(parsed) ? parsed : 0;
};

const getKeyStep = (key: string): number => {
  if (key === "ArrowRight" || key === "ArrowUp") return 1;
  if (key === "ArrowLeft" || key === "ArrowDown") return -1;
  return 0;
};

export function SwFilterPrice({
  filter,
  selectedFilters,
  displayMode = "accordion",
  translations,
  onSelectValue,
}: SwFilterPriceProps) {
  const t = withTranslationDefaults(translations, defaultTranslations);
  const selectedMin = selectedFilters.price?.min;
  const selectedMax = selectedFilters.price?.max;
  const initialPrices = (): Prices => ({
    min: Math.floor(selectedMin ?? filter.min ?? 0),
    max: Math.floor(selectedMax ?? filter.max ?? 0),
  });

  const [prices, setPrices] = useState<Prices>(initialPrices);
  const syncKey = `${selectedMin}|${selectedMax}|${filter.min}|${filter.max}`;
  const [previousSyncKey, setPreviousSyncKey] = useState(syncKey);
  if (previousSyncKey !== syncKey) {
    setPreviousSyncKey(syncKey);
    setPrices(initialPrices());
  }

  const [isFilterVisible, setIsFilterVisible] = useState(false);
  const toggle = () => setIsFilterVisible((visible) => !visible);

  const onSelectValueRef = useRef(onSelectValue);
  useEffect(() => {
    onSelectValueRef.current = onSelectValue;
  });

  const pricesRef = useRef(prices);
  const emitRange = useCallback(() => {
    const { min, max } = pricesRef.current;
    onSelectValueRef.current({ code: "price", value: { min, max } });
  }, []);

  const timer = useRef<number | undefined>(undefined);
  const clearPendingEmit = () => window.clearTimeout(timer.current);
  const scheduleEmit = useCallback(() => {
    window.clearTimeout(timer.current);
    timer.current = window.setTimeout(emitRange, DEBOUNCE_MS);
  }, [emitRange]);
  useEffect(() => () => window.clearTimeout(timer.current), []);

  const userChanged = useRef(false);
  const previousPrices = useRef(prices);
  useEffect(() => {
    const previous = previousPrices.current;
    previousPrices.current = prices;
    pricesRef.current = prices;
    if (!userChanged.current) return;
    userChanged.current = false;
    if (prices.min !== previous.min || prices.max !== previous.max) {
      scheduleEmit();
    }
  }, [prices, scheduleEmit]);

  const updateUserPrices = (update: (current: Prices) => Prices) => {
    userChanged.current = true;
    setPrices(update);
  };

  const onInputBlur = () => {
    clearPendingEmit();
    emitRange();
  };

  const [dragging, setDragging] = useState<DragType>(null);
  const sliderElement = useRef<HTMLDivElement>(null);
  const sliderRect = useRef<DOMRect | null>(null);
  const rangeMin = filter.min ?? 0;
  const rangeMax = filter.max ?? 100;

  const clampThumb = useCallback(
    (type: "min" | "max", value: number) => {
      userChanged.current = true;
      setPrices((current) => {
        if (type === "min") {
          return value >= rangeMin && value <= current.max
            ? { ...current, min: value }
            : current;
        }
        return value <= rangeMax && value >= current.min
          ? { ...current, max: value }
          : current;
      });
    },
    [rangeMin, rangeMax],
  );

  useEffect(() => {
    if (!dragging) return;

    const updateSliderValue = (clientX: number) => {
      const rect = sliderRect.current;
      if (!rect) return;
      const percent = Math.min(
        Math.max((clientX - rect.left) / rect.width, 0),
        1,
      );
      clampThumb(
        dragging,
        Math.round(rangeMin + percent * (rangeMax - rangeMin)),
      );
    };

    const onDrag = (event: MouseEvent | TouchEvent) => {
      event.preventDefault();
      updateSliderValue(getClientX(event));
    };
    const stopDrag = () => {
      setDragging(null);
      sliderRect.current = null;
    };

    window.addEventListener("mousemove", onDrag);
    window.addEventListener("mouseup", stopDrag);
    window.addEventListener("touchmove", onDrag, { passive: false });
    window.addEventListener("touchend", stopDrag);
    return () => {
      window.removeEventListener("mousemove", onDrag);
      window.removeEventListener("mouseup", stopDrag);
      window.removeEventListener("touchmove", onDrag);
      window.removeEventListener("touchend", stopDrag);
    };
  }, [dragging, rangeMin, rangeMax, clampThumb]);

  const startDrag = (type: "min" | "max") => {
    setDragging(type);
    sliderRect.current = sliderElement.current?.getBoundingClientRect() ?? null;
  };

  const onMouseDownThumb =
    (type: "min" | "max") => (event: ReactMouseEvent<HTMLButtonElement>) => {
      event.preventDefault();
      startDrag(type);
    };

  const onThumbKeyDown =
    (type: "min" | "max") => (event: KeyboardEvent<HTMLButtonElement>) => {
      const step = getKeyStep(event.key);
      if (!step) return;
      event.preventDefault();
      clampThumb(type, (type === "min" ? prices.min : prices.max) + step);
    };

  const span = rangeMax - rangeMin;
  const toPercent = (value: number) =>
    span > 0 ? ((value - rangeMin) / span) * 100 : 0;
  const minPercent = toPercent(prices.min);
  const maxPercent = toPercent(prices.max);
  const widthPercent = maxPercent - minPercent;
  const panelId = useId();

  return (
    <div className="self-stretch flex flex-col justify-start items-start gap-4">
      {displayMode === "accordion" && (
        <div className="self-stretch flex flex-col justify-center items-center">
          <button
            type="button"
            className="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-between items-center gap-1 cursor-pointer"
            onClick={toggle}
            aria-expanded={isFilterVisible}
            aria-controls={panelId}
          >
            <div className="flex-1 flex items-center gap-2.5">
              <div className="flex-1 text-surface-on-surface text-base font-bold leading-normal text-left">
                {filter.label}
              </div>
            </div>
            <span
              className="flex items-center justify-center"
              aria-hidden="true"
            >
              <ChevronDownIcon
                width={24}
                height={24}
                className={cx(
                  "transition-transform",
                  isFilterVisible && "rotate-180",
                )}
              />
            </span>
          </button>
        </div>
      )}

      {(isFilterVisible || displayMode === "dropdown") && (
        <div
          id={panelId}
          className="self-stretch flex flex-col justify-start items-start gap-2.5"
        >
          <div className="self-stretch flex flex-col justify-start items-start gap-1">
            <div className="self-stretch inline-flex justify-between items-center gap-2">
              <div className="w-16 h-10 px-2 py-1 rounded-lg outline outline-1 outline-offset-[-1px] outline-outline-outline-variant inline-flex flex-col justify-center items-start gap-2.5">
                <input
                  type="number"
                  placeholder={t.listing.min}
                  aria-label={t.listing.min}
                  value={prices.min}
                  onChange={(event) => {
                    const min = toInputNumber(event);
                    updateUserPrices((current) => ({ ...current, min }));
                  }}
                  onBlur={onInputBlur}
                  className="w-full bg-transparent border-none outline-hidden text-surface-on-surface text-sm font-normal leading-tight"
                  min={filter.min}
                  max={prices.max}
                />
              </div>
              <div className="w-16 h-10 px-2 py-1 rounded-lg outline outline-1 outline-offset-[-1px] outline-outline-outline-variant inline-flex flex-col justify-center items-start gap-2.5">
                <input
                  type="number"
                  placeholder={t.listing.max}
                  aria-label={t.listing.max}
                  value={prices.max}
                  onChange={(event) => {
                    const max = toInputNumber(event);
                    updateUserPrices((current) => ({ ...current, max }));
                  }}
                  onBlur={onInputBlur}
                  className="w-full bg-transparent border-none outline-hidden text-surface-on-surface text-sm font-normal leading-tight"
                  min={prices.min}
                  max={filter.max}
                />
              </div>
            </div>
            <div
              ref={sliderElement}
              className="relative w-64 h-10 mt-2 mx-auto flex items-center select-none"
            >
              <div className="absolute left-0 top-1/2 -translate-y-1/2 w-full h-2 bg-surface-surface-container-highest rounded-full" />
              <div
                className="absolute top-1/2 -translate-y-1/2 h-2 bg-surface-surface-primary rounded-full"
                style={{ left: `${minPercent}%`, width: `${widthPercent}%` }}
              />
              <button
                type="button"
                aria-label={t.listing.min}
                className="absolute top-1/2 -translate-y-1/2 w-5 h-5 bg-brand-primary rounded-full shadow-[2px_2px_10px_0px_rgba(0,0,0,0.15)] cursor-pointer touch-none"
                style={{ left: `calc(${minPercent}% - 10px)` }}
                onMouseDown={onMouseDownThumb("min")}
                onTouchStart={() => startDrag("min")}
                onKeyDown={onThumbKeyDown("min")}
              />
              <button
                type="button"
                aria-label={t.listing.max}
                className="absolute top-1/2 -translate-y-1/2 w-5 h-5 bg-brand-primary rounded-full shadow-[2px_2px_10px_0px_rgba(0,0,0,0.15)] cursor-pointer touch-none"
                style={{ left: `calc(${maxPercent}% - 10px)` }}
                onMouseDown={onMouseDownThumb("max")}
                onTouchStart={() => startDrag("max")}
                onKeyDown={onThumbKeyDown("max")}
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
