// packages/cms-base/components/SwListingProductPrice.vue
<script setup lang="ts">
import {
  useCmsTranslations,
  useProductPrice,
} from "@shopware-pwa/composables-next";
import { defu } from "defu";
import { toRefs } from "vue";
import type { Schemas } from "#shopware";

const props = defineProps<{
  product: Schemas["Product"];
}>();

type Translations = {
  listing: {
    variantsFrom: string;
    previously: string;
    to: string;
  };
};

let translations: Translations = {
  listing: {
    variantsFrom: "variants from",
    previously: "previously",
    from: "from",
    to: "to",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const { product } = toRefs(props);

const {
  price,
  unitPrice,
  displayFromVariants,
  displayFrom,
  isListPrice,
  regulationPrice,
} = useProductPrice(product);
</script>

<template>
  <div :id="product.id">
    <SwSharedPrice
      v-if="isListPrice"
      class="text-l text-gray-900 basis-2/6 justify-end line-through"
      :value="price?.listPrice?.price"
    />
    <template v-if="!isListPrice">
      <div class="h-6"><!-- placeholder --></div>
    </template>
    <SwSharedPrice
      v-if="displayFromVariants"
      class="text-xl text-gray-900 basis-2/6 justify-end"
      :value="displayFromVariants"
    >
      <template #beforePrice
        ><span v-if="displayFromVariants" class="text-sm">{{
          translations.listing.variantsFrom
        }}</span></template
      >
    </SwSharedPrice>
    <SwSharedPrice
      class="text-gray-900 basis-2/6"
      :class="{
        'text-red-600 font-bold': isListPrice,
        'justify-end text-xl':
          regulationPrice || !regulationPrice || !displayFromVariants,
      }"
      :value="unitPrice"
    >
      <template #beforePrice
        ><span v-if="displayFrom || displayFromVariants" class="text-sm">{{
          translations.listing.from
        }}</span></template
      >
    </SwSharedPrice>
    <template v-if="regulationPrice">
      <div class="flex gap-2 justify-end text-gray-500 text-3.5 mb-2">
        {{ translations.listing.previously }}
        <SharedPrice :value="regulationPrice" />
      </div>
    </template>
    <template v-if="!regulationPrice">
      <div class="h-7"><!-- placeholder --></div>
    </template>
  </div>
</template>

// packages/cms-base-layer-react/src/components/shared/SwListingProductPrice.tsx
import type { ComponentProps } from "react";

import type { Schemas } from "#shopware";

import type { CmsClientContext } from "../../context";
import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import { getProductPrice } from "./productPrice";
import { SwSharedPrice } from "./SwSharedPrice";

export type ProductPriceContext = Pick<
  CmsClientContext,
  "locale" | "currencyCode" | "translations"
>;

export type SwListingProductPriceProps = Omit<
  ComponentProps<"div">,
  "children"
> & {
  product: Schemas["Product"];
  ctx: ProductPriceContext;
};

const translationDefaults = {
  listing: {
    variantsFrom: "variants from",
    previously: "previously",
    from: "from",
    to: "to",
  },
};

export function SwListingProductPrice({
  product,
  ctx,
  className,
  ...props
}: SwListingProductPriceProps) {
  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );
  const {
    price,
    unitPrice,
    displayFromVariants,
    displayFrom,
    hasListPrice,
    regulationPrice,
  } = getProductPrice(product);

  const fromLabel =
    displayFrom || displayFromVariants ? (
      <span className="text-sm">{translations.listing.from}</span>
    ) : null;

  return (
    <div
      {...props}
      className={cx("inline-flex justify-start items-center gap-2", className)}
    >
      {hasListPrice ? (
        <div className="flex items-center gap-2">
          <div className="text-base font-bold leading-normal">
            <SwSharedPrice
              value={unitPrice}
              ctx={ctx}
              beforePrice={fromLabel}
            />
          </div>
          <div className="text-surface-on-surface-variant text-sm font-normal leading-tight line-through">
            <SwSharedPrice value={price?.listPrice?.price} ctx={ctx} />
          </div>
        </div>
      ) : (
        <div className="text-surface-on-surface text-base font-bold leading-normal">
          <SwSharedPrice value={unitPrice} ctx={ctx} beforePrice={fromLabel} />
        </div>
      )}

      {displayFromVariants ? (
        <div className="text-surface-on-surface text-base font-bold leading-normal">
          <SwSharedPrice
            value={displayFromVariants}
            ctx={ctx}
            beforePrice={
              <span className="text-sm">
                {translations.listing.variantsFrom}
              </span>
            }
          />
        </div>
      ) : null}

      {regulationPrice ? (
        <div className="flex gap-2 text-surface-on-surface-variant text-sm">
          {translations.listing.previously}
          <SwSharedPrice value={regulationPrice} ctx={ctx} />
        </div>
      ) : null}
    </div>
  );
}
