// packages/cms-base-layer/app/components/SwListingProductPrice.vue
<script setup lang="ts">
import { useCmsTranslations, useProductPrice } from "@shopware/composables";
import { defu } from "defu";
import { toRefs } from "vue";
import type { Schemas } from "#shopware";

const props = defineProps<{
  product: Schemas["Product"];
}>();

type Translations = {
  listing: {
    variantsFrom: string;
    previously: string;
    from: string;
    to: string;
  };
};

let translations: Translations = {
  listing: {
    variantsFrom: "variants from",
    previously: "previously",
    from: "from",
    to: "to",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const { product } = toRefs(props);

const {
  price,
  unitPrice,
  displayFromVariants,
  displayFrom,
  hasListPrice,
  regulationPrice,
} = useProductPrice(product);
</script>

<template>
  <div :id="product.id" class="inline-flex justify-start items-center gap-2">
    <!-- Sale price display -->
    <div v-if="hasListPrice" class="flex items-center gap-2">
      <div class="text-base font-bold leading-normal">
        <SwSharedPrice :value="unitPrice">
          <template #beforePrice>
            <span v-if="displayFrom || displayFromVariants" class="text-sm">{{
              translations.listing.from
            }}</span>
          </template>
        </SwSharedPrice>
      </div>
      <div class="text-surface-on-surface-variant text-sm font-normal leading-tight line-through">
        <SwSharedPrice :value="price?.listPrice?.price" />
      </div>
    </div>

    <!-- Regular price display -->
    <div v-else class="text-surface-on-surface text-base font-bold leading-normal">
      <SwSharedPrice :value="unitPrice">
        <template #beforePrice>
          <span v-if="displayFrom || displayFromVariants" class="text-sm">{{
            translations.listing.from
          }}</span>
        </template>
      </SwSharedPrice>
    </div>

    <!-- Variants from price -->
    <div v-if="displayFromVariants" class="text-surface-on-surface text-base font-bold leading-normal">
      <SwSharedPrice :value="displayFromVariants">
        <template #beforePrice>
          <span v-if="displayFromVariants" class="text-sm">{{
            translations.listing.variantsFrom
          }}</span>
        </template>
      </SwSharedPrice>
    </div>

    <!-- Regulation price -->
    <div v-if="regulationPrice" class="flex gap-2 text-surface-on-surface-variant text-sm">
      {{ translations.listing.previously }}
      <SwSharedPrice :value="regulationPrice" />
    </div>
  </div>
</template>

// packages/cms-base-layer-react/src/components/shared/SwListingProductPrice.tsx
import type { ComponentProps } from "react";

import type { Schemas } from "#shopware";

import type { CmsClientContext } from "../../context";
import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import { getProductPrice } from "./productPrice";
import { SwSharedPrice } from "./SwSharedPrice";

export type ProductPriceContext = Pick<
  CmsClientContext,
  "locale" | "currencyCode" | "translations"
>;

export type SwListingProductPriceProps = Omit<
  ComponentProps<"div">,
  "children"
> & {
  product: Schemas["Product"];
  ctx: ProductPriceContext;
};

const translationDefaults = {
  listing: {
    variantsFrom: "variants from",
    previously: "previously",
    from: "from",
    to: "to",
  },
};

export function SwListingProductPrice({
  product,
  ctx,
  className,
  ...props
}: SwListingProductPriceProps) {
  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );
  const {
    price,
    unitPrice,
    displayFromVariants,
    displayFrom,
    hasListPrice,
    regulationPrice,
  } = getProductPrice(product);

  const fromLabel =
    displayFrom || displayFromVariants ? (
      <span className="text-sm">{translations.listing.from}</span>
    ) : null;

  return (
    <div
      {...props}
      className={cx("inline-flex justify-start items-center gap-2", className)}
    >
      {hasListPrice ? (
        <div className="flex items-center gap-2">
          <div className="text-base font-bold leading-normal">
            <SwSharedPrice
              value={unitPrice}
              ctx={ctx}
              beforePrice={fromLabel}
            />
          </div>
          <div className="text-surface-on-surface-variant text-sm font-normal leading-tight line-through">
            <SwSharedPrice value={price?.listPrice?.price} ctx={ctx} />
          </div>
        </div>
      ) : (
        <div className="text-surface-on-surface text-base font-bold leading-normal">
          <SwSharedPrice value={unitPrice} ctx={ctx} beforePrice={fromLabel} />
        </div>
      )}

      {displayFromVariants ? (
        <div className="text-surface-on-surface text-base font-bold leading-normal">
          <SwSharedPrice
            value={displayFromVariants}
            ctx={ctx}
            beforePrice={
              <span className="text-sm">
                {translations.listing.variantsFrom}
              </span>
            }
          />
        </div>
      ) : null}

      {regulationPrice ? (
        <div className="flex gap-2 text-surface-on-surface-variant text-sm">
          {translations.listing.previously}
          <SwSharedPrice value={regulationPrice} ctx={ctx} />
        </div>
      ) : null}
    </div>
  );
}
