// packages/cms-base/components/SwNewsletterForm.vue
<script setup lang="ts">
import { useVuelidate } from "@vuelidate/core";
import { required, email } from "@vuelidate/validators";
import type { CmsElementForm } from "@shopware-pwa/composables-next";
import { useCmsTranslations } from "@shopware-pwa/composables-next";
import { ApiClientError, type ApiError } from "@shopware/api-client";
import { useCmsElementConfig, useNewsletter, useSalutations } from "#imports";
import { computed, reactive, ref } from "vue";
import { defu } from "defu";

const props = defineProps<{
  content: CmsElementForm;
}>();

type Translations = {
  form: {
    subscribeLabel: string;
    unsubscribeLabel: string;
    action: string;
    email: string;
    emailPlaceholder: string;
    salutation: string;
    salutationPlaceholder: string;
    firstName: string;
    firstNamePlaceholder: string;
    lastName: string;
    lastNamePlaceholder: string;
    privacy: string;
    privacyLabel: string;
    submit: string;
    newsletterBenefits: string;
  };
};

let translations: Translations = {
  form: {
    subscribeLabel: "Subscribe to newsletter",
    unsubscribeLabel: "Unsubscribe from newsletter",
    action: "Action",
    email: "Email address",
    emailPlaceholder: "Enter email address...",
    salutation: "Salutation",
    salutationPlaceholder: "Enter salutation...",
    firstName: "First name",
    firstNamePlaceholder: "Enter first name...",
    lastName: "Last name",
    lastNamePlaceholder: "Enter last name...",
    privacy: "Privacy",
    privacyLabel: "I have read the data protection information.",
    submit: "Submit",
    newsletterBenefits:
      "Be aware of upcoming sales and events.Receive gifts and special offers!",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const loading = ref<boolean>();
const formSent = ref<boolean>(false);
const errorMessages = ref<ApiError[]>([]);
const subscriptionOptions: {
  label: string;
  value: "subscribe" | "unsubscribe";
}[] = [
  {
    label: translations.form.subscribeLabel,
    value: "subscribe",
  },
  {
    label: translations.form.unsubscribeLabel,
    value: "unsubscribe",
  },
];
const { getSalutations } = useSalutations();
const { getConfigValue } = useCmsElementConfig(props.content);
const { newsletterSubscribe, newsletterUnsubscribe } = useNewsletter();

const getFormTitle = computed(() => getConfigValue("title"));
const state = reactive({
  option: subscriptionOptions[0].value,
  salutationId: "",
  firstName: "",
  lastName: "",
  email: "",
  checkbox: false,
});

const rules = computed(() => {
  let temp: any = {
    email: {
      required,
      email,
    },
    checkbox: {
      required,
      isTrue: (value: any) => value === true,
    },
  };
  if (state.option === "subscribe") {
    temp = {
      ...temp,
      firstName: {
        required,
        minLength: 3,
      },
      lastName: {
        required,
        minLength: 3,
      },
      salutationId: {
        required,
      },
    };
  }
  return temp;
});

const $v = useVuelidate(rules, state);
const invokeSubmit = async () => {
  $v.value.$touch();
  const valid = await $v.value.$validate();
  if (valid) {
    loading.value = true;
    try {
      if (state.option === "subscribe") {
        await newsletterSubscribe({
          ...state,
        });
      } else {
        await newsletterUnsubscribe(state.email);
      }
      formSent.value = true;
    } catch (e) {
      if (e instanceof ApiClientError) {
        errorMessages.value = e.details.errors;
      }
    } finally {
      loading.value = false;
    }
  }
};
</script>
<template>
  <form class="w-full relative" @submit.prevent="invokeSubmit">
    <div
      v-if="loading"
      class="absolute inset-0 flex items-center justify-center z-10 bg-white/50"
    >
      <div
        class="h-15 w-15 i-carbon-progress-bar-round animate-spin c-gray-500"
      />
    </div>
    <h3 class="pb-3 mb-10 border-b border-gray-300">
      {{
        getFormTitle
          ? getFormTitle
          : state.option === "subscribe"
            ? translations.form.subscribeLabel
            : translations.form.unsubscribeLabel
      }}
    </h3>
    <template v-if="!formSent">
      <div class="grid grid-cols-12 gap-5">
        <div class="col-span-12">
          <label for="option">{{ translations.form.action }} *</label>
          <select
            id="option"
            name="option"
            class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            v-model="state.option"
          >
            <option
              v-for="subscription in subscriptionOptions"
              :key="subscription.value"
              :value="subscription.value"
            >
              {{ subscription.label }}
            </option>
          </select>
        </div>
        <div class="col-span-12">
          <label for="email-address">{{ translations.form.email }} *</label>
          <input
            id="email-address"
            name="email"
            type="email"
            autocomplete="email"
            :class="[
              $v.email.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-gray-300 focus:border-indigo-500',
            ]"
            v-model="state.email"
            @blur="$v.email.$touch()"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :placeholder="translations.form.emailPlaceholder"
          />
          <span
            v-if="$v.email.$error"
            class="pt-1 text-sm text-red-600 focus:ring-brand-primary border-gray-300"
          >
            {{ $v.email.$errors[0].$message }}
          </span>
        </div>
        <div v-if="state.option === 'subscribe'" class="col-span-4">
          <label for="salutation">{{ translations.form.salutation }} *</label>
          <select
            id="salutation"
            name="salutation"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.salutationId.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-gray-300 focus:border-indigo-500',
            ]"
            v-model="state.salutationId"
            @blur="$v.salutationId.$touch()"
          >
            <option disabled selected value="">
              {{ translations.form.salutationPlaceholder }}
            </option>
            <option
              v-for="salutation in getSalutations"
              :key="salutation.id"
              :value="salutation.id"
            >
              {{ salutation.displayName }}
            </option>
          </select>
          <span
            v-if="$v.salutationId.$error"
            class="pt-1 text-sm text-red-600 focus:ring-brand-primary border-gray-300"
          >
            {{ $v.salutationId.$errors[0].$message }}
          </span>
        </div>
        <div v-if="state.option === 'subscribe'" class="col-span-4">
          <label for="first-name">{{ translations.form.firstName }} *</label>
          <input
            id="first-name"
            name="first-name"
            type="text"
            autocomplete="first-name"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.firstName.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-gray-300 focus:border-indigo-500',
            ]"
            @blur="$v.firstName.$touch()"
            v-model="state.firstName"
            :placeholder="translations.form.firstNamePlaceholder"
          />
          <span
            v-if="$v.firstName.$error"
            class="pt-1 text-sm text-red-600 focus:ring-brand-primary border-gray-300"
          >
            {{ $v.firstName.$errors[0].$message }}
          </span>
        </div>
        <div v-if="state.option === 'subscribe'" class="col-span-4">
          <label for="last-name">{{ translations.form.lastName }} *</label>
          <input
            id="last-name"
            name="last-name"
            type="text"
            autocomplete="last-name"
            v-model="state.lastName"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.lastName.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-gray-300 focus:border-indigo-500',
            ]"
            @blur="$v.lastName.$touch()"
            :placeholder="translations.form.lastNamePlaceholder"
          />
          <span
            v-if="$v.lastName.$error"
            class="pt-1 text-sm text-red-600 focus:ring-brand-primary border-gray-300"
          >
            {{ $v.lastName.$errors[0].$message }}
          </span>
        </div>
        <div class="col-span-12">
          <label>{{ translations.form.privacy }} *</label>
          <div class="flex gap-3 items-start">
            <input
              id="privacy"
              name="privacy"
              type="checkbox"
              v-model="state.checkbox"
              class="mt-1 focus:ring-indigo-500 h-4 w-4 border text-indigo-600 rounded"
              :class="[
                $v.checkbox.$error ? 'border-red-600' : 'border-gray-300',
              ]"
            />
            <div>
              <label
                :class="[$v.checkbox.$error ? 'text-red-600' : '']"
                for="privacy"
              >
                {{ translations.form.privacyLabel }}
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="flex justify-end mt-10">
        <button
          class="group relative flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-75"
          type="submit"
        >
          {{ translations.form.submit }}
        </button>
      </div>
    </template>
    <template v-else>
      <p class="py-10 text-lg text-center">
        {{ translations.form.newsletterBenefits }}
      </p>
    </template>
  </form>
</template>

// packages/cms-base-layer-react/src/components/shared/SwNewsletterForm.tsx
"use client";

import { useId, useState } from "react";
import type { FormEvent } from "react";

import { useCmsActions } from "../../actions/CmsActionsContext";
import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import type { CmsTranslations } from "../../translations";
import { SpinnerIcon } from "../icons";
import type { SwFormSalutation } from "./formSalutations";
import { email, isTrue, minLength, required } from "./formValidation";
import type { FormRules } from "./formValidation";
import { useFormValidation } from "./useFormValidation";

const defaultTranslations = {
  form: {
    subscribeLabel: "Subscribe to newsletter",
    unsubscribeLabel: "Unsubscribe from newsletter",
    action: "Action",
    email: "Email address",
    emailPlaceholder: "Enter email address...",
    salutation: "Salutation",
    salutationPlaceholder: "Enter salutation...",
    firstName: "First name",
    firstNamePlaceholder: "Enter first name...",
    lastName: "Last name",
    lastNamePlaceholder: "Enter last name...",
    privacy: "Privacy",
    privacyLabel: "I have read the data protection information.",
    submit: "Submit",
    newsletterBenefits:
      "Be aware of upcoming sales and events.Receive gifts and special offers!",
  },
};

const INPUT_CLASS =
  "appearance-none relative block w-full px-3 py-2 border placeholder-surface-on-surface-variant text-surface-on-surface rounded-md focus:outline-hidden focus:ring-brand-primary focus:z-10 sm:text-sm";
const INPUT_ERROR_CLASS = "border-red-600 focus:border-red-600";
const INPUT_VALID_CLASS =
  "border-outline-outline-variant focus:border-brand-primary";
const ERROR_MESSAGE_CLASS =
  "pt-1 text-sm text-red-600 focus:ring-brand-primary border-gray-300";

type NewsletterOption = "subscribe" | "unsubscribe";

type NewsletterFormValues = {
  option: NewsletterOption;
  salutationId: string;
  firstName: string;
  lastName: string;
  email: string;
  checkbox: boolean;
};

const INITIAL_VALUES: NewsletterFormValues = {
  option: "subscribe",
  salutationId: "",
  firstName: "",
  lastName: "",
  email: "",
  checkbox: false,
};

function getRules(option: NewsletterOption): FormRules<NewsletterFormValues> {
  const rules: FormRules<NewsletterFormValues> = {
    email: [required, email],
    checkbox: [required, isTrue],
  };
  if (option === "subscribe") {
    rules.firstName = [required, minLength(3)];
    rules.lastName = [required, minLength(3)];
  }
  return rules;
}

function toNewsletterOption(value: string): NewsletterOption {
  return value === "unsubscribe" ? "unsubscribe" : "subscribe";
}

export type SwNewsletterFormProps = {
  title?: string;
  salutations: SwFormSalutation[];
  translations?: CmsTranslations;
};

export function SwNewsletterForm({
  title,
  salutations,
  translations,
}: SwNewsletterFormProps) {
  const t = withTranslationDefaults(translations, defaultTranslations);
  const idPrefix = useId();
  const actions = useCmsActions();
  const [loading, setLoading] = useState(false);
  const [formSent, setFormSent] = useState(false);
  const [values, setValues] = useState<NewsletterFormValues>(INITIAL_VALUES);
  const { isValid, touch, touchAll, hasError, errorMessage } =
    useFormValidation(values, getRules(values.option));

  const subscriptionOptions: { label: string; value: NewsletterOption }[] = [
    { label: t.form.subscribeLabel, value: "subscribe" },
    { label: t.form.unsubscribeLabel, value: "unsubscribe" },
  ];

  const isSubscribe = values.option === "subscribe";
  const formTitle =
    title || (isSubscribe ? t.form.subscribeLabel : t.form.unsubscribeLabel);

  const setValue = <KEY extends keyof NewsletterFormValues>(
    key: KEY,
    value: NewsletterFormValues[KEY],
  ) => {
    setValues((current) => ({ ...current, [key]: value }));
  };

  const inputClass = (key: keyof NewsletterFormValues) =>
    cx(INPUT_CLASS, hasError(key) ? INPUT_ERROR_CLASS : INPUT_VALID_CLASS);

  const renderError = (key: keyof NewsletterFormValues) => {
    const message = errorMessage(key);
    return message ? (
      <span className={ERROR_MESSAGE_CLASS}>{message}</span>
    ) : null;
  };

  async function invokeSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    touchAll();
    if (!isValid) return;
    setLoading(true);
    try {
      const result = isSubscribe
        ? await actions.subscribeNewsletter({
            email: values.email,
            option: "subscribe",
            firstName: values.firstName,
            lastName: values.lastName,
            salutationId: values.salutationId || undefined,
          })
        : await actions.subscribeNewsletter({
            email: values.email,
            option: "unsubscribe",
          });
      if (result.ok) {
        setFormSent(true);
        return;
      }
      if (result.message) {
        actions.notify({ type: "error", message: result.message });
      }
    } catch (error) {
      actions.notify({
        type: "error",
        message: error instanceof Error ? error.message : String(error),
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <form
      className="w-full relative"
      onSubmit={(event) => {
        void invokeSubmit(event);
      }}
    >
      {loading && (
        <div className="absolute inset-0 flex items-center justify-center z-10 bg-white/50">
          <SpinnerIcon className="h-15 w-15 animate-spin text-gray-500" />
        </div>
      )}
      <h3 className="pb-3 mb-10 border-b border-gray-300">{formTitle}</h3>
      {!formSent ? (
        <>
          <div className="grid grid-cols-12 gap-5">
            <div className="col-span-12">
              <label
                htmlFor={`${idPrefix}option`}
              >{`${t.form.action} *`}</label>
              <select
                id={`${idPrefix}option`}
                name="option"
                value={values.option}
                onChange={(event) =>
                  setValue("option", toNewsletterOption(event.target.value))
                }
                className="appearance-none relative block w-full px-3 py-2 border border-outline-outline-variant placeholder-surface-on-surface-variant text-surface-on-surface rounded-md focus:border-brand-primary focus:outline-hidden focus:ring-brand-primary focus:z-10 sm:text-sm"
              >
                {subscriptionOptions.map((subscription) => (
                  <option key={subscription.value} value={subscription.value}>
                    {subscription.label}
                  </option>
                ))}
              </select>
            </div>
            <div className="col-span-12">
              <label htmlFor={`${idPrefix}email-address`}>
                {`${t.form.email} *`}
              </label>
              <input
                id={`${idPrefix}email-address`}
                name="email"
                type="email"
                autoComplete="email"
                value={values.email}
                onChange={(event) => setValue("email", event.target.value)}
                onBlur={() => touch("email")}
                className={inputClass("email")}
                placeholder={t.form.emailPlaceholder}
              />
              {renderError("email")}
            </div>
            {isSubscribe && (
              <div className="col-span-4">
                <label htmlFor={`${idPrefix}salutation`}>
                  {`${t.form.salutation} *`}
                </label>
                <select
                  id={`${idPrefix}salutation`}
                  name="salutation"
                  value={values.salutationId}
                  onChange={(event) =>
                    setValue("salutationId", event.target.value)
                  }
                  className="border-outline-outline-variant focus:border-brand-primary appearance-none relative block w-full px-3 py-2 border placeholder-surface-on-surface-variant text-surface-on-surface rounded-md focus:outline-hidden focus:ring-brand-primary focus:z-10 sm:text-sm"
                >
                  <option disabled value="">
                    {t.form.salutationPlaceholder}
                  </option>
                  {salutations.map((salutation) => (
                    <option key={salutation.id} value={salutation.id}>
                      {salutation.displayName}
                    </option>
                  ))}
                </select>
              </div>
            )}
            {isSubscribe && (
              <div className="col-span-4">
                <label htmlFor={`${idPrefix}first-name`}>
                  {`${t.form.firstName} *`}
                </label>
                <input
                  id={`${idPrefix}first-name`}
                  name="first-name"
                  type="text"
                  autoComplete="given-name"
                  value={values.firstName}
                  onChange={(event) =>
                    setValue("firstName", event.target.value)
                  }
                  onBlur={() => touch("firstName")}
                  className={inputClass("firstName")}
                  placeholder={t.form.firstNamePlaceholder}
                />
                {renderError("firstName")}
              </div>
            )}
            {isSubscribe && (
              <div className="col-span-4">
                <label htmlFor={`${idPrefix}last-name`}>
                  {`${t.form.lastName} *`}
                </label>
                <input
                  id={`${idPrefix}last-name`}
                  name="last-name"
                  type="text"
                  autoComplete="family-name"
                  value={values.lastName}
                  onChange={(event) => setValue("lastName", event.target.value)}
                  onBlur={() => touch("lastName")}
                  className={inputClass("lastName")}
                  placeholder={t.form.lastNamePlaceholder}
                />
                {renderError("lastName")}
              </div>
            )}
            <fieldset className="col-span-12">
              <legend>{`${t.form.privacy} *`}</legend>
              <div className="flex gap-3 items-start">
                <input
                  id={`${idPrefix}privacy`}
                  name="privacy"
                  type="checkbox"
                  checked={values.checkbox}
                  onChange={(event) =>
                    setValue("checkbox", event.target.checked)
                  }
                  className={cx(
                    "mt-1 focus:ring-brand-primary h-4 w-4 border text-brand-primary rounded",
                    hasError("checkbox") ? "border-red-600" : "border-gray-300",
                  )}
                />
                <div>
                  <label
                    className={
                      hasError("checkbox") ? "text-red-600" : undefined
                    }
                    htmlFor={`${idPrefix}privacy`}
                  >
                    {t.form.privacyLabel}
                  </label>
                </div>
              </div>
            </fieldset>
          </div>
          <div className="flex justify-end mt-10">
            <button
              className="group relative flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-brand-primary hover:bg-brand-primary-hover focus:outline-hidden focus:ring-2 focus:ring-brand-primary disabled:opacity-75"
              type="submit"
            >
              {t.form.submit}
            </button>
          </div>
        </>
      ) : (
        <p className="py-10 text-lg text-center">{t.form.newsletterBenefits}</p>
      )}
    </form>
  );
}
