// packages/cms-base/components/SwPagination.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    total: number;
    current: number;
    translations?: {
      previous: string
      next: string
    }
  }>(), {
  translations: () => ({
    previous: "Previous",
    next: "Next"
  })
});


defineEmits<{
  (e: "changePage", page: number): void;
}>();
</script>
<template>
  <div
    v-if="total > 1"
    class="bg-white justify-center px-4 py-3 flex border-t border-gray-200 sm:px-6"
  >
    <nav
      class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px"
      aria-label="Pagination"
    >
      <button
        v-if="current - 1 >= 1"
        @click="$emit('changePage', current - 1)"
        class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50"
      >
        <span class="w-10 h-10 i-carbon-chevron-left text-blue-700"></span>
        <span class="sr-only">{{props.translations.previous}}</span>
      </button>
      <button
        v-if="current > 2"
        @click="$emit('changePage', 1)"
        aria-current="page"
        class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
      >
        1
      </button>
      <span
        v-if="current - 1 > 2"
        class="relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700"
      >
        ...
      </span>
      <button
        v-if="current > 1"
        @click="$emit('changePage', current - 1)"
        aria-current="page"
        class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
      >
        {{ current - 1 }}
      </button>
      <button
        aria-current="page"
        class="bg-indigo-50 border-indigo-500 text-indigo-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
      >
        {{ current }}
      </button>
      <button
        v-if="current < total"
        @click="$emit('changePage', current + 1)"
        aria-current="page"
        class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
      >
        {{ current + 1 }}
      </button>
      <span
        v-if="total - current > 2"
        class="relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700"
      >
        ...
      </span>
      <button
        v-if="total - current > 1"
        @click="$emit('changePage', total)"
        class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
      >
        {{ total }}
      </button>
      <button
        v-if="total > current + 1"
        @click="$emit('changePage', total)"
        class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50"
      >
        <span class="sr-only">{{props.translations.next}}</span>
        <span class="w-10 h-10 i-carbon-chevron-right text-blue-700"></span>
      </button>
    </nav>
  </div>
</template>

// packages/cms-base-layer-react/src/components/shared/SwPagination.tsx
"use client";

import type { CSSProperties } from "react";

import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import type { CmsTranslations } from "../../translations";
import { ChevronLeftIcon, ChevronRightIcon } from "../icons";

export type SwPaginationProps = {
  total: number;
  current: number;
  onChangePage: (page: number) => void;
  translations?: CmsTranslations;
  className?: string;
  style?: CSSProperties;
};

const translationDefaults = {
  listing: {
    previous: "Previous",
    next: "Next",
  },
};

const PAGE_BUTTON_CLASS =
  "bg-white border-outline-outline-variant text-surface-on-surface-variant hover:bg-surface-surface-container-low relative inline-flex items-center px-4 py-2 border text-sm font-medium";

const ELLIPSIS_CLASS =
  "relative inline-flex items-center px-4 py-2 border border-outline-outline-variant bg-white text-sm font-medium text-surface-on-surface";

export function SwPagination({
  total,
  current,
  onChangePage,
  translations,
  className,
  style,
}: SwPaginationProps) {
  const t = withTranslationDefaults(translations, translationDefaults);

  return (
    <nav
      className={cx(
        "relative z-0 inline-flex rounded-md shadow-xs space-x-px",
        className,
      )}
      style={style}
      aria-label="Pagination"
    >
      {current - 1 >= 2 && (
        <button
          type="button"
          className="relative inline-flex items-center px-2 py-2 rounded-l-md border border-outline-outline-variant bg-white text-sm font-medium text-surface-on-surface-variant hover:bg-surface-surface-container-low"
          onClick={() => onChangePage(current - 1)}
        >
          <span className="sr-only">{t.listing.previous}</span>
          <ChevronLeftIcon
            width={20}
            height={20}
            className="transition-transform"
          />
        </button>
      )}
      {current > 2 && (
        <button
          type="button"
          className={PAGE_BUTTON_CLASS}
          onClick={() => onChangePage(1)}
        >
          <span className="sr-only">Page </span>1
        </button>
      )}
      {current - 1 > 2 && <span className={ELLIPSIS_CLASS}>...</span>}
      {current > 1 && (
        <button
          type="button"
          className={cx(
            PAGE_BUTTON_CLASS,
            current === 2 &&
              "rounded-l-md border border-outline-outline-variant",
          )}
          onClick={() => onChangePage(current - 1)}
        >
          <span className="sr-only">Page </span>
          {current - 1}
        </button>
      )}
      <button
        type="button"
        aria-current="page"
        className={cx(
          "bg-surface-surface-primary border-brand-primary text-brand-primary relative inline-flex items-center px-4 py-2 border text-sm font-medium",
          current - 1 >= 1
            ? ""
            : "rounded-l-md border border-outline-outline-variant",
          total === current &&
            "rounded-r-md border border-outline-outline-variant",
        )}
      >
        <span className="sr-only">Page </span>
        {current}
      </button>
      {current < total && (
        <button
          type="button"
          className={cx(
            PAGE_BUTTON_CLASS,
            total === current + 1 &&
              "rounded-r-md border border-outline-outline-variant",
          )}
          onClick={() => onChangePage(current + 1)}
        >
          <span className="sr-only">Page </span>
          {current + 1}
        </button>
      )}
      {total - current > 2 && <span className={ELLIPSIS_CLASS}>...</span>}
      {total - current > 1 && (
        <button
          type="button"
          className={PAGE_BUTTON_CLASS}
          onClick={() => onChangePage(total)}
        >
          {total}
        </button>
      )}
      {total > current + 1 && (
        <button
          type="button"
          className="relative inline-flex items-center px-2 py-2 rounded-r-md border border-outline-outline-variant bg-white text-sm font-medium text-surface-on-surface-variant hover:bg-surface-surface-container-low"
          onClick={() => onChangePage(current + 1)}
        >
          <span className="sr-only">{t.listing.next}</span>
          <ChevronRightIcon
            width={20}
            height={20}
            className="transition-transform"
          />
        </button>
      )}
    </nav>
  );
}
