// templates/vue-demo-store/components/SwPagination.vue
<script setup lang="ts">
import {
  ArrowLeftIcon,
  ArrowRightIcon,
} from '@heroicons/vue/24/outline';
</script>
<template>
  <nav class="isolate inline-flex" aria-label="Pagination">
    <a href="#" class="relative inline-flex items-center mx-6 md:px-2 md:py-2 text-gray-400 focus:z-20 focus:outline-offset-0">
      <span class="sr-only">Previous</span>
      <ArrowLeftIcon class="h-6 w-6 text-gray-900 md:text-gray-500" aria-hidden="true" />
    </a>
    <a href="#" aria-current="page" class="relative z-10 inline-flex items-center px-1 md:px-4 md:py-2.25 text-lg md:text-sm font-medium text-dark-primary md:text-gray-900 focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">1</a>
    <a href="#" class="relative inline-flex items-center px-1 md:px-4 md:py-2.25 text-lg md:text-sm font-medium text-text-muted md:text-gray-500 focus:z-20 focus:outline-offset-0">2</a>
    <a href="#" class="relative inline-flex items-center px-1 md:px-4 md:py-2.25 text-lg md:text-sm font-medium text-text-muted md:text-gray-500 focus:z-20 focus:outline-offset-0">3</a>
    <span class="relative inline-flex items-center px-1 md:px -4 md:py-2.25 text-lg md:text-sm font-semibold text-dark-primary md:text-gray-500 focus:outline-offset-0">...</span>
    <a href="#" class="relative inline-flex items-center px-1 md:px-4 md:py-2.25 text-lg md:text-sm font-medium text-text-muted md:text-gray-500 focus:z-20 focus:outline-offset-0">10</a>
    <a href="#" class="relative inline-flex items-center mx-6 md:px-2 md:py-2 text-gray-400 focus:z-20 focus:outline-offset-0">
      <span class="sr-only">Next</span>
      <ArrowRightIcon class="h-6 w-6 text-gray-900 md:text-gray-500" aria-hidden="true" />
    </a>
  </nav>
</template>

// packages/cms-base-layer-react/src/components/shared/SwPagination.tsx
"use client";

import type { CSSProperties } from "react";

import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import type { CmsTranslations } from "../../translations";
import { ChevronLeftIcon, ChevronRightIcon } from "../icons";

export type SwPaginationProps = {
  total: number;
  current: number;
  onChangePage: (page: number) => void;
  translations?: CmsTranslations;
  className?: string;
  style?: CSSProperties;
};

const translationDefaults = {
  listing: {
    previous: "Previous",
    next: "Next",
  },
};

const PAGE_BUTTON_CLASS =
  "bg-white border-outline-outline-variant text-surface-on-surface-variant hover:bg-surface-surface-container-low relative inline-flex items-center px-4 py-2 border text-sm font-medium";

const ELLIPSIS_CLASS =
  "relative inline-flex items-center px-4 py-2 border border-outline-outline-variant bg-white text-sm font-medium text-surface-on-surface";

export function SwPagination({
  total,
  current,
  onChangePage,
  translations,
  className,
  style,
}: SwPaginationProps) {
  const t = withTranslationDefaults(translations, translationDefaults);

  return (
    <nav
      className={cx(
        "relative z-0 inline-flex rounded-md shadow-xs space-x-px",
        className,
      )}
      style={style}
      aria-label="Pagination"
    >
      {current - 1 >= 2 && (
        <button
          type="button"
          className="relative inline-flex items-center px-2 py-2 rounded-l-md border border-outline-outline-variant bg-white text-sm font-medium text-surface-on-surface-variant hover:bg-surface-surface-container-low"
          onClick={() => onChangePage(current - 1)}
        >
          <span className="sr-only">{t.listing.previous}</span>
          <ChevronLeftIcon
            width={20}
            height={20}
            className="transition-transform"
          />
        </button>
      )}
      {current > 2 && (
        <button
          type="button"
          className={PAGE_BUTTON_CLASS}
          onClick={() => onChangePage(1)}
        >
          <span className="sr-only">Page </span>1
        </button>
      )}
      {current - 1 > 2 && <span className={ELLIPSIS_CLASS}>...</span>}
      {current > 1 && (
        <button
          type="button"
          className={cx(
            PAGE_BUTTON_CLASS,
            current === 2 &&
              "rounded-l-md border border-outline-outline-variant",
          )}
          onClick={() => onChangePage(current - 1)}
        >
          <span className="sr-only">Page </span>
          {current - 1}
        </button>
      )}
      <button
        type="button"
        aria-current="page"
        className={cx(
          "bg-surface-surface-primary border-brand-primary text-brand-primary relative inline-flex items-center px-4 py-2 border text-sm font-medium",
          current - 1 >= 1
            ? ""
            : "rounded-l-md border border-outline-outline-variant",
          total === current &&
            "rounded-r-md border border-outline-outline-variant",
        )}
      >
        <span className="sr-only">Page </span>
        {current}
      </button>
      {current < total && (
        <button
          type="button"
          className={cx(
            PAGE_BUTTON_CLASS,
            total === current + 1 &&
              "rounded-r-md border border-outline-outline-variant",
          )}
          onClick={() => onChangePage(current + 1)}
        >
          <span className="sr-only">Page </span>
          {current + 1}
        </button>
      )}
      {total - current > 2 && <span className={ELLIPSIS_CLASS}>...</span>}
      {total - current > 1 && (
        <button
          type="button"
          className={PAGE_BUTTON_CLASS}
          onClick={() => onChangePage(total)}
        >
          {total}
        </button>
      )}
      {total > current + 1 && (
        <button
          type="button"
          className="relative inline-flex items-center px-2 py-2 rounded-r-md border border-outline-outline-variant bg-white text-sm font-medium text-surface-on-surface-variant hover:bg-surface-surface-container-low"
          onClick={() => onChangePage(current + 1)}
        >
          <span className="sr-only">{t.listing.next}</span>
          <ChevronRightIcon
            width={20}
            height={20}
            className="transition-transform"
          />
        </button>
      )}
    </nav>
  );
}
