// packages/cms-base-layer/app/components/SwProductListingFilters.vue
<script setup lang="ts">
import type {
  CmsElementProductListing,
  CmsElementSidebarFilter,
} from "@shopware/composables";
import { useCmsTranslations } from "@shopware/composables";
import { defu } from "defu";
import { computed, reactive } from "vue";
import type { ComputedRef, UnwrapNestedRefs } from "vue";
import type { LocationQueryRaw } from "vue-router";
import { useCategoryListing, useRoute, useRouter } from "#imports";
import type { Schemas, operations } from "#shopware";

const props = defineProps<{
  content?: CmsElementProductListing | CmsElementSidebarFilter;
  listingType?: string;
}>();

type Translations = {
  listing: {
    filters: string;
    sort: string;
    resetFilters: string;
  };
};

type FilterState = {
  manufacturer: Set<string>;
  properties: Set<string>;
  "min-price": number | undefined;
  "max-price": number | undefined;
  rating: number | undefined;
  "shipping-free": boolean | undefined;
};

let translations: Translations = {
  listing: {
    filters: "Filters",
    sort: "Sort",
    resetFilters: "Reset filters",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const route = useRoute();
const router = useRouter();

const {
  changeCurrentSortingOrder,
  getCurrentFilters,
  getCurrentSortingOrder,
  getInitialFilters,
  getSortingOrders,
  search,
} = useCategoryListing();

const sidebarSelectedFilters: UnwrapNestedRefs<FilterState> =
  reactive<FilterState>({
    manufacturer: new Set(),
    properties: new Set(),
    "min-price": undefined,
    "max-price": undefined,
    rating: undefined,
    "shipping-free": undefined,
  });

const showResetFiltersButton = computed<boolean>(() => {
  if (
    sidebarSelectedFilters.manufacturer.size !== 0 ||
    sidebarSelectedFilters.properties.size !== 0 ||
    sidebarSelectedFilters["max-price"] ||
    sidebarSelectedFilters["min-price"] ||
    sidebarSelectedFilters.rating ||
    sidebarSelectedFilters["shipping-free"]
  ) {
    return true;
  }

  return false;
});

const searchCriteriaForRequest: ComputedRef<Schemas["ProductListingCriteria"]> =
  computed(() => ({
    manufacturer: [
      ...(sidebarSelectedFilters.manufacturer as Set<string>),
    ]?.join("|"),
    properties: [...(sidebarSelectedFilters.properties as Set<string>)]?.join(
      "|",
    ),
    "min-price": sidebarSelectedFilters["min-price"] as number,
    "max-price": sidebarSelectedFilters["max-price"] as number,
    order: getCurrentSortingOrder.value as string,
    "shipping-free": sidebarSelectedFilters["shipping-free"] as boolean,
    rating: sidebarSelectedFilters.rating as number,
    search: "",
    limit: route.query.limit ? Number(route.query.limit) : 15,
  }));

for (const param in route.query) {
  if (param in sidebarSelectedFilters) {
    const queryValue = route.query[param];

    // Skip arrays
    if (Array.isArray(queryValue)) continue;

    if (["manufacturer", "properties"].includes(param)) {
      if (typeof queryValue === "string") {
        const elements = queryValue.split("|");
        const targetSet = sidebarSelectedFilters[
          param as keyof FilterState
        ] as Set<string>;
        for (const element of elements) {
          targetSet.add(element);
        }
      }
    } else if (queryValue && typeof queryValue === "string") {
      // Fix: Use specific property assignments instead of generic keyof
      if (param === "min-price") {
        const numValue = Number(queryValue);
        if (!Number.isNaN(numValue)) {
          sidebarSelectedFilters["min-price"] = numValue;
        }
      } else if (param === "max-price") {
        const numValue = Number(queryValue);
        if (!Number.isNaN(numValue)) {
          sidebarSelectedFilters["max-price"] = numValue;
        }
      } else if (param === "rating") {
        const numValue = Number(queryValue);
        if (!Number.isNaN(numValue)) {
          sidebarSelectedFilters.rating = numValue;
        }
      } else if (param === "shipping-free") {
        sidebarSelectedFilters["shipping-free"] = queryValue === "true";
      }
    }
  }
}

const handleFilterChange = async (event: {
  code: string;
  value: string | number | boolean;
}) => {
  try {
    const { code, value } = event;

    if (code === "manufacturer" || code === "properties") {
      const filterSet = sidebarSelectedFilters[code];
      const stringValue = String(value);

      if (filterSet.has(stringValue)) {
        filterSet.delete(stringValue);
      } else {
        filterSet.add(stringValue);
      }
    } else if (code === "min-price" || code === "max-price") {
      sidebarSelectedFilters[code] =
        typeof value === "number" ? value : Number(value);
    } else if (code === "rating") {
      sidebarSelectedFilters.rating = Number(value);
    } else if (code === "shipping-free") {
      sidebarSelectedFilters["shipping-free"] = Boolean(value);
    }

    await executeSearch();
  } catch (error) {
    console.error("Filter update failed:", error);
  }
};

const executeSearch = async () => {
  try {
    await search(searchCriteriaForRequest.value);

    // Build query directly from searchCriteriaForRequest which already has pipe-separated strings
    const criteria = searchCriteriaForRequest.value;
    const query: Record<string, unknown> = {};

    if (criteria.manufacturer) query.manufacturer = criteria.manufacturer;
    if (criteria.properties) query.properties = criteria.properties;
    if (criteria["min-price"]) query["min-price"] = criteria["min-price"];
    if (criteria["max-price"]) query["max-price"] = criteria["max-price"];
    if (criteria.rating) query.rating = criteria.rating;
    if (criteria["shipping-free"])
      query["shipping-free"] = criteria["shipping-free"];
    if (criteria.order) query.order = criteria.order;

    await router.push({
      query: query as LocationQueryRaw,
    });
  } catch (error) {
    console.error("Search execution failed:", error);
  }
};

const clearFilters = () => {
  (sidebarSelectedFilters.manufacturer as Set<string>).clear();
  (sidebarSelectedFilters.properties as Set<string>).clear();
  sidebarSelectedFilters["min-price"] = undefined;
  sidebarSelectedFilters["max-price"] = undefined;
  sidebarSelectedFilters.rating = undefined;
  sidebarSelectedFilters["shipping-free"] = undefined;
};

const currentSortingOrder = computed({
  get: (): string => getCurrentSortingOrder.value || "",
  set: async (order: string): Promise<void> => {
    try {
      await router.push({
        query: {
          ...route.query,
          order,
        },
      });

      await changeCurrentSortingOrder(order, {
        ...(route.query as unknown as operations["searchPage post /search"]["body"]),
        limit: route.query.limit ? Number(route.query.limit) : 15,
      });
    } catch (error) {
      console.error("Sorting order change failed:", error);
    }
  },
});

async function invokeCleanFilters() {
  try {
    clearFilters();
    await executeSearch();
  } catch (error) {
    console.error("Clear filters failed:", error);
  }
}

const handleSortChange = (sortKey: string) => {
  currentSortingOrder.value = sortKey;
};

const handleRemoveFilterChip = async (chip: {
  code: string;
  value: string | number;
}) => {
  if (chip.code === "properties" || chip.code === "manufacturer") {
    const filterSet = sidebarSelectedFilters[chip.code] as Set<string>;
    filterSet.delete(String(chip.value));
  } else if (chip.code === "price") {
    sidebarSelectedFilters["min-price"] = undefined;
    sidebarSelectedFilters["max-price"] = undefined;
  } else if (chip.code === "rating") {
    sidebarSelectedFilters.rating = undefined;
  } else if (chip.code === "shipping-free") {
    sidebarSelectedFilters["shipping-free"] = undefined;
  }

  await executeSearch();
};
</script>
<template>
  <div>
    <!-- Active Filter Chips -->
    <SwFilterChips
      :filters="sidebarSelectedFilters"
      :available-filters="getInitialFilters"
      @remove="handleRemoveFilterChip"
    />

    <!-- Filters Header -->
    <div class="self-stretch flex flex-col justify-start items-start gap-4">
      <div
        class="flex flex-row items-center justify-between w-full mb-4 py-3 border-b border-outline-outline-variant"
      >
        <div
          class="flex-1 text-surface-on-surface text-base font-bold leading-normal"
        >
          {{ translations.listing.filters }}
        </div>
        <SwSortDropdown
          :sort-options="getSortingOrders ?? []"
          :current-sort="getCurrentSortingOrder ?? ''"
          :label="translations.listing.sort"
          @sort-change="handleSortChange"
        />
      </div>
    </div>

    <!-- Filters List -->
    <div class="self-stretch flex flex-col justify-start items-start gap-4">
      <SwProductListingFilter
        v-for="filter in getInitialFilters"
        :key="filter.id"
        :filter="filter"
        :selected-manufacturer="sidebarSelectedFilters.manufacturer"
        :selected-properties="sidebarSelectedFilters.properties"
        :selected-min-price="sidebarSelectedFilters['min-price']"
        :selected-max-price="sidebarSelectedFilters['max-price']"
        :selected-rating="sidebarSelectedFilters.rating"
        :selected-shipping-free="sidebarSelectedFilters['shipping-free']"
        @filter-change="handleFilterChange"
        class="w-full"
      />
      <div v-if="showResetFiltersButton" class="w-full">
        <SwBaseButton
          variant="primary"
          size="medium"
          block
          @click="invokeCleanFilters"
          type="button"
        >
          {{ translations.listing.resetFilters }}
          <span
            class="w-6 h-6 i-carbon-close-filled inline-block align-middle ml-2"
          ></span>
        </SwBaseButton>
      </div>
    </div>
  </div>
</template>

// packages/cms-base-layer-react/src/components/shared/SwProductListingFilters.tsx
"use client";

import type { CSSProperties } from "react";

import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import type { CmsTranslations } from "../../translations";
import { CloseFilledIcon, SpinnerIcon } from "../icons";
import type { ListingFilter, ListingSortOption } from "./listingFilterTypes";
import { SwFilterChips } from "./SwFilterChips";
import { SwProductListingFilter } from "./SwProductListingFilter";
import { SwSortDropdown } from "./SwSortDropdown";
import { useListingFilters } from "./useListingFilters";

export type SwProductListingFiltersProps = {
  filters: ListingFilter[];
  sortOptions?: ListingSortOption[];
  currentSort?: string;
  isProductSearch?: boolean;
  rootCategoryId?: string;
  translations?: CmsTranslations;
  className?: string;
  style?: CSSProperties;
};

const defaultTranslations = {
  listing: {
    filters: "Filters",
    sort: "Sort",
    resetFilters: "Reset filters",
    loading: "Loading",
  },
};

export function SwProductListingFilters({
  filters,
  sortOptions = [],
  currentSort = "",
  isProductSearch = false,
  rootCategoryId,
  translations,
  className,
  style,
}: SwProductListingFiltersProps) {
  const t = withTranslationDefaults(translations, defaultTranslations);
  const {
    selectedFilters,
    visibleFilters,
    showResetFiltersButton,
    currentSortingOrder,
    handleFilterChange,
    handleRemoveFilterChip,
    handleSortChange,
    invokeCleanFilters,
    isPending,
  } = useListingFilters({ filters, isProductSearch, currentSort });

  return (
    <div className={cx(className) || undefined} style={style}>
      <SwFilterChips
        filters={selectedFilters}
        availableFilters={visibleFilters}
        onRemove={handleRemoveFilterChip}
      />

      <div className="self-stretch flex flex-col justify-start items-start gap-4">
        <div className="flex flex-row items-center justify-between w-full mb-4 py-3 border-b border-outline-outline-variant">
          <div className="flex-1 text-surface-on-surface text-base font-bold leading-normal">
            {t.listing.filters}
          </div>
          {isPending && (
            <output
              data-testid="loading"
              className="inline-flex items-center mr-2"
            >
              <SpinnerIcon
                className="w-5 h-5 animate-spin text-brand-primary"
                aria-label={t.listing.loading}
              />
            </output>
          )}
          <SwSortDropdown
            sortOptions={sortOptions}
            currentSort={currentSortingOrder}
            label={t.listing.sort}
            onSortChange={handleSortChange}
          />
        </div>
      </div>

      <div className="self-stretch flex flex-col justify-start items-start gap-4">
        {visibleFilters.map((filter) => (
          <SwProductListingFilter
            key={filter.id ?? filter.code}
            filter={filter}
            selectedManufacturer={selectedFilters.manufacturer}
            selectedProperties={selectedFilters.properties}
            selectedCategories={selectedFilters.categories}
            selectedMinPrice={selectedFilters["min-price"]}
            selectedMaxPrice={selectedFilters["max-price"]}
            selectedRating={selectedFilters.rating}
            selectedShippingFree={selectedFilters["shipping-free"]}
            rootCategoryId={rootCategoryId}
            translations={translations}
            onFilterChange={handleFilterChange}
            className="w-full"
          />
        ))}
        {showResetFiltersButton && (
          <div className="w-full">
            <button
              type="button"
              onClick={invokeCleanFilters}
              className="inline-flex justify-center items-center gap-2 rounded font-bold transition-colors focus:outline-hidden focus:ring-2 focus:ring-offset-2 px-4 py-3 text-base bg-brand-primary hover:bg-brand-primary-hover text-brand-on-primary focus:ring-brand-primary w-full"
            >
              <span>
                {t.listing.resetFilters}
                <CloseFilledIcon className="w-6 h-6 inline-block align-middle ml-2" />
              </span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
