// packages/cms-base-layer/app/components/SwProductUnits.vue
<script setup lang="ts">
import { useCmsTranslations } from "@shopware/composables";
import { defu } from "defu";
import { computed } from "vue";
import type { Schemas } from "#shopware";

const { product, showContent = true } = defineProps<{
  product: Schemas["Product"];
  showContent?: boolean;
}>();

type Translations = {
  product: {
    content: string;
  };
};

let translations: Translations = {
  product: {
    content: "Content",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const purchaseUnit = computed(() => product?.purchaseUnit);
const unitName = computed(() => product?.unit?.translated.name);
const referencePrice = computed(
  () => product?.calculatedPrice?.referencePrice?.price,
);
const referenceUnit = computed(
  () => product?.calculatedPrice?.referencePrice?.referenceUnit,
);
const referenceUnitName = computed(
  () => product?.calculatedPrice?.referencePrice?.unitName,
);
</script>

<template>
  <div v-if="purchaseUnit" class="flex text-gray-500 justify-end gap-1">
    <template v-if="showContent">
      {{ translations.product.content }}: {{ purchaseUnit }} {{ unitName }}
    </template>
    <template v-if="referencePrice">
      (<SwSharedPrice :value="referencePrice" /> / {{ referenceUnit }}
      {{ referenceUnitName }} )
    </template>
  </div>
</template>

// packages/cms-base-layer-react/src/components/shared/SwProductUnits.tsx
import type { CSSProperties } from "react";

import type { Schemas } from "#shopware";

import type { CmsClientContext } from "../../context";
import { cx } from "../../helpers/cx";
import { withTranslationDefaults } from "../../translations";
import { SwSharedPrice } from "./SwSharedPrice";

export type SwProductUnitsProps = {
  product: Schemas["Product"];
  ctx: Pick<CmsClientContext, "locale" | "currencyCode" | "translations">;
  showContent?: boolean;
  className?: string;
  style?: CSSProperties;
};

const translationDefaults = {
  product: {
    content: "Content",
  },
};

export function SwProductUnits({
  product,
  ctx,
  showContent = true,
  className,
  style,
}: SwProductUnitsProps) {
  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );
  const purchaseUnit = product.purchaseUnit;
  if (!purchaseUnit) return null;

  const unitName = product.unit?.translated.name;
  const referencePrice = product.calculatedPrice?.referencePrice;

  return (
    <div
      className={cx("flex text-gray-500 justify-end gap-1", className)}
      style={style}
    >
      {showContent ? (
        <>
          {translations.product.content}: {purchaseUnit} {unitName}
        </>
      ) : null}
      {referencePrice?.price ? (
        <>
          {"("}
          <SwSharedPrice value={referencePrice.price} ctx={ctx} />
          {" / "}
          {referencePrice.referenceUnit} {referencePrice.unitName}
          {" )"}
        </>
      ) : null}
    </div>
  );
}
