// packages/cms-base/components/SwSharedPrice.vue
<script setup lang="ts">
import { usePrice } from "#imports";
import { computed } from "vue";

const { getFormattedPrice } = usePrice();
const props = defineProps<{
  value: number | undefined;
}>();

const getPrice = computed<string>(() => getFormattedPrice(props.value));
</script>

<template>
  <p class="flex gap-1">
    <slot name="beforePrice" />
    <span>{{ getPrice }}</span>
    <slot name="afterPrice" />
  </p>
</template>

// packages/cms-base-layer-react/src/components/shared/SwSharedPrice.tsx
import type { ReactNode } from "react";

import { cx } from "../../helpers/cx";
import { formatPrice } from "../../helpers/formatPrice";
import type { PriceFormatOptions } from "../../helpers/formatPrice";

export type SwSharedPriceProps = {
  value: number | undefined;
  ctx: PriceFormatOptions;
  className?: string;
  beforePrice?: ReactNode;
  afterPrice?: ReactNode;
};

export function SwSharedPrice({
  value,
  ctx,
  className,
  beforePrice,
  afterPrice,
}: SwSharedPriceProps) {
  return (
    <p className={cx("flex gap-1", className)}>
      {beforePrice}
      <span>{formatPrice(value, ctx)}</span>
      {afterPrice}
    </p>
  );
}
