// packages/cms-base-layer-react/src/components/element/CmsElementVimeoVideo.tsx
import { getTranslatedProperty } from "@shopware/helpers";

import { cx } from "../../helpers/cx";
import { getConfigValue } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import { getCmsTranslate, withTranslationDefaults } from "../../translations";
import type { CmsElementVimeoVideo as CmsElementVimeoVideoContent } from "../../types";
import { CmsMedia } from "../ui/CmsMedia";
import { CmsVideoConsent } from "./CmsVideoConsent";
import { CmsVideoIframe } from "./CmsVideoIframe";
import { getVimeoVideoUrl } from "./videoEmbedUrl";

const translations = {
  cms: {
    video: {
      privacyNoticeText:
        "By viewing the video you agree that your data will be transferred to {platform} and that you have read the privacy policy.",
      acceptButtonLabel: "Accept",
    },
    vimeoVideo: {
      iframeTitle: "Vimeo video",
    },
  },
};

export function CmsElementVimeoVideo({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsElementVimeoVideoContent>) {
  const t = withTranslationDefaults(ctx.translations, translations);

  const videoUrl = getVimeoVideoUrl({
    videoID: getConfigValue(content, "videoID"),
    byLine: getConfigValue(content, "byLine"),
    color: getConfigValue(content, "color"),
    doNotTrack: getConfigValue(content, "doNotTrack"),
    loop: getConfigValue(content, "loop"),
    mute: getConfigValue(content, "mute"),
    title: getConfigValue(content, "title"),
    portrait: getConfigValue(content, "portrait"),
    controls: getConfigValue(content, "controls"),
    autoplay: getConfigValue(content, "autoplay"),
  });

  const iframeTitle =
    getConfigValue(content, "iframeTitle") || t.cms.vimeoVideo.iframeTitle;
  const needsConfirmation = !!getConfigValue(content, "needsConfirmation");
  const previewMedia = content.data?.media;

  return (
    <div className={cx("cms-element-vimeo-video", className)} style={style}>
      {needsConfirmation ? (
        <CmsVideoConsent
          cookieName="vimeo-video"
          videoUrl={videoUrl}
          iframeTitle={iframeTitle}
          privacyNoticeText={getCmsTranslate(t.cms.video.privacyNoticeText, {
            platform: "Vimeo",
          })}
          acceptButtonLabel={t.cms.video.acceptButtonLabel}
        >
          {previewMedia ? (
            <CmsMedia
              media={previewMedia}
              alt={getTranslatedProperty(previewMedia, "alt")}
              sizes={ctx.imageSizes}
              className="absolute inset-0 w-full h-full object-cover"
            />
          ) : null}
        </CmsVideoConsent>
      ) : (
        <CmsVideoIframe src={videoUrl} title={iframeTitle} />
      )}
    </div>
  );
}

// packages/cms-base/components/public/cms/element/CmsElementVimeoVideo.vue
<script setup lang="ts">
import type { CmsElementVimeoVideo } from "@shopware-pwa/composables-next";
import { ref } from "vue";
import type { Ref } from "vue";
import { useCmsElementConfig } from "#imports";

const props = defineProps<{
  content: CmsElementVimeoVideo;
}>();
const { getConfigValue } = useCmsElementConfig(props.content);
// TODO CMS add proper mapping or config type. This Component needs rework.
type CmsElementVimeoVideoConfigKey = keyof CmsElementVimeoVideo["config"];

const vimeoConfigMapping = {
  byLine: "byline",
  color: "color",
  doNotTrack: "dnt",
  loop: "loop",
  mute: "mute",
  title: "title",
  portrait: "portrait",
  controls: "controls",
  videoID: "videoID",
  autoplay: "autoplay",
  previewMedia: "previewMedia",
  needsConfirmation: "needsConfirmation",
};

const videoUrl: Ref = ref(
  `https://player.vimeo.com/video/${getConfigValue("videoID")}?`,
);

const convertAttr = (
  value: string,
  configKey: CmsElementVimeoVideoConfigKey,
) => {
  if (configKey === "color")
    return value
      ? `${vimeoConfigMapping[configKey]}=${value}&`.replace("#", "")
      : "";

  return value ? `${vimeoConfigMapping[configKey]}=${value}&` : "";
};

for (const key in props.content.config) {
  if (Object.prototype.hasOwnProperty.call(vimeoConfigMapping, key)) {
    videoUrl.value += convertAttr(
      props.content.config[key as CmsElementVimeoVideoConfigKey]
        .value as string,
      key as CmsElementVimeoVideoConfigKey,
    );
  }
}
</script>
<template>
  <div class="cms-element-vimeo-video">
    <iframe
      class="w-full inset-0 aspect-video"
      :src="videoUrl.replace(/ /g, '')"
    >
    </iframe>
  </div>
</template>
