// packages/cms-base/components/cms/block/CmsBlockDefault.vue
<template>
  <div>
    <CmsGenericElement
      v-for="slot in getSlots"
      :key="slot.id"
      :content="slot"
      class="cms-block-default"
    />
  </div>
</template>

<script>
// import CmsGenericElement from "sw-cms/CmsGenericElement";

export default {
  name: "CmsBlockDefault",

  components: {
    // CmsGenericElement,
  },

  props: {
    content: {
      type: Object,
      default: () => ({}),
    },
  },

  computed: {
    getSlots() {
      return this.content.slots || [];
    },
  },
};
// <style lang="scss" scoped>
// @import "@/cms/settings.scss";

// .cms-block-default {
//   @include sizing-mode-boxed;
// }
// </style>
</script>

// packages/cms-base-layer-react/src/components/block/CmsBlockDefault.tsx
import type { Schemas } from "#shopware";

import { cx } from "../../helpers/cx";
import type { CmsComponentProps } from "../../registry";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockDefault({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<Schemas["CmsBlock"]>) {
  return (
    <div className={cx("cms-block-default", className)} style={style}>
      {content.slots.map((slot) => (
        <CmsGenericElement key={slot.id} content={slot} ctx={ctx} />
      ))}
    </div>
  );
}
