// packages/cms-base-layer/app/components/public/cms/block/CmsBlockImageTextCover.vue
<script setup lang="ts">
import type { CmsBlockImageTextCover } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageTextCover;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
</script>
<template>
  <article class="flex flex-col md:flex-row justify-start items-start gap-6 w-full">
    <div class="w-full md:flex-1">
      <CmsGenericElement :content="leftContent" />
    </div>
    <div class="w-full md:flex-1">
      <CmsGenericElement :content="rightContent" />
    </div>
  </article>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageTextCover.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageTextCover as CmsBlockImageTextCoverContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageTextCover({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageTextCoverContent>) {
  const leftContent = getSlotContent(content, "left");
  const rightContent = getSlotContent(content, "right");

  return (
    <article
      className={cx(
        "flex flex-col md:flex-row justify-start items-start gap-6 w-full pb-6",
        className,
      )}
      style={style}
    >
      <div className="w-full md:flex-1 px-6 pt-6 md:px-0 md:pt-6 md:pl-6">
        <CmsGenericElement content={leftContent} ctx={ctx} />
      </div>
      <div className="w-full md:flex-1 px-6 pt-0 md:pt-6 pb-6 md:px-0 md:pr-6">
        <CmsGenericElement content={rightContent} ctx={ctx} />
      </div>
    </article>
  );
}
