// packages/cms-base-layer/app/components/public/cms/block/CmsBlockImageGallery.vue
<script setup lang="ts">
import type { CmsBlockImageGallery } from "@shopware/composables";

import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageGallery;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const cmsContent = getSlotContent("imageGallery");
</script>

<template>
  <div class="cms-block-image-gallery">
    <CmsGenericElement :content="cmsContent" />
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageGallery.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageGallery as CmsBlockImageGalleryContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageGallery({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageGalleryContent>) {
  const cmsContent = getSlotContent(content, "imageGallery");

  return (
    <div className={cx("cms-block-image-gallery", className)} style={style}>
      <CmsGenericElement content={cmsContent} ctx={ctx} />
    </div>
  );
}
