// packages/cms-base-layer/app/components/public/cms/block/CmsBlockImageTwoColumn.vue
<script setup lang="ts">
import type { CmsBlockImageTwoColumn } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageTwoColumn;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
</script>
<template>
  <div
    class="cms-block-image-two-column flex flex-col md:flex-row justify-start items-start gap-6 w-full"
  >
    <div class="w-full md:flex-1 md:min-w-0">
      <CmsGenericElement :content="leftContent" />
    </div>
    <div class="w-full md:flex-1 md:min-w-0">
      <CmsGenericElement :content="rightContent" />
    </div>
  </div>
</template>

<style scoped>
.cms-block-image-two-column :deep(.cms-element-image) {
  @apply relative h-full w-full;
}

.cms-block-image-two-column :deep(.cms-element-image img) {
  @apply w-full h-full object-cover;
}

.cms-block-image-two-column :deep(.cms-element-image-slider) {
  @apply w-full;
}
</style>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageTwoColumn.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageTwoColumn as CmsBlockImageTwoColumnContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageTwoColumn({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageTwoColumnContent>) {
  const leftContent = getSlotContent(content, "left");
  const rightContent = getSlotContent(content, "right");

  return (
    <div
      className={cx(
        "cms-block-image-two-column flex flex-col md:flex-row justify-start items-start gap-6 w-full",
        "[&_.cms-element-image]:relative [&_.cms-element-image]:h-full [&_.cms-element-image]:w-full",
        "[&_.cms-element-image_img]:h-full [&_.cms-element-image_img]:w-full [&_.cms-element-image_img]:object-cover",
        "[&_.cms-element-image-slider]:w-full",
        className,
      )}
      style={style}
    >
      <div className="w-full md:flex-1 md:min-w-0">
        <CmsGenericElement content={leftContent} ctx={ctx} />
      </div>
      <div className="w-full md:flex-1 md:min-w-0">
        <CmsGenericElement content={rightContent} ctx={ctx} />
      </div>
    </div>
  );
}
