// packages/cms-base-layer/app/components/public/cms/block/CmsBlockImageGalleryBig.vue
<script setup lang="ts">
import type { CmsBlockImageGalleryBig } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageGalleryBig;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const cmsContent = getSlotContent("imageGallery");
</script>

<template>
  <div class="cms-block-image-gallery-big">
    <CmsGenericElement :content="cmsContent" />
  </div>
</template>

<style scoped>
.cms-block-image-gallery-big {
  @apply w-full;
}

.cms-block-image-gallery-big :deep(.cms-element-image-gallery) {
  @apply max-w-screen-xl mx-auto;
}

/* Enhanced styling for the big gallery version */
.cms-block-image-gallery-big :deep(.gallery-slider) {
  @apply max-h-[800px];
}

.cms-block-image-gallery-big :deep(img) {
  @apply object-contain mx-auto;
}

/* Larger navigation controls */
.cms-block-image-gallery-big :deep(.gallery-slider-controls) {
  @apply scale-125;
}
</style>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageGalleryBig.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageGalleryBig as CmsBlockImageGalleryBigContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageGalleryBig({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageGalleryBigContent>) {
  const cmsContent = getSlotContent(content, "imageGallery");

  return (
    <div
      className={cx(
        "cms-block-image-gallery-big w-full",
        "[&_.cms-element-image-gallery]:max-w-[1280px] [&_.cms-element-image-gallery]:mx-auto",
        "[&_.gallery-slider]:max-h-[800px]",
        "[&_img]:mx-auto [&_img]:object-contain",
        "[&_.gallery-slider-controls]:scale-125",
        className,
      )}
      style={style}
    >
      <CmsGenericElement content={cmsContent} ctx={ctx} />
    </div>
  );
}
