// packages/cms-base/components/public/cms/block/CmsBlockProductHeading.vue
<script setup lang="ts">
import type { CmsBlockProductHeading } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockProductHeading;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
</script>

<template>
  <div class="cms-block-product-heading flex justify-between">
    <CmsGenericElement :content="leftContent" />
    <CmsGenericElement :content="rightContent" />
  </div>
</template>

<style scoped>
.cms-block-product-heading .cms-element-image {
  @apply max-w-[7.5rem] max-h-[7.5rem];
}
</style>

// packages/cms-base-layer-react/src/components/block/CmsBlockProductHeading.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockProductHeading as CmsBlockProductHeadingContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockProductHeading({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockProductHeadingContent>) {
  const leftContent = getSlotContent(content, "left");
  const rightContent = getSlotContent(content, "right");

  return (
    <div
      className={cx(
        "cms-block-product-heading flex justify-between pt-4",
        "[&_.cms-element-image]:max-h-[7.5rem] [&_.cms-element-image]:max-w-[7.5rem]",
        className,
      )}
      style={style}
    >
      <CmsGenericElement content={leftContent} ctx={ctx} />
      <CmsGenericElement content={rightContent} ctx={ctx} />
    </div>
  );
}
