// packages/cms-base/components/public/cms/block/CmsBlockImageTextGallery.vue
<script setup lang="ts">
import type {
  CmsBlockImageTextGallery,
  CmsElementImage,
  CmsElementText,
} from "@shopware-pwa/composables-next";
import { useCmsBlock } from "#imports";
import type { Schemas } from "#shopware";

const props = defineProps<{
  content: CmsBlockImageTextGallery;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftTextContent = getSlotContent("left-text") as CmsElementText;
const rightTextContent = getSlotContent("right-text") as CmsElementText;
const centerTextContent = getSlotContent("center-text") as CmsElementText;

const leftImageContent = getSlotContent("left-image") as CmsElementImage;
const rightImageContent = getSlotContent("right-image") as CmsElementImage;
const centerImageContent = getSlotContent("center-image") as CmsElementImage;

// TODO: useRouter
function onImageClick(
  slotContent: Schemas["CmsSlot"] & {
    data: {
      url?: string;
      newTab?: boolean;
    };
  },
) {
  if (slotContent.data?.url) {
    if (slotContent.data?.newTab) {
      window.open(slotContent.data.url);
    } else {
      window.location.href = slotContent.data.url;
    }
  }
}
</script>
<template>
  <article
    class="cms-block-image-text-gallery"
    :style="{ backgroundColor: content.backgroundColor || '' }"
  >
    <div class="cms-block-image-text-gallery__container">
      <div class="cms-block-image-text-gallery__container__column">
        <CmsElementImage
          :content="leftImageContent"
          :style="{ cursor: leftImageContent.data?.url && 'pointer' }"
          @click="onImageClick(leftImageContent)"
        />
        <CmsElementText
          :content="leftTextContent"
          class="cms-block-imag)e-text-gallery__container__column--text"
        />
      </div>
      <div class="cms-block-image-text-gallery__container__column">
        <CmsElementImage
          :content="centerImageContent"
          :style="{
            cursor: centerImageContent.data?.url && 'pointer',
          }"
          @click="onImageClick(centerImageContent)"
        />
        <CmsElementText
          :content="centerTextContent"
          class="cms-block-image-text-gallery__container__column--text"
        />
      </div>
      <div class="cms-block-image-text-gallery__container__column">
        <CmsElementImage
          :content="rightImageContent"
          :style="{ cursor: rightImageContent.data?.url && 'pointer' }"
          @click="onImageClick(rightImageContent)"
        />
        <CmsElementText
          :content="rightTextContent"
          class="cms-block-image-text-gallery__container__column--text"
        />
      </div>
    </div>
  </article>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageTextGallery.tsx
import type { CSSProperties } from "react";

import type { Schemas } from "#shopware";

import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageTextGallery as CmsBlockImageTextGalleryContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

function getImageCursorStyle(
  slotContent: Schemas["CmsSlot"] | undefined,
): CSSProperties | undefined {
  const data = slotContent?.data;
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    return undefined;
  }
  return typeof data.url === "string" && data.url
    ? { cursor: "pointer" }
    : undefined;
}

export function CmsBlockImageTextGallery({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageTextGalleryContent>) {
  const leftTextContent = getSlotContent(content, "left-text");
  const rightTextContent = getSlotContent(content, "right-text");
  const centerTextContent = getSlotContent(content, "center-text");

  const leftImageContent = getSlotContent(content, "left-image");
  const rightImageContent = getSlotContent(content, "right-image");
  const centerImageContent = getSlotContent(content, "center-image");

  const blockStyle: CSSProperties = content.backgroundColor
    ? { backgroundColor: content.backgroundColor, ...style }
    : { ...style };

  return (
    <article
      className={cx(
        "cms-block-image-text-gallery flex flex-col sm:flex-row justify-start items-start gap-6 w-full",
        className,
      )}
      style={blockStyle}
    >
      <div className="w-full sm:flex-1">
        <CmsGenericElement
          content={leftImageContent}
          ctx={ctx}
          style={getImageCursorStyle(leftImageContent)}
        />
        <CmsGenericElement
          content={leftTextContent}
          ctx={ctx}
          className="self-stretch"
        />
      </div>
      <div className="w-full sm:flex-1">
        <CmsGenericElement
          content={centerImageContent}
          ctx={ctx}
          style={getImageCursorStyle(centerImageContent)}
        />
        <CmsGenericElement
          content={centerTextContent}
          ctx={ctx}
          className="self-stretch"
        />
      </div>
      <div className="w-full sm:flex-1">
        <CmsGenericElement
          content={rightImageContent}
          ctx={ctx}
          style={getImageCursorStyle(rightImageContent)}
        />
        <CmsGenericElement
          content={rightTextContent}
          ctx={ctx}
          className="self-stretch"
        />
      </div>
    </article>
  );
}
