// packages/cms-base/components/cms/block/CmsBlockImageSimpleGrid.vue
<script setup lang="ts">
import { CmsBlockImageSimpleGrid } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockImageSimpleGrid;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftTopContent = getSlotContent("left-top");
const leftBottomContent = getSlotContent("left-bottom");
const rightContent = getSlotContent("right");
</script>

<template>
  <div class="grid md:grid-cols-2 gap-10">
    <div class="grid gap-10">
      <CmsGenericElement :content="leftTopContent" />
      <CmsGenericElement :content="leftBottomContent" />
    </div>
    <CmsGenericElement :content="rightContent" />
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageSimpleGrid.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageSimpleGrid as CmsBlockImageSimpleGridContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageSimpleGrid({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageSimpleGridContent>) {
  const leftTopContent = getSlotContent(content, "left-top");
  const leftBottomContent = getSlotContent(content, "left-bottom");
  const rightContent = getSlotContent(content, "right");

  return (
    <div
      className={cx(
        "flex flex-col md:flex-row justify-start items-start gap-6 w-full",
        className,
      )}
      style={style}
    >
      <div className="w-full md:flex-1 flex flex-col justify-start items-start gap-6">
        <div className="w-full">
          <CmsGenericElement content={leftTopContent} ctx={ctx} />
        </div>
        <div className="w-full">
          <CmsGenericElement content={leftBottomContent} ctx={ctx} />
        </div>
      </div>
      <div className="w-full md:flex-1">
        <CmsGenericElement content={rightContent} ctx={ctx} />
      </div>
    </div>
  );
}
