// packages/cms-base/components/public/cms/block/CmsBlockTextHero.vue
<script setup lang="ts">
import type { CmsBlockTextHero } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockTextHero;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const slotContent = getSlotContent("content");
</script>
<template>
  <CmsGenericElement :content="slotContent" />
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockTextHero.tsx
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockTextHero as CmsBlockTextHeroContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockTextHero({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockTextHeroContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <CmsGenericElement
      content={slotContent}
      ctx={ctx}
      className={className}
      style={style}
    />
  );
}
