// packages/cms-base-layer/app/components/public/cms/block/CmsBlockImageBubbleRow.vue
<script setup lang="ts">
import type { CmsBlockImageBubbleRow } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageBubbleRow;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
const centerContent = getSlotContent("center");
</script>
<template>
  <div
    class="cms-block-image-bubble-row flex flex-col sm:flex-row justify-start items-start gap-6 w-full"
  >
    <div class="w-full sm:flex-1 flex items-center justify-center">
      <CmsGenericElement :content="leftContent" class="w-full" />
    </div>
    <div class="w-full sm:flex-1 flex items-center justify-center">
      <CmsGenericElement :content="centerContent" class="w-full" />
    </div>
    <div class="w-full sm:flex-1 flex items-center justify-center">
      <CmsGenericElement :content="rightContent" class="w-full" />
    </div>
  </div>
</template>
<style scoped>
.cms-block-image-bubble-row :deep(.cms-element-image) {
  @apply object-cover max-w-xs overflow-hidden rounded-full aspect-square;
}
</style>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageBubbleRow.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageBubbleRow as CmsBlockImageBubbleRowContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageBubbleRow({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageBubbleRowContent>) {
  const leftContent = getSlotContent(content, "left");
  const centerContent = getSlotContent(content, "center");
  const rightContent = getSlotContent(content, "right");

  return (
    <div
      className={cx(
        "cms-block-image-bubble-row flex flex-col sm:flex-row justify-start items-start gap-6 w-full",
        "[&_.cms-element-image]:aspect-square [&_.cms-element-image]:max-w-[20rem] [&_.cms-element-image]:overflow-hidden [&_.cms-element-image]:rounded-full [&_.cms-element-image]:object-cover",
        className,
      )}
      style={style}
    >
      <div className="w-full sm:flex-1 flex items-center justify-center">
        <CmsGenericElement content={leftContent} ctx={ctx} className="w-full" />
      </div>
      <div className="w-full sm:flex-1 flex items-center justify-center">
        <CmsGenericElement
          content={centerContent}
          ctx={ctx}
          className="w-full"
        />
      </div>
      <div className="w-full sm:flex-1 flex items-center justify-center">
        <CmsGenericElement
          content={rightContent}
          ctx={ctx}
          className="w-full"
        />
      </div>
    </div>
  );
}
