// packages/cms-base-layer/app/components/public/cms/block/CmsBlockProductSlider.vue
<script setup lang="ts">
import type { CmsBlockProductSlider } from "@shopware/composables";

defineProps<{
  content: CmsBlockProductSlider;
}>();
</script>
<template>
  <div class="cms-block-product-slider">
    <CmsGenericElement
      v-for="slot in content.slots"
      :key="slot.id"
      :content="slot"
    />
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockProductSlider.tsx
import { cx } from "../../helpers/cx";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockProductSlider as CmsBlockProductSliderContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockProductSlider({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockProductSliderContent>) {
  return (
    <div className={cx("cms-block-product-slider", className)} style={style}>
      {content.slots.map((slot) => (
        <CmsGenericElement key={slot.id} content={slot} ctx={ctx} />
      ))}
    </div>
  );
}
