// templates/vue-demo-store/components/cms/block/CmsBlockGalleryBuybox.vue
<script setup lang="ts">
import { CmsBlockGalleryBuybox } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockGalleryBuybox;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const rightContent = getSlotContent("right");
const leftContent = getSlotContent("left");
</script>

<template>
  <div
    class="flex flex-col gap-6 md:gap-0 md:flex-row justify-center"
  >
    <div class="-mx-4 md:mx-0 md:w-1/2">
      <CmsGenericElement :content="leftContent" />
    </div>
    <div class="w-full md:w-1/2 md:pl-4">
      <CmsGenericElement :content="rightContent" />
    </div>
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockGalleryBuybox.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockGalleryBuybox as CmsBlockGalleryBuyboxContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockGalleryBuybox({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockGalleryBuyboxContent>) {
  const rightContent = getSlotContent(content, "right");
  const leftContent = getSlotContent(content, "left");

  return (
    <div
      className={cx(
        "w-full flex flex-col lg:flex-row justify-center items-stretch gap-4 lg:gap-10 lg:px-0 overflow-hidden",
        className,
      )}
      style={style}
    >
      <div className="w-full lg:w-3/5">
        <CmsGenericElement content={leftContent} ctx={ctx} />
      </div>
      <div className="w-full lg:w-2/5">
        <CmsGenericElement content={rightContent} ctx={ctx} />
      </div>
    </div>
  );
}
