// packages/cms-base-layer/components/public/cms/block/CmsBlockImageTextRow.vue
<script setup lang="ts">
import type { CmsBlockImageTextRow } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockImageTextRow;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftImageContent = getSlotContent("left-image");
const leftTextContent = getSlotContent("left-text");
const centerImageContent = getSlotContent("center-image");
const centerTextContent = getSlotContent("center-text");
const rightImageContent = getSlotContent("right-image");
const rightTextContent = getSlotContent("right-text");
</script>
<template>
  <div class="cms-block-image-text-row grid md:grid-cols-3 gap-10">
    <div class="cms-block-image-text-row__column">
      <CmsGenericElement :content="leftImageContent" />
      <CmsGenericElement :content="leftTextContent" />
    </div>
    <div class="cms-block-image-text-row__column">
      <CmsGenericElement :content="centerImageContent" />
      <CmsGenericElement :content="centerTextContent" />
    </div>
    <div class="cms-block-image-text-row__column">
      <CmsGenericElement :content="rightImageContent" />
      <CmsGenericElement :content="rightTextContent" />
    </div>
  </div>
</template>

<style scoped>
.cms-block-image-text-row .cms-element-image {
  @apply object-cover;
}

.cms-block-image-text-row .cms-block-image-text-row__column div:first-child {
  @apply mb-5;
}
</style>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageTextRow.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageTextRow as CmsBlockImageTextRowContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageTextRow({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageTextRowContent>) {
  const leftImageContent = getSlotContent(content, "left-image");
  const leftTextContent = getSlotContent(content, "left-text");
  const centerImageContent = getSlotContent(content, "center-image");
  const centerTextContent = getSlotContent(content, "center-text");
  const rightImageContent = getSlotContent(content, "right-image");
  const rightTextContent = getSlotContent(content, "right-text");

  return (
    <div
      className={cx(
        "cms-block-image-text-row flex flex-col md:flex-row justify-center items-stretch gap-6 w-full",
        "[&_.cms-element-image]:relative [&_.cms-element-image]:h-full [&_.cms-element-image]:w-full",
        "[&_.cms-element-image_img]:h-full [&_.cms-element-image_img]:w-full [&_.cms-element-image_img]:rounded-lg [&_.cms-element-image_img]:object-cover",
        "[&_.cms-element-text]:self-stretch [&_.cms-element-text]:min-h-12",
        className,
      )}
      style={style}
    >
      <div className="w-full md:flex-1 flex flex-col">
        <div className="flex-1 mb-4 overflow-hidden rounded-lg min-h-64">
          <CmsGenericElement content={leftImageContent} ctx={ctx} />
        </div>
        <CmsGenericElement
          content={leftTextContent}
          ctx={ctx}
          className="text-center"
        />
      </div>
      <div className="w-full md:flex-1 flex flex-col">
        <div className="flex-1 mb-4 overflow-hidden rounded-lg min-h-64">
          <CmsGenericElement content={centerImageContent} ctx={ctx} />
        </div>
        <CmsGenericElement
          content={centerTextContent}
          ctx={ctx}
          className="text-center"
        />
      </div>
      <div className="w-full md:flex-1 flex flex-col">
        <div className="flex-1 mb-4 overflow-hidden rounded-lg min-h-64">
          <CmsGenericElement content={rightImageContent} ctx={ctx} />
        </div>
        <CmsGenericElement
          content={rightTextContent}
          ctx={ctx}
          className="text-center"
        />
      </div>
    </div>
  );
}
