// packages/cms-base/components/cms/block/CmsBlockTextThreeColumn.vue
<script setup lang="ts">
import { CmsBlockTextThreeColumn } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockTextThreeColumn;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
const centerContent = getSlotContent("center");
</script>

<template>
  <article class="grid md:grid-cols-3 gap-4">
    <CmsGenericElement :content="leftContent" class="" />
    <CmsGenericElement :content="centerContent" class="" />
    <CmsGenericElement :content="rightContent" class="" />
  </article>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockTextThreeColumn.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockTextThreeColumn as CmsBlockTextThreeColumnContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockTextThreeColumn({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockTextThreeColumnContent>) {
  const leftContent = getSlotContent(content, "left");
  const centerContent = getSlotContent(content, "center");
  const rightContent = getSlotContent(content, "right");

  return (
    <article
      className={cx("grid md:grid-cols-3 gap-4", className)}
      style={style}
    >
      <CmsGenericElement content={leftContent} ctx={ctx} />
      <CmsGenericElement content={centerContent} ctx={ctx} />
      <CmsGenericElement content={rightContent} ctx={ctx} />
    </article>
  );
}
