// packages/cms-base/components/public/cms/block/CmsBlockImageCover.vue
<script setup lang="ts">
import { CmsBlockImageCover } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockImageCover;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const cmsContent = getSlotContent("image");
</script>
<template>
  <div class="cms-block-image-cover">
    <CmsGenericElement v-if="cmsContent" :content="cmsContent" />
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockImageCover.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageCover as CmsBlockImageCoverContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageCover({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageCoverContent>) {
  const cmsContent = getSlotContent(content, "image");

  return (
    <div className={cx("cms-block-image-cover", className)} style={style}>
      {cmsContent && <CmsGenericElement content={cmsContent} ctx={ctx} />}
    </div>
  );
}
