// packages/cms-base-layer/app/components/public/cms/block/CmsBlockForm.vue
<script setup lang="ts">
import type { CmsBlockForm } from "@shopware/composables";

import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockForm;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const cmsContent = getSlotContent("content");
</script>
<template>
  <div class="cms-block-form">
    <CmsGenericElement v-if="cmsContent" :content="cmsContent" />
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockForm.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockForm as CmsBlockFormContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockForm({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockFormContent>) {
  const cmsContent = getSlotContent(content, "content");

  return (
    <div className={cx("cms-block-form", className)} style={style}>
      {cmsContent && <CmsGenericElement content={cmsContent} ctx={ctx} />}
    </div>
  );
}
