// packages/cms-base/components/public/cms/block/CmsBlockYoutubeVideo.vue
<script setup lang="ts">
import type { CmsBlockYoutubeVideo } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockYoutubeVideo;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const slotContent = getSlotContent("video");
</script>
<template>
  <div class="cms-block-youtube-video relative">
    <CmsGenericElement :content="slotContent" />
  </div>
</template>

// packages/cms-base-layer-react/src/components/block/CmsBlockYoutubeVideo.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockYoutubeVideo as CmsBlockYoutubeVideoContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockYoutubeVideo({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockYoutubeVideoContent>) {
  const slotContent = getSlotContent(content, "video");

  return (
    <div
      className={cx("cms-block-youtube-video relative", className)}
      style={style}
    >
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}
