// packages/cms-base/components/public/cms/block/CmsBlockCenterText.vue
<script setup lang="ts">
import type { CmsBlockCenterText } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockCenterText;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const slotLeftContent = getSlotContent("left");
const slotRightContent = getSlotContent("right");
const slotCenterContent = getSlotContent("center");
</script>
<template>
  <div class="cms-block-center-text grid md:grid-cols-3 gap-10 content-center">
    <CmsGenericElement :content="slotLeftContent" />
    <CmsGenericElement :content="slotCenterContent" />
    <CmsGenericElement :content="slotRightContent" />
  </div>
</template>

<style scoped>
.cms-block-center-text .cms-element-image {
  @apply aspect-square object-cover;
}
</style>

// packages/cms-base-layer-react/src/components/block/CmsBlockCenterText.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockCenterText as CmsBlockCenterTextContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockCenterText({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockCenterTextContent>) {
  const slotLeftContent = getSlotContent(content, "left");
  const slotRightContent = getSlotContent(content, "right");
  const slotCenterContent = getSlotContent(content, "center");

  return (
    <div
      className={cx(
        "cms-block-center-text grid md:grid-cols-3 gap-10 content-center",
        "[&_.cms-element-image]:self-stretch [&_.cms-element-image]:min-h-12",
        className,
      )}
      style={style}
    >
      <CmsGenericElement content={slotLeftContent} ctx={ctx} />
      <CmsGenericElement content={slotCenterContent} ctx={ctx} />
      <CmsGenericElement content={slotRightContent} ctx={ctx} />
    </div>
  );
}
