// templates/vue-starter-template-extended/base-template/app/components/account/order/detail/ChangePaymentModal.vue
<script setup lang="ts">
import type { Schemas } from "#shopware";

defineOptions({
  name: "AccountOrderDetailChangePaymentModal",
});

const props = defineProps<{
  isOpen: boolean;
  paymentMethods: Schemas["PaymentMethod"][];
  loading: boolean;
  currentPaymentMethodId: string;
}>();

const emit = defineEmits<{
  close: [];
  confirm: [paymentMethodId: string];
}>();

const selectedMethodId = ref(props.currentPaymentMethodId);

watch(
  () => props.currentPaymentMethodId,
  (val) => {
    selectedMethodId.value = val;
  },
);
</script>

<template>
  <div
    v-if="isOpen"
    class="fixed inset-0 bg-overlay-dark overflow-y-auto h-full w-full flex items-center justify-center"
  >
    <div
      class="bg-surface-surface p-8 rounded-lg shadow-xl max-w-md w-full"
    >
      <h2 class="text-2xl font-bold mb-4 text-surface-on-surface">
        {{ $t("account.orderDetails.changePaymentMethod") }}
      </h2>
      <div class="space-y-4">
        <template v-if="loading">
          <div
            v-for="i in 3"
            :key="i"
            class="flex items-center animate-pulse"
          >
            <div
              class="w-4 h-4 bg-surface-surface-container rounded-full mr-3"
            ></div>
            <div class="flex-grow">
              <div
                class="h-5 bg-surface-surface-container rounded w-1/3 mb-2"
              ></div>
              <div
                class="h-4 bg-surface-surface-container rounded w-2/3"
              ></div>
            </div>
          </div>
        </template>
        <template v-else>
          <div
            v-for="method in paymentMethods"
            :key="method.id"
            class="flex items-center"
          >
            <input
              :id="method.id"
              v-model="selectedMethodId"
              type="radio"
              :value="method.id"
              class="mr-3"
            />
            <label :for="method.id" class="flex-grow">
              <span class="font-medium text-surface-on-surface">{{
                method.name
              }}</span>

              <span
                v-if="method.description"
                class="block text-sm text-surface-on-surface-variant"
              >
                {{ method.description }}</span
              >
            </label>
          </div>
        </template>
      </div>
      <div class="mt-6 flex justify-end space-x-3">
        <button
          class="px-4 py-2 bg-brand-tertiary text-brand-on-tertiary rounded hover:bg-brand-tertiary-hover focus:outline-none focus:ring-2 focus:ring-brand-primary focus:ring-offset-2"
          :disabled="!selectedMethodId"
          @click="emit('close')"
        >
          {{ $t("account.orderDetails.close") }}
        </button>
        <button
          class="px-4 py-2 bg-brand-primary text-brand-on-primary rounded hover:bg-brand-primary-hover focus:outline-none focus:ring-2 focus:ring-brand-primary focus:ring-offset-2"
          :disabled="!selectedMethodId"
          @click="emit('confirm', selectedMethodId)"
        >
          {{ $t("account.orderDetails.confirm") }}
        </button>
      </div>
    </div>
  </div>
</template>

// templates/react-starter-template/features/account/orders/components/ChangePaymentModal.tsx
"use client";

import { BaseButton } from "@shopware/cms-base-layer-react/client";
import { getTranslatedProperty } from "@shopware/helpers";
import { useId, useState } from "react";

import type { Schemas } from "#shopware";
import { useTranslations } from "@/i18n/I18nProvider";

import { Modal } from "./Modal";

const SKELETON_ROWS = [0, 1, 2];

export type PaymentMethodsLoad =
  | { status: "loading" }
  | { status: "error" }
  | { status: "ready"; methods: Schemas["PaymentMethod"][] };

export type ChangePaymentModalProps = {
  open: boolean;
  methods: PaymentMethodsLoad;
  currentPaymentMethodId: string | null;
  busy: boolean;
  onClose: () => void;
  onConfirm: (paymentMethodId: string) => void;
};

export function ChangePaymentModal({
  open,
  ...props
}: ChangePaymentModalProps) {
  const t = useTranslations();
  return (
    <Modal
      open={open}
      title={t("account.orderDetails.changePaymentMethod")}
      closeLabel={t("account.orderDetails.close")}
      onClose={() => {
        if (!props.busy) props.onClose();
      }}
      data-testid="change-payment-modal"
    >
      <ChangePaymentForm {...props} />
    </Modal>
  );
}

function ChangePaymentForm({
  methods,
  currentPaymentMethodId,
  busy,
  onClose,
  onConfirm,
}: Omit<ChangePaymentModalProps, "open">) {
  const t = useTranslations();
  const legendId = useId();
  const [selectedId, setSelectedId] = useState<string | null>(
    currentPaymentMethodId,
  );
  const confirmableId =
    methods.status === "ready" &&
    methods.methods.some((method) => method.id === selectedId)
      ? selectedId
      : null;

  return (
    <form
      onSubmit={(event) => {
        event.preventDefault();
        if (confirmableId && !busy) onConfirm(confirmableId);
      }}
    >
      <fieldset className="space-y-4">
        <legend id={legendId} className="sr-only">
          {t("account.orderDetails.changePaymentMethod")}
        </legend>
        {methods.status === "loading" ? (
          <div aria-busy="true">
            <output className="sr-only">{t("form.loading")}</output>
            {SKELETON_ROWS.map((row) => (
              <div
                key={row}
                className="mb-4 flex animate-pulse items-center"
                aria-hidden="true"
              >
                <div className="mr-3 size-4 rounded-full bg-surface-surface-container" />
                <div className="grow">
                  <div className="mb-2 h-5 w-1/3 rounded bg-surface-surface-container" />
                  <div className="h-4 w-2/3 rounded bg-surface-surface-container" />
                </div>
              </div>
            ))}
          </div>
        ) : null}
        {methods.status === "error" ? (
          <p role="alert" className="text-sm text-states-error">
            {t("messages.error")}
          </p>
        ) : null}
        {methods.status === "ready"
          ? methods.methods.map((method) => {
              const inputId = `${legendId}-${method.id}`;
              const description = getTranslatedProperty(method, "description");
              return (
                <div key={method.id} className="flex items-center">
                  <input
                    id={inputId}
                    type="radio"
                    name="order-payment-method"
                    value={method.id}
                    className="mr-3 accent-brand-primary"
                    checked={selectedId === method.id}
                    aria-disabled={busy || undefined}
                    data-testid={`checkout-payment-method-${method.id}`}
                    aria-describedby={
                      description ? `${inputId}-description` : undefined
                    }
                    onChange={() => {
                      if (!busy) setSelectedId(method.id);
                    }}
                  />
                  <label htmlFor={inputId} className="grow">
                    <span className="font-medium text-surface-on-surface">
                      {getTranslatedProperty(method, "name") || method.name}
                    </span>
                    {description ? (
                      <span
                        id={`${inputId}-description`}
                        className="block text-sm text-surface-on-surface-variant"
                      >
                        {description}
                      </span>
                    ) : null}
                  </label>
                </div>
              );
            })
          : null}
      </fieldset>
      <div className="mt-6 flex justify-end gap-3">
        <BaseButton
          variant="secondary"
          size="small"
          disabled={busy}
          onClick={onClose}
        >
          {t("account.orderDetails.close")}
        </BaseButton>
        <BaseButton
          type="submit"
          size="small"
          disabled={!confirmableId}
          aria-busy={busy}
          aria-disabled={busy || undefined}
          className="aria-disabled:cursor-not-allowed aria-disabled:opacity-50"
          data-testid="change-payment-confirm-button"
        >
          {t("account.orderDetails.confirm")}
        </BaseButton>
      </div>
    </form>
  );
}
