// templates/vue-starter-template/app/components/shared/Pagination.vue
<script setup lang="ts">
const { total, current } = defineProps<{
  total: number;
  current: number;
}>();

defineEmits<{
  changePage: [page: number];
}>();

const VISIBLE_PAGES = 7;

const ELLIPSIS = "ellipsis" as const;

type PaginationCell = number | typeof ELLIPSIS;

const cells = computed<PaginationCell[]>(() => {
  const pages = Math.max(1, total);
  const size = Math.min(VISIBLE_PAGES, pages);

  const start = Math.min(
    Math.max(1, current - Math.floor(size / 2)),
    Math.max(1, pages - size + 1),
  );
  const end = start + size - 1;

  const visible: PaginationCell[] = Array.from(
    { length: size },
    (_, index) => start + index,
  );

  if (start > 1) {
    visible[0] = 1;
    visible[1] = ELLIPSIS;
  }

  if (end < pages) {
    visible[size - 1] = pages;
    visible[size - 2] = ELLIPSIS;
  }

  return visible;
});
</script>
<template>
  <nav
    class="relative z-0 inline-flex rounded-md shadow-sm space-x-px"
    :aria-label="$t('layout.ariaLabels.pagination')"
  >
    <button
      type="button"
      class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-outline-outline-variant bg-white text-sm outline outline-1 outline-offset-[-1px] outline-outline-outline-variant disabled:opacity-40 disabled:cursor-not-allowed"
      :disabled="current <= 1"
      :aria-label="$t('layout.ariaLabels.previousPage')"
      @click="$emit('changePage', current - 1)"
    >
      <SwChevronIcon direction="left" :size="20" />
    </button>

    <template v-for="(cell, index) in cells" :key="index">
      <span
        v-if="cell === ELLIPSIS"
        aria-hidden="true"
        class="relative inline-flex items-center justify-center min-w-[3rem] px-4 py-2 border border-outline-outline-variant bg-white text-sm outline outline-1 outline-offset-[-1px] outline-outline-outline-variant"
      >
        ...
      </span>
      <button
        v-else
        type="button"
        class="relative inline-flex items-center justify-center min-w-[3rem] px-4 py-2 border text-sm"
        :class="
          cell === current
            ? 'bg-brand-primary text-brand-on-primary'
            : 'bg-white border-outline-outline-variant outline outline-1 outline-offset-[-1px] outline-outline-outline-variant'
        "
        :aria-current="cell === current ? 'page' : undefined"
        :disabled="cell === current"
        @click="$emit('changePage', cell)"
      >
        {{ cell }}
      </button>
    </template>

    <button
      type="button"
      class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-outline-outline-variant bg-white text-sm outline outline-1 outline-offset-[-1px] outline-outline-outline-variant disabled:opacity-40 disabled:cursor-not-allowed"
      :disabled="current >= total"
      :aria-label="$t('layout.ariaLabels.nextPage')"
      @click="$emit('changePage', current + 1)"
    >
      <SwChevronIcon direction="right" :size="20" />
    </button>
  </nav>
</template>

// templates/react-starter-template/features/account/orders/components/Pagination.tsx
"use client";

import { cx } from "@shopware/cms-base-layer-react/client";

import { useTranslations } from "@/i18n/I18nProvider";

import { ELLIPSIS, paginationCells } from "../pagination";
import { ChevronLeftIcon, ChevronRightIcon } from "./OrderIcons";

const CELL_CLASS =
  "relative inline-flex min-w-12 items-center justify-center border px-4 py-2 text-sm";

const ARROW_CLASS =
  "relative inline-flex items-center border border-outline-outline-variant bg-surface-surface px-2 py-2 text-sm text-surface-on-surface disabled:cursor-not-allowed disabled:opacity-40";

export type PaginationProps = {
  total: number;
  current: number;
  onChangePage: (page: number) => void;
  className?: string;
};

export function Pagination({
  total,
  current,
  onChangePage,
  className,
}: PaginationProps) {
  const t = useTranslations();
  const change = (page: number) => {
    if (page === current || page < 1 || page > total) return;
    onChangePage(page);
  };

  return (
    <nav
      className={cx(
        "relative z-0 inline-flex space-x-px rounded-md",
        className,
      )}
      aria-label={t("layout.ariaLabels.pagination")}
    >
      <button
        type="button"
        className={cx(ARROW_CLASS, "rounded-l-md")}
        disabled={current <= 1}
        aria-label={t("layout.ariaLabels.previousPage")}
        onClick={() => change(current - 1)}
      >
        <ChevronLeftIcon className="size-5" />
      </button>
      {paginationCells(total, current).map((cell, index) =>
        cell === ELLIPSIS ? (
          <span
            key={`ellipsis-${index}`}
            aria-hidden="true"
            className={cx(
              CELL_CLASS,
              "border-outline-outline-variant bg-surface-surface text-surface-on-surface",
            )}
          >
            ...
          </span>
        ) : (
          <button
            key={cell}
            type="button"
            className={cx(
              CELL_CLASS,
              cell === current
                ? "cursor-default border-brand-primary bg-brand-primary text-brand-on-primary"
                : "border-outline-outline-variant bg-surface-surface text-surface-on-surface hover:bg-surface-surface-container-low",
            )}
            aria-current={cell === current ? "page" : undefined}
            aria-label={t("layout.ariaLabels.page", { page: cell })}
            onClick={() => change(cell)}
          >
            {cell}
          </button>
        ),
      )}
      <button
        type="button"
        className={cx(ARROW_CLASS, "rounded-r-md")}
        disabled={current >= total}
        aria-label={t("layout.ariaLabels.nextPage")}
        onClick={() => change(current + 1)}
      >
        <ChevronRightIcon className="size-5" />
      </button>
    </nav>
  );
}
