// templates/react-starter-template/features/cart/components/MiniCart.tsx
"use client";

import { IconButton, cx } from "@shopware/cms-base-layer-react/client";
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useId, useRef } from "react";
import type { RefObject } from "react";

import { CloseIcon } from "@/components/icons";
import { LocaleLink } from "@/components/LocaleLink";
import { Price } from "@/components/Price";
import { CheckoutProductTile } from "@/features/cart/components/CheckoutProductTile";
import { useLineItemActions } from "@/features/cart/components/useLineItemActions";
import { useCart } from "@/features/cart/useCart";
import { useTranslations } from "@/i18n/I18nProvider";

export type MiniCartProps = {
  id: string;
  onClose(): void;
  triggerRef?: RefObject<HTMLElement | null>;
  className?: string;
};

export function MiniCart({
  id,
  onClose,
  triggerRef,
  className,
}: MiniCartProps) {
  const { status, lineItems, subtotal } = useCart();
  const { remove, updateQuantity } = useLineItemActions();
  const t = useTranslations();
  const pathname = usePathname();
  const openedAt = useRef(pathname);
  const panelRef = useRef<HTMLElement>(null);
  const titleId = useId();
  const isEmpty = status !== "loading" && lineItems.length === 0;

  const isInside = useCallback(
    (target: EventTarget | null) =>
      target instanceof Node &&
      Boolean(
        panelRef.current?.contains(target) ||
        triggerRef?.current?.contains(target),
      ),
    [triggerRef],
  );

  const returnFocus = useCallback(() => {
    const active = document.activeElement;
    if (!active || active === document.body || isInside(active)) {
      triggerRef?.current?.focus();
    }
  }, [isInside, triggerRef]);

  useEffect(() => {
    if (pathname !== openedAt.current) onClose();
  }, [pathname, onClose]);

  useEffect(() => {
    if (!isEmpty) return;
    returnFocus();
    onClose();
  }, [isEmpty, returnFocus, onClose]);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return;
      returnFocus();
      onClose();
    };

    const handleMouseDown = (event: MouseEvent) => {
      if (!isInside(event.target)) onClose();
    };

    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("mousedown", handleMouseDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("mousedown", handleMouseDown);
    };
  }, [isInside, returnFocus, onClose]);

  return (
    <section
      ref={panelRef}
      id={id}
      data-testid="mini-cart-container"
      aria-labelledby={titleId}
      className={cx("z-40 w-full max-w-[500px]", className)}
    >
      <div className="flex items-center justify-between border border-outline-outline-variant bg-surface-surface px-6 pt-4 pb-3">
        <h2
          id={titleId}
          className="font-serif text-2xl leading-9 font-normal text-surface-on-surface"
        >
          {t("cart.miniCart.title")}
        </h2>
        <IconButton
          variant="ghost"
          className="rounded-full p-2"
          data-testid="mini-cart-close-button"
          aria-label={t("cart.miniCart.close")}
          onClick={() => {
            triggerRef?.current?.focus();
            onClose();
          }}
        >
          <CloseIcon className="size-3" />
        </IconButton>
      </div>
      <ul className="max-h-[365px] divide-y divide-outline-outline-variant overflow-y-auto border border-t-0 border-outline-outline-variant bg-surface-surface px-6 py-3">
        {lineItems.map((item) => (
          <li key={item.id} className="py-8 first:pt-3">
            <CheckoutProductTile
              item={item}
              onRemove={(lineItemId) => {
                void remove(lineItemId);
              }}
              onChangeQuantity={updateQuantity}
            />
          </li>
        ))}
      </ul>
      <div className="border border-t-0 border-outline-outline-variant bg-surface-surface-container-low px-6 py-3">
        <div className="mb-2 flex items-center justify-between">
          <span className="text-surface-on-surface">
            {t("cart.miniCart.subtotal")}
          </span>
          <Price
            className="leading-6 font-bold text-surface-on-surface"
            value={subtotal}
          />
        </div>
        <p className="mb-6 text-right leading-6 text-surface-on-surface-variant">
          {t("cart.miniCart.taxEstimation")}
        </p>
        <LocaleLink
          href="/checkout"
          data-testid="checkout-cart-link"
          className="mb-2 block rounded-md bg-brand-primary py-1.5 text-center leading-6 font-bold text-brand-on-primary hover:bg-brand-primary-hover"
        >
          {t("cart.miniCart.proceedToCheckout")}
        </LocaleLink>
        <LocaleLink
          href="/checkout/cart"
          className="block rounded-md bg-brand-secondary py-1.5 text-center leading-6 font-bold text-brand-on-secondary hover:bg-brand-secondary-hover"
        >
          {t("cart.miniCart.goToShoppingCart")}
        </LocaleLink>
      </div>
    </section>
  );
}

// templates/vue-starter-template-extended/base-template/app/components/layout/MiniCart.vue
<script setup lang="ts">
import { onClickOutside } from "@vueuse/core";

const localePath = useLocalePath();
const { formatLink } = useInternationalization(localePath);
const { cartItems, subtotal, removeItemById } = useCart();

const emit = defineEmits<{
  closeMiniCart: [];
}>();

const miniCartContainer = useTemplateRef("miniCartContainer");

function handleCloseMiniCart() {
  emit("closeMiniCart");
}

function handleRemoveItem(itemId: string) {
  removeItemById(itemId);
}

watch(cartItems, () => {
  if (cartItems.value.length === 0) {
    handleCloseMiniCart();
  }
});

onClickOutside(miniCartContainer, () => {
  handleCloseMiniCart();
});
</script>
<template>
  <div ref="miniCartContainer" class="z-20 max-w-[500px] w-full">
    <div
      class="px-6 pt-4 pb-3 border bg-surface-surface flex items-center justify-between"
    >
      <div
        class="text-surface-on-surface text-2xl font-normal font-['Noto_Serif'] leading-9"
      >
        {{ $t("cart.miniCart.title") }}
      </div>
      <FormIconButton type="ghost" @click.stop="handleCloseMiniCart">
        <Icon name="shopware:times-s" class="w-3 h-3" />
      </FormIconButton>
    </div>
    <div
      class="px-6 py-3 border border-t-0 bg-surface-surface divide-y divide-surface-outline max-h-[365px] overflow-y-auto"
    >
      <CheckoutProductTile
        v-for="item in cartItems"
        :key="item.id"
        :item
        class="py-8 first:pt-3"
        @remove="handleRemoveItem"
      />
    </div>
    <div class="px-6 py-3 border border-t-0 bg-surface-surface-container-low">
      <div class="flex items-center justify-between mb-2">
        <div class="text-surface-on-surface">
          {{ $t("cart.miniCart.subtotal") }}
        </div>
        <SharedPrice
          class="text-surface-on-surface font-bold leading-6"
          :value="subtotal"
        />
      </div>
      <div class="text-right text-surface-on-surface-variant leading-6 mb-6">
        {{ $t("cart.miniCart.taxEstimation") }}
      </div>
      <NuxtLink
        :to="formatLink('/checkout')"
        class="bg-brand-primary text-brand-on-primary block text-center font-bold leading-6 py-1.5 rounded-md mb-2"
        >{{ $t("cart.miniCart.proceedToCheckout") }}</NuxtLink
      >
      <NuxtLink
        :to="formatLink('/checkout/cart')"
        class="bg-brand-secondary text-brand-on-secondary block text-center font-bold leading-6 py-1.5 rounded-md"
        >{{ $t("cart.miniCart.goToShoppingCart") }}</NuxtLink
      >
    </div>
  </div>
</template>
