// packages/cms-base-layer-react/src/components/block/CmsBlockTextTeaser.tsx
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockTextTeaser as CmsBlockTextTeaserContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockTextTeaser({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockTextTeaserContent>) {
  return (
    <div className={className} style={style}>
      {content.slots.map((slot) => (
        <CmsGenericElement key={slot.id} content={slot} ctx={ctx} />
      ))}
    </div>
  );
}

// packages/cms-base/components/public/cms/block/CmsBlockTextTeaser.vue
<script setup lang="ts">
import type { CmsBlockTextTeaser } from "@shopware-pwa/composables-next";

defineProps<{
  content: CmsBlockTextTeaser;
}>();
</script>
<template>
  <div>
    <CmsGenericElement
      v-for="slot in content.slots"
      :key="slot.id"
      :content="slot"
    />
  </div>
</template>
