// packages/cms-base-layer-react/src/components/block/CmsBlockImage.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImage as CmsBlockImageContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImage({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageContent>) {
  const imageContent = getSlotContent(content, "image");

  return (
    <div className={cx(className) || undefined} style={style}>
      <CmsGenericElement content={imageContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base/components/public/cms/block/CmsBlockImage.vue
<script setup lang="ts">
import { CmsBlockImage } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockImage;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const imageContent = getSlotContent("image");
</script>
<template>
  <div>
    <CmsGenericElement :content="imageContent" />
  </div>
</template>
