// packages/cms-base-layer-react/src/components/block/CmsBlockImageThreeColumn.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageThreeColumn as CmsBlockImageThreeColumnContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageThreeColumn({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageThreeColumnContent>) {
  const leftContent = getSlotContent(content, "left");
  const centerContent = getSlotContent(content, "center");
  const rightContent = getSlotContent(content, "right");

  return (
    <div
      className={cx(
        "flex flex-col sm:flex-row justify-start items-start gap-6 w-full",
        className,
      )}
      style={style}
    >
      <div className="w-full sm:flex-1">
        <CmsGenericElement content={leftContent} ctx={ctx} />
      </div>
      <div className="w-full sm:flex-1">
        <CmsGenericElement content={centerContent} ctx={ctx} />
      </div>
      <div className="w-full sm:flex-1">
        <CmsGenericElement content={rightContent} ctx={ctx} />
      </div>
    </div>
  );
}

// packages/cms-base/components/public/cms/block/CmsBlockImageThreeColumn.vue
<script setup lang="ts">
import type { CmsBlockImageThreeColumn } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockImageThreeColumn;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
const centerContent = getSlotContent("center");
</script>
<template>
  <div class="grid md:grid-cols-3 gap-10">
    <CmsGenericElement :content="leftContent" />
    <CmsGenericElement :content="centerContent" />
    <CmsGenericElement :content="rightContent" />
  </div>
</template>
