// packages/cms-base-layer-react/src/components/block/CmsBlockProductListing.tsx
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockProductListing as CmsBlockProductListingContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockProductListing({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockProductListingContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div className={className} style={style}>
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base/components/public/cms/block/CmsBlockProductListing.vue
<script setup lang="ts">
import type { CmsBlockProductListing } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockProductListing;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const slotContent = getSlotContent("content");
</script>

<template>
  <div>
    <CmsGenericElement v-if="slotContent" :content="slotContent" />
  </div>
</template>
