// packages/cms-base-layer-react/src/components/block/CmsBlockImageSlider.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockImageSlider as CmsBlockImageSliderContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockImageSlider({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockImageSliderContent>) {
  const cmsContent = getSlotContent(content, "imageSlider");

  return (
    <div className={cx("cms-block-image-slider", className)} style={style}>
      <CmsGenericElement content={cmsContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base/components/public/cms/block/CmsBlockImageSlider.vue
<script setup lang="ts">
import type { CmsBlockImageSlider } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockImageSlider;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const cmsContent = getSlotContent("imageSlider");
</script>

<template>
  <div class="cms-block-image-slider">
    <CmsGenericElement :content="cmsContent" />
  </div>
</template>
