// packages/cms-base-layer-react/src/components/block/CmsBlockTextOnImage.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockTextOnImage as CmsBlockTextOnImageContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockTextOnImage({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockTextOnImageContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div
      className={cx(
        "cms-block-text-on-image min-h-[500px] py-20 bg-cover bg-bottom bg-no-repeat relative",
        className,
      )}
      style={style}
    >
      {slotContent && <CmsGenericElement content={slotContent} ctx={ctx} />}
    </div>
  );
}

// packages/cms-base/components/public/cms/block/CmsBlockTextOnImage.vue
<script setup lang="ts">
import type { CmsBlockTextOnImage } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockTextOnImage;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const slotContent = getSlotContent("content");
</script>

<template>
  <CmsGenericElement
    v-if="slotContent"
    :content="slotContent"
    class="cms-block-text-on-image min-h-md"
  />
</template>
