// packages/cms-base-layer-react/src/components/element/CmsElementImage.tsx
import Link from "next/link";
import type { ReactNode } from "react";

import { cx } from "../../helpers/cx";
import { getCmsElementImage } from "../../helpers/image";
import { isSpatial } from "../../helpers/isSpatial";
import { isInternalUrl, prefixUrl } from "../../helpers/resolveUrl";
import type { CmsComponentProps } from "../../registry";
import { withTranslationDefaults } from "../../translations";
import type {
  CmsElementImage as CmsElementImageContent,
  CmsElementManufacturerLogo as CmsElementManufacturerLogoContent,
} from "../../types";
import { CmsMedia } from "../ui/CmsMedia";

const translations = {
  cms: {
    image: {
      linkWithoutLabel: "Open linked page",
    },
  },
};

const FILLING_DISPLAY_MODES: ReadonlySet<string> = new Set([
  "cover",
  "stretch",
]);

export type CmsElementImageProps = CmsComponentProps<
  CmsElementImageContent | CmsElementManufacturerLogoContent
> & {
  imageGallery?: boolean;
};

function CmsElementImage3dPlaceholder() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      width="552"
      height="383"
      viewBox="0 0 552 383"
    >
      <defs>
        <g
          id="icons-default-placeholder"
          fill="none"
          fillRule="evenodd"
          opacity=".65"
        >
          <rect
            width="333.061"
            height="499.591"
            x="84.659"
            y="-82.663"
            fill="#E9EBF2"
            fillRule="nonzero"
            transform="rotate(-89.862 251.19 167.132)"
          ></rect>
          <g transform="translate(51 49)">
            <rect
              width="333.06"
              height="499.59"
              x="83.983"
              y="-83.234"
              fill="#DADDE5"
              fillRule="nonzero"
              transform="rotate(-90 250.513 166.561)"
            ></rect>
            <polygon
              fill="#E9EBF2"
              points="137.18 333.1 500.31 333.1 500.31 302.36 322.15 110.42"
            ></polygon>
            <circle cx="113.04" cy="65.68" r="35.9" fill="#F5F7FC"></circle>
            <polygon
              fill="#F5F7FC"
              points="219.88 157.3 73.85 333.1 383.05 333.1"
            ></polygon>
          </g>
        </g>
      </defs>
      <use
        xlinkHref="#icons-default-placeholder"
        fill="#758CA3"
        fillRule="evenodd"
      ></use>
    </svg>
  );
}

export function CmsElementImage({
  content,
  ctx,
  className,
  style,
  imageGallery = false,
}: CmsElementImageProps) {
  const t = withTranslationDefaults(ctx.translations, translations);
  const {
    ariaLabel,
    containerStyle,
    displayMode,
    imageContainerAttrs,
    imageAttrs,
    imageLink,
    isDecorative,
    isVideoElement,
    mimeType,
  } = getCmsElementImage(content);

  if (!imageAttrs.src) return null;

  const media = content.data?.media;
  const fillsContainer = FILLING_DISPLAY_MODES.has(displayMode);

  let linkAriaLabel: string | undefined;
  if (imageLink.url && !imageAttrs.alt) {
    const mediaTitle = isDecorative ? "" : media?.title;
    linkAriaLabel = ariaLabel || mediaTitle || t.cms.image.linkWithoutLabel;
  }

  const rootClassName = cx(
    "cms-element-image self-stretch relative",
    imageGallery && "flex justify-center items-center",
    className,
  );
  const rootStyle = { ...containerStyle, ...style };

  let child: ReactNode;
  if (isVideoElement) {
    child = (
      <video
        controls
        className={cx(
          "w-full h-full",
          fillsContainer && "absolute inset-0",
          displayMode === "cover" ? "object-cover" : "object-contain",
        )}
      >
        <source src={imageAttrs.src} type={mimeType} />
        Your browser does not support the video tag.
      </video>
    );
  } else if (isSpatial(media)) {
    child = <CmsElementImage3dPlaceholder />;
  } else {
    child = (
      <CmsMedia
        media={media}
        alt={imageAttrs.alt}
        sizes={ctx.imageSizes}
        className={cx(
          !imageGallery && "w-full",
          !imageGallery && fillsContainer && "h-full",
          imageGallery && "w-4/5",
          fillsContainer && "absolute left-0 top-0",
          displayMode === "cover" && "object-cover",
          (imageGallery || displayMode !== "cover") && "object-contain",
        )}
      />
    );
  }

  if (imageLink.url) {
    const href = imageContainerAttrs.href
      ? prefixUrl(imageContainerAttrs.href, ctx.urlPrefix)
      : undefined;

    if (href && isInternalUrl(href)) {
      return (
        <Link
          className={rootClassName}
          style={rootStyle}
          href={href}
          target={imageContainerAttrs.target}
          rel={imageContainerAttrs.rel}
          aria-label={linkAriaLabel}
        >
          {child}
        </Link>
      );
    }

    return (
      <a
        className={rootClassName}
        style={rootStyle}
        href={href}
        target={imageContainerAttrs.target}
        rel={imageContainerAttrs.rel}
        aria-label={linkAriaLabel}
      >
        {child}
      </a>
    );
  }

  return (
    <div className={rootClassName} style={rootStyle}>
      {child}
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/element/CmsElementImage.vue
<script setup lang="ts">
import type {
  CmsElementImage,
  CmsElementManufacturerLogo,
} from "@shopware/composables";
import { buildUrlPrefix } from "@shopware/helpers";
import { useElementSize } from "@vueuse/core";
import { defu } from "defu";
import { computed, defineAsyncComponent, useTemplateRef } from "vue";

import {
  useCmsElementImage,
  useCmsTranslations,
  useUrlResolver,
} from "#imports";

import { isSpatial } from "../../../../helpers/media/isSpatial";

const props = defineProps<{
  content: CmsElementImage | CmsElementManufacturerLogo;
  imageGallery?: boolean;
}>();

type Translations = {
  cms: {
    image: {
      linkWithoutLabel: string;
    };
  };
};

let translations: Translations = {
  cms: {
    image: {
      linkWithoutLabel: "Open linked page",
    },
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const { getUrlPrefix } = useUrlResolver();
const {
  ariaLabel,
  containerStyle,
  displayMode,
  imageContainerAttrs,
  imageAttrs,
  imageLink,
  isDecorative,
  isVideoElement,
  mimeType,
} = useCmsElementImage(props.content);

// A link wrapping only an image is nameless without alt text, which axe
// reports as a `link-name` violation.
const linkAriaLabel = computed(() => {
  if (!imageLink.value.url || imageAttrs.value.alt) {
    return undefined;
  }

  const mediaTitle = isDecorative.value ? "" : props.content.data?.media?.title;

  return (
    ariaLabel.value || mediaTitle || translations.cms.image.linkWithoutLabel
  );
});

const imageElement = useTemplateRef<HTMLImageElement>("imageElement");
const { width, height } = useElementSize(imageElement);

function roundUp(num: number) {
  return Math.ceil(num / 100) * 100;
}

const imageSize = computed(() => {
  const containerSize = Math.max(width.value || 0, height.value || 0);
  if (!containerSize) return undefined;
  return roundUp(containerSize * 2);
});

const imageComputedContainerAttrs = computed(() => {
  const imageAttrsCopy = Object.assign({}, imageContainerAttrs.value);
  if (imageAttrsCopy?.href) {
    imageAttrsCopy.href = buildUrlPrefix(
      imageAttrsCopy.href,
      getUrlPrefix(),
    ).path;
  }
  return imageAttrsCopy;
});

const SwMedia3D = computed(() => {
  if (isSpatial(props.content.data.media)) {
    return defineAsyncComponent(() => import("../../../SwMedia3D.vue"));
  }
  return "";
});
</script>
<template>
  <!-- TODO: using a tag only works with externalLink, need to improve this element to deal with both internalLink & externalLink -->
  <component
    :is="imageLink.url ? 'a' : 'div'"
    v-if="imageAttrs.src"
    class="cms-element-image self-stretch relative"
    :class="{
      'flex justify-center items-center': imageGallery,
    }"
    :style="containerStyle"
    v-bind="imageComputedContainerAttrs"
    :aria-label="linkAriaLabel"
  >
    <video
      v-if="isVideoElement"
      controls
      :class="{
        'w-full h-full': true,
        'absolute inset-0': ['cover', 'stretch'].includes(displayMode),
        'object-cover': displayMode === 'cover',
        'object-contain': displayMode !== 'cover',
      }"
    >
      <source :src="imageAttrs.src" :type="mimeType" />
      Your browser does not support the video tag.
    </video>
    <ClientOnly v-else-if="isSpatial(props.content.data.media)">
      <component :is="SwMedia3D" :src="props.content.data.media.url" />
    </ClientOnly>
    <NuxtImg
      v-else
      ref="imageElement"
      preset="productDetail"
      loading="lazy"
      :width="imageSize"
      :class="{
        'w-full': !imageGallery,
        'h-full': !imageGallery && ['cover', 'stretch'].includes(displayMode),
        'w-4/5': imageGallery,
        'absolute left-0 top-0': ['cover', 'stretch'].includes(displayMode),
        'object-cover': displayMode === 'cover',
        'object-contain': imageGallery || displayMode !== 'cover',
      }"
      :alt="imageAttrs.alt"
      :src="imageAttrs.src"
    />
  </component>
</template>

<style scoped>
.cms-element-image {
  display: block;
  width: 100%;
  height: 100%;
}

/* Ensure anchor tags within the element fill the container */
.cms-element-image a {
  display: block;
  width: 100%;
  height: 100%;
}
</style>
