// packages/cms-base-layer-react/src/components/element/CmsElementBuyBox.tsx
import { getTranslatedProperty } from "@shopware/helpers";

import { cx } from "../../helpers/cx";
import { formatPrice } from "../../helpers/formatPrice";
import { getConfigValue } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import { withTranslationDefaults } from "../../translations";
import type { CmsElementBuyBox as CmsElementBuyBoxContent } from "../../types";
import { getProductPrice } from "../shared/productPrice";
import { SwProductAddToCart } from "../shared/SwProductAddToCart";
import { SwSharedPrice } from "../shared/SwSharedPrice";
import { SwVariantConfigurator } from "../shared/SwVariantConfigurator";
import { formatReferencePrice } from "./formatReferencePrice";

const translationDefaults = {
  product: {
    previously: "Previously",
    amount: "Amount",
    price: {
      label: "Price",
      to: "To",
      from: "From",
    },
    to: "To",
    from: "From",
    content: "Content",
    pricesIncl: "Prices incl. VAT plus shipping costs",
    pricesExcl: "Prices excl. VAT plus shipping costs",
  },
};

export function CmsElementBuyBox({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsElementBuyBoxContent>) {
  const product = content.data?.product;
  if (!product) return null;

  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );
  const alignment = getConfigValue(content, "alignment");
  const { unitPrice, price, tierPrices, hasListPrice } =
    getProductPrice(product);
  const regulationPrice = price?.regulationPrice?.price;
  const referencePrice = product.calculatedPrice?.referencePrice;
  const purchaseUnit = product.purchaseUnit;
  const unitName = getTranslatedProperty(product.unit, "name");
  const productName = product.translated?.name || "";

  return (
    <div
      className={cx(
        "h-full w-full flex flex-col",
        alignment === "flex-start" && "justify-start",
        alignment === "flex-end" && "justify-end",
        alignment === "center" && "justify-center",
        className,
      )}
      style={style}
    >
      <div className="self-stretch inline-flex flex-col justify-start items-start gap-8 mt-4 min-w-0">
        <div className="md:hidden self-stretch text-surface-on-surface text-4xl font-normal font-serif leading-[60px]">
          {productName}
        </div>

        {tierPrices.length <= 1 ? (
          <div>
            {hasListPrice ? (
              <SwSharedPrice
                className="text-xl text-surface-on-surface basis-2/6 justify-start line-through"
                value={price?.listPrice?.price}
                ctx={ctx}
              />
            ) : null}
            {unitPrice ? (
              <SwSharedPrice
                className={cx(
                  "text-surface-on-surface text-base font-bold leading-normal",
                  hasListPrice && "text-states-error",
                )}
                value={unitPrice}
                ctx={ctx}
              />
            ) : null}
            {regulationPrice ? (
              <div className="text-xs flex text-surface-on-surface-variant">
                {translations.product.previously}
                <SwSharedPrice
                  className="ml-1"
                  value={regulationPrice}
                  ctx={ctx}
                />
              </div>
            ) : null}
          </div>
        ) : (
          <div>
            <table className="border-collapse table-auto w-full text-sm mb-8">
              <thead>
                <tr>
                  <th className="border-b font-medium p-4 pl-8 pt-0 pb-3 text-surface-on-surface-variant text-left">
                    {translations.product.amount}
                  </th>
                  <th className="border-b font-medium p-4 pr-8 pt-0 pb-3 text-surface-on-surface-variant text-left">
                    {translations.product.price.label}
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white">
                {tierPrices.map((tierPrice, index) => (
                  <tr key={tierPrice.label}>
                    <td className="border-b border-outline-outline-variant p-4 pl-8 font-medium text-surface-on-surface-variant">
                      <span>
                        {index < tierPrices.length - 1
                          ? translations.product.to
                          : translations.product.from}
                      </span>{" "}
                      {tierPrice.quantity}
                    </td>
                    <td className="border-b border-outline-outline-variant p-4 pr-8 font-medium text-current">
                      {formatPrice(tierPrice.unitPrice, ctx)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {purchaseUnit && unitName ? (
          <div className="mt-1">
            <span className="font-light">{`${translations.product.content}: `}</span>
            <span className="font-light">{`${purchaseUnit} ${unitName}`}</span>
            {referencePrice ? (
              <span className="font-light">
                {` ${formatReferencePrice(referencePrice.price, ctx)} / ${referencePrice.referenceUnit} ${referencePrice.unitName}`}
              </span>
            ) : null}
          </div>
        ) : null}

        <span className="text-brand-primary">
          {ctx.taxState === "gross"
            ? translations.product.pricesIncl
            : translations.product.pricesExcl}
        </span>

        <SwVariantConfigurator
          product={product}
          optionGroups={content.data?.configuratorSettings}
          ctx={ctx}
        />
        <SwProductAddToCart product={product} ctx={ctx} />
      </div>
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/element/CmsElementBuyBox.vue
<script setup lang="ts">
import type { CmsElementBuyBox } from "@shopware/composables";
import { useCmsTranslations } from "@shopware/composables";
import { defu } from "defu";
import { computed } from "vue";
import {
  useCmsElementConfig,
  usePrice,
  useProduct,
  useProductPrice,
  useSessionContext,
} from "#imports";

const props = defineProps<{
  content: CmsElementBuyBox;
}>();

type Translations = {
  product: {
    previously: string;
    amount: string;
    price: {
      [key: string]: string;
    };
    to: string;
    from: string;
    content: string;
    pricesIncl: string;
    pricesExcl: string;
  };
};

let translations: Translations = {
  product: {
    previously: "Previously",
    amount: "Amount",
    price: {
      label: "Price",
      to: "To",
      from: "From",
    },
    to: "To",
    from: "From",
    content: "Content",
    pricesIncl: "Prices incl. VAT plus shipping costs",
    pricesExcl: "Prices excl. VAT plus shipping costs",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const { getConfigValue } = useCmsElementConfig(props.content);
const alignment = computed(() => getConfigValue("alignment"));
const { taxState, currency } = useSessionContext();
const { product, changeVariant } = useProduct(
  props.content.data.product,
  props.content.data.configuratorSettings || [],
);
const { unitPrice, price, tierPrices, hasListPrice } = useProductPrice(product);
const regulationPrice = computed(() => price.value?.regulationPrice?.price);
const { getFormattedPrice } = usePrice();
const referencePrice = computed(
  () => product.value?.calculatedPrice?.referencePrice,
);
const purchaseUnit = computed(() => product.value?.purchaseUnit);
const unitName = computed(() => product.value?.unit?.name);
const productName = computed(() => product.value?.translated?.name || "");
</script>
<template>
  <div
    v-if="product"
    :class="{
      'h-full w-full flex flex-col': true,
      'justify-start': alignment === 'flex-start',
      'justify-end': alignment === 'flex-end',
      'justify-center': alignment === 'center',
    }"
  >
    <div
      class="self-stretch inline-flex flex-col justify-start items-start gap-8 mt-4 min-w-0"
    >
      <div
        class="md:hidden self-stretch text-surface-on-surface text-4xl font-normal font-serif leading-[60px]"
      >
        {{ productName }}
      </div>

      <div v-if="tierPrices.length <= 1">
        <SwSharedPrice
          v-if="hasListPrice"
          class="text-1xl text-secondary-900 basis-2/6 justify-start line-through"
          :value="price?.listPrice?.price"
        />
        <SwSharedPrice
          v-if="unitPrice"
          class="text-surface-on-surface text-base font-bold leading-normal"
          :class="{
            'text-red': hasListPrice,
          }"
          :value="unitPrice"
        />
        <div v-if="regulationPrice" class="text-xs flex text-secondary-500">
          {{ translations.product.previously }}
          <SwSharedPrice class="ml-1" :value="regulationPrice" />
        </div>
      </div>
      <div v-else>
        <table class="border-collapse table-auto w-full text-sm mb-8">
          <thead>
            <tr>
              <th
                class="border-b dark:border-secondary-600 font-medium p-4 pl-8 pt-0 pb-3 text-secondary-600 dark:text-secondary-200 text-left"
              >
                {{ translations.product.amount }}
              </th>

              <th
                class="border-b dark:border-secondary-600 font-medium p-4 pr-8 pt-0 pb-3 text-secondary-600 dark:text-secondary-200 text-left"
              >
                {{ translations.product.price.label }}
              </th>
            </tr>
          </thead>
          <tbody class="bg-white dark:bg-secondary-800">
            <tr v-for="(tierPrice, index) in tierPrices" :key="tierPrice.label">
              <td
                class="border-b border-secondary-100 dark:border-secondary-700 p-4 pl-8 font-medium text-secondary-500 dark:text-secondary-400"
              >
                <span v-if="index < tierPrices.length - 1">{{
                  translations.product.to
                }}</span
                ><span v-else>{{ translations.product.from }}</span>
                {{ tierPrice.quantity }}
              </td>
              <td
                class="border-b border-secondary-100 dark:border-secondary-700 p-4 pr-8 font-medium text-current-500 dark:text-secondary-400"
              >
                {{ getFormattedPrice(tierPrice.unitPrice) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div v-if="purchaseUnit && unitName" class="mt-1">
        <span class="font-light"> {{ translations.product.content }}: </span>
        <span class="font-light"> {{ purchaseUnit }} {{ unitName }} </span>
        <span v-if="referencePrice" class="font-light">
          {{ currency?.symbol }} {{ referencePrice?.price }} / /
          {{ referencePrice?.referenceUnit }} {{ referencePrice?.unitName }}
        </span>
      </div>
      <span class="text-brand-primary">
        <template v-if="taxState === 'gross'">
          {{ translations.product.pricesIncl }}
        </template>
        <template v-else> {{ translations.product.pricesExcl }} </template>
      </span>
      <SwVariantConfigurator @change="changeVariant" />
      <SwProductAddToCart :product="product" />
    </div>
  </div>
</template>
