// packages/cms-base-layer-react/src/components/element/CmsElementProductDescriptionReviews.tsx
import { getTranslatedProperty } from "@shopware/helpers";

import { cx } from "../../helpers/cx";
import type { CmsComponentProps } from "../../registry";
import { sanitizeHtml } from "../../rich-text/sanitize";
import { withTranslationDefaults } from "../../translations";
import type { CmsTranslations } from "../../translations";
import type { CmsElementProductDescriptionReviews as CmsElementProductDescriptionReviewsContent } from "../../types";
import { SwProductReviews } from "../shared/SwProductReviews";
import { CmsElementProductDescriptionReviewsTabs } from "./CmsElementProductDescriptionReviewsTabs";

const translationDefaults = {
  product: {
    description: "Description",
    reviews: "Reviews",
    messages: {
      reviewAdded: "Thank you for submitting your review",
      loginToReview: "Please log in to write a review",
    },
  },
  errors: {} as CmsTranslations,
};

export function CmsElementProductDescriptionReviews({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsElementProductDescriptionReviewsContent>) {
  const product = content.data?.product ?? ctx.product;
  const reviews = content.data?.reviews?.elements ?? [];
  const description = sanitizeHtml(
    getTranslatedProperty(product, "description"),
  );
  const isLoggedIn = ctx.isLoggedIn;
  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );

  return (
    <div
      className={cx(
        "w-full self-stretch inline-flex flex-col justify-start items-start gap-4",
        className,
      )}
      style={style}
    >
      <CmsElementProductDescriptionReviewsTabs
        productId={product?.id}
        reviewCount={reviews.length}
        isLoggedIn={isLoggedIn}
        translations={{
          product: translations.product,
          errors: translations.errors,
        }}
        description={
          <div
            className="cms-element-text"
            dangerouslySetInnerHTML={{ __html: description }}
          />
        }
        reviews={
          product ? <SwProductReviews reviews={reviews} ctx={ctx} /> : null
        }
        categories={
          product?.categories ? (
            <div>
              {product.categories.map((category) => (
                <div key={category.id} className="mb-2">
                  {getTranslatedProperty(category, "name")}
                </div>
              ))}
            </div>
          ) : (
            <div>No categories available</div>
          )
        }
      />
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/element/CmsElementProductDescriptionReviews.vue
<script setup lang="ts">
import type { CmsElementProductDescriptionReviews } from "@shopware/composables";
import { useCmsTranslations } from "@shopware/composables";
import { getTranslatedProperty } from "@shopware/helpers";
import { defu } from "defu";
import { type Ref, computed, onMounted, ref } from "vue";
import xss from "xss";
import { useProduct } from "#imports";
import type { Schemas } from "#shopware";

const props = defineProps<{
  content: CmsElementProductDescriptionReviews;
}>();

type Translations = {
  product: {
    description: string;
    reviews: string;
    messages: {
      reviewAdded: string;
    };
  };
};

let translations: Translations = {
  product: {
    description: "Description",
    reviews: "Reviews",
    messages: {
      reviewAdded: "Thank you for submitting your review",
    },
  },
};
translations = defu(useCmsTranslations(), translations) as Translations;

const openSections = ref<Set<number>>(new Set([1]));
const { product } = useProduct(props.content.data?.product);

const description = computed(() =>
  xss(getTranslatedProperty(product.value, "description")),
);

const toggleSection = (sectionNumber: number) => {
  if (openSections.value.has(sectionNumber)) {
    openSections.value.delete(sectionNumber);
  } else {
    openSections.value.add(sectionNumber);
  }
};

const isSectionOpen = (sectionNumber: number) => {
  return openSections.value.has(sectionNumber);
};

const reviews: Ref<Schemas["ProductReview"][]> = ref([]);

onMounted(async () => {
  if (props.content.data?.reviews?.elements) {
    reviews.value = props.content.data.reviews.elements;
  }
});
</script>

<template>
  <div class="w-full self-stretch inline-flex flex-col justify-start items-start gap-4">
    <div class="self-stretch flex flex-col justify-center items-center">
      <div
        class="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-start items-center gap-1 cursor-pointer hover:bg-surface-surface-variant transition-colors"
        @click="toggleSection(1)">
        <div class="flex-1 flex items-center gap-2.5">
          <div class="flex-1 text-surface-on-surface text-base font-bold leading-normal">
            {{ translations.product.description }}
          </div>
        </div>
        <div class="w-6 h-6 relative">
          <div class="w-2.5 h-1.5 left-[7px] top-[9.50px] absolute">
            <div class="i-carbon-chevron-down transition-transform duration-200"
              :class="{ 'rotate-180': isSectionOpen(1) }"></div>
          </div>
        </div>
      </div>
    </div>
    <Transition name="accordion">
      <div v-if="isSectionOpen(1)" class="self-stretch flex flex-col justify-center items-center gap-2.5">
        <div
          class="self-stretch text-surface-on-surface text-base font-normal leading-normal">
          <!-- eslint-disable-next-line vue/no-v-html -->
          <div v-html="description"></div>
        </div>
      </div>
    </Transition>
    <div class="self-stretch flex flex-col justify-center items-center">
      <div
        class="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-start items-center gap-1 cursor-pointer hover:bg-surface-surface-variant transition-colors"
        @click="toggleSection(2)">
        <div class="flex-1 flex items-center gap-2.5">
          <div class="flex-1 text-surface-on-surface text-base font-bold leading-normal">
            {{ translations.product.reviews }} ({{ reviews.length }})
          </div>
        </div>
        <div class="w-6 h-6 relative">
          <div class="w-2.5 h-1.5 left-[7px] top-[9.50px] absolute">
            <div class="i-carbon-chevron-down transition-transform duration-200"
              :class="{ 'rotate-180': isSectionOpen(2) }"></div>
          </div>
        </div>
      </div>
    </div>
    <Transition name="accordion">
      <div v-if="isSectionOpen(2)" class="self-stretch flex flex-col justify-center items-center gap-2.5">
        <div
          class="self-stretch text-surface-on-surface text-base font-normal leading-normal">
          <SwProductReviews v-if="product" :product="product" :reviews="reviews" />
        </div>
      </div>
    </Transition>
    <div class="self-stretch flex flex-col justify-center items-center">
      <div
        class="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-start items-center gap-1 cursor-pointer hover:bg-surface-surface-variant transition-colors"
        @click="toggleSection(3)">
        <div class="flex-1 flex items-center gap-2.5">
          <div class="flex-1 text-surface-on-surface text-base font-bold leading-normal">
            Category
          </div>
        </div>
        <div class="w-6 h-6 relative">
          <div class="w-2.5 h-1.5 left-[7px] top-[9.50px] absolute">
            <div class="i-carbon-chevron-down transition-transform duration-200"
              :class="{ 'rotate-180': isSectionOpen(3) }"></div>
          </div>
        </div>
      </div>
    </div>
    <Transition name="accordion">
      <div v-if="isSectionOpen(3)" class="self-stretch flex flex-col justify-center items-center gap-2.5">
        <div
          class="self-stretch text-surface-on-surface text-base font-normal leading-normal">
          <div v-if="product?.categories">
            <div v-for="category in product.categories" :key="category.id" class="mb-2">
              {{ category.name }}
            </div>
          </div>
          <div v-else>
            No categories available
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>
<style scoped>
.accordion-enter-active,
.accordion-leave-active {
  transition: all 0.3s ease;
  overflow: hidden;
}

.accordion-enter-from,
.accordion-leave-to {
  max-height: 0;
  opacity: 0;
  transform: translateY(-10px);
}

.accordion-enter-to,
.accordion-leave-from {
  max-height: 500px;
  opacity: 1;
  transform: translateY(0);
}
</style>
