// packages/cms-base-layer-react/src/components/block/CmsBlockProductListing.tsx
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockProductListing as CmsBlockProductListingContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockProductListing({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockProductListingContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div className={className} style={style}>
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base/components/cms/block/CmsBlockProductListing.vue
<script setup lang="ts">
import { CmsBlockProductListing } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockProductListing;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const slotContent = getSlotContent("content");
</script>

<template>
  <CmsGenericElement v-if="slotContent" :content="slotContent" />
</template>
