// packages/cms-base-layer-react/src/components/block/CmsBlockCategoryNavigation.tsx
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockCategoryNavigation as CmsBlockCategoryNavigationContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockCategoryNavigation({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockCategoryNavigationContent>) {
  const slotContent = getSlotContent(content, "content");

  return (
    <div className={className} style={style}>
      <CmsGenericElement content={slotContent} ctx={ctx} />
    </div>
  );
}

// packages/cms-base/components/cms/block/CmsBlockCategoryNavigation.vue
<script setup lang="ts">
import { CmsBlockCategoryNavigation } from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsBlockCategoryNavigation;
}>();

const { getSlotContent } = useCmsBlock(props.content);
const slotContent = getSlotContent("content");
</script>

<template>
  <CmsGenericElement v-if="slotContent" :content="slotContent" />
</template>
