// templates/vue-starter-template/app/components/checkout/OrderAddress.vue
<script setup lang="ts">
import { getTranslatedProperty } from "@shopware/helpers";

import type { Schemas } from "#shopware";

defineOptions({
  name: "CheckoutOrderAddress",
});

const { address } = defineProps<{
  address: Schemas["OrderAddress"];
  label: string;
}>();

const countryName = computed(() =>
  address.country ? getTranslatedProperty(address.country, "name") : "",
);
</script>
<template>
  <div>
    <h3 class="text-surface-on-surface font-bold leading-normal mb-3">
      {{ label }}
    </h3>
    <address
      class="not-italic p-4 bg-brand-secondary flex flex-col justify-start items-start gap-0.5"
    >
      <div class="text-surface-on-surface text-base leading-normal">
        {{ address.firstName }} {{ address.lastName }}
      </div>
      <div class="text-surface-on-surface text-base leading-normal">
        {{ address.street }}
      </div>
      <div class="text-surface-on-surface text-base leading-normal">
        {{ address.zipcode }} {{ address.city }}
      </div>
      <div
        v-if="countryName"
        class="text-surface-on-surface text-base leading-normal"
      >
        {{ countryName }}
      </div>
    </address>
  </div>
</template>

// templates/react-starter-template/features/checkout/components/OrderAddress.tsx
import { getTranslatedProperty } from "@shopware/helpers";

import type { Schemas } from "#shopware";

export function OrderAddress({
  address,
  label,
}: {
  address: Schemas["OrderAddress"];
  label: string;
}) {
  const countryName = address.country
    ? getTranslatedProperty(address.country, "name")
    : "";

  return (
    <div>
      <h3 className="mb-3 leading-normal font-bold text-surface-on-surface">
        {label}
      </h3>
      <address className="flex flex-col items-start justify-start gap-0.5 bg-brand-secondary p-4 not-italic">
        <span className="text-base leading-normal text-surface-on-surface">
          {address.firstName} {address.lastName}
        </span>
        <span className="text-base leading-normal text-surface-on-surface">
          {address.street}
        </span>
        <span className="text-base leading-normal text-surface-on-surface">
          {address.zipcode} {address.city}
        </span>
        {countryName ? (
          <span className="text-base leading-normal text-surface-on-surface">
            {countryName}
          </span>
        ) : null}
      </address>
    </div>
  );
}
