// packages/cms-base/components/public/cms/section/CmsSectionSidebar.vue
<script setup lang="ts">
import {
  CmsSectionSidebar,
  useCmsSection,
} from "@shopware-pwa/composables-next";

const props = defineProps<{
  content: CmsSectionSidebar;
}>();
const { getPositionContent } = useCmsSection(props.content);

const sidebarBlocks = getPositionContent("sidebar");
const mainBlocks = getPositionContent("main");
const mobileBehavior = computed(() => props.content.mobileBehavior);
</script>

<template>
  <div class="cms-section-sidebar flex flex-col md:block ">
    <div
      :class="{
        'inline-block align-top w-12/12 md:w-3/12 order-2 md:order-1': mobileBehavior !== 'hidden',
        'hidden md:block': mobileBehavior === 'hidden',
      }"
    >
      <CmsGenericBlock
        v-for="cmsBlock in sidebarBlocks"
        class="overflow-auto"
        :key="cmsBlock.id"
        :content="cmsBlock"
      />
    </div>
    <div class="inline-block w-12/12 md:w-9/12 order-1 md:order-2">
      <CmsGenericBlock
        v-for="cmsBlock in mainBlocks"
        class="overflow-auto"
        :key="cmsBlock.id"
        :content="cmsBlock"
      />
    </div>
  </div>
</template>

// packages/cms-base-layer-react/src/components/section/CmsSectionSidebar.tsx
import { cx } from "../../helpers/cx";
import { getPositionContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsSectionSidebar as CmsSectionSidebarContent } from "../../types";
import { CmsGenericBlock } from "../core/CmsGenericBlock";

export function CmsSectionSidebar({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsSectionSidebarContent>) {
  const sidebarBlocks = getPositionContent(content, "sidebar");
  const mainBlocks = getPositionContent(content, "main");
  const hideSidebarOnMobile = content.mobileBehavior === "hidden";
  const fullWidth = content.sizingMode === "full_width";
  const sectionCtx = { ...ctx, sectionLayout: "sidebar" as const };

  return (
    <div
      className={cx(
        "self-stretch flex flex-col lg:flex-row items-stretch gap-16",
        fullWidth && "px-6",
        className,
      )}
      style={style}
    >
      <aside
        className={
          hideSidebarOnMobile
            ? "hidden lg:block"
            : "w-full lg:w-72 xl:w-80 flex-shrink-0 bg-surface-surface flex flex-col justify-start items-stretch gap-4 lg:sticky lg:top-20 px-4 lg:px-0"
        }
      >
        {sidebarBlocks.map((block) => (
          <div key={block.id} className="w-full">
            <CmsGenericBlock content={block} ctx={sectionCtx} />
          </div>
        ))}
      </aside>
      <div className="flex-1 flex flex-col justify-start items-stretch gap-20">
        {mainBlocks.map((block) => (
          <div key={block.id} className="w-full">
            <CmsGenericBlock content={block} ctx={sectionCtx} />
          </div>
        ))}
      </div>
    </div>
  );
}
