// templates/react-starter-template/features/layout/components/MainCounter.tsx
import { cx } from "@shopware/cms-base-layer-react/client";

export function MainCounter({
  count,
  className,
}: {
  count: number;
  className?: string;
}) {
  return (
    <span
      className={cx(
        "block size-[18px] rounded-full bg-states-error text-center text-xs leading-[18px] font-bold text-white",
        className,
      )}
    >
      {count}
    </span>
  );
}

// packages/cms-base-layer/app/components/ui/MainCounter.vue
<script lang="ts" setup>
defineSlots<{
  default(): unknown;
}>();

defineProps<{
  count: number;
}>();
</script>
<template>
  <div
    class="w-[18px] h-[18px]  bg-states-error rounded-full overflow-hidden"
  >
    <div
      class="w-[18px] left-0 top-[-2px] absolute text-center justify-start text-white text-sm font-bold leading-[21px]"
    >
      <slot> {{ count }} </slot>
    </div>
  </div>
</template>
