// packages/cms-base-layer-react/src/components/shared/SwFilterProperties.tsx
"use client";

import { getTranslatedProperty } from "@shopware/helpers";
import { useId, useState } from "react";

import { cx } from "../../helpers/cx";
import { ChevronDownIcon } from "../icons";
import { Checkbox } from "../ui/Checkbox";
import type {
  ListingFilter,
  ListingFilterChangeEvent,
  ListingFilterDisplayMode,
} from "./listingFilterTypes";

export type SwFilterPropertiesProps = {
  filter: ListingFilter;
  selectedFilters: { manufacturer?: string[]; properties?: string[] };
  displayMode?: ListingFilterDisplayMode;
  onSelectValue: (event: ListingFilterChangeEvent) => void;
};

export function SwFilterProperties({
  filter,
  selectedFilters,
  displayMode = "accordion",
  onSelectValue,
}: SwFilterPropertiesProps) {
  const [isFilterVisible, setIsFilterVisible] = useState(false);
  const toggle = () => setIsFilterVisible((visible) => !visible);
  const idPrefix = useId();

  const selectedIds =
    filter.code === "manufacturer"
      ? (selectedFilters.manufacturer ?? [])
      : (selectedFilters.properties ?? []);
  const isChecked = (id: string) => selectedIds.includes(id);

  const selectValue = (id: string) => {
    const emitCode =
      filter.code === "manufacturer" ? "manufacturer" : "properties";
    onSelectValue({ code: emitCode, value: id });
  };

  const options = filter.options ?? filter.entities ?? [];

  return (
    <div className="self-stretch flex flex-col justify-start items-start gap-4">
      {displayMode === "accordion" && (
        <div className="self-stretch flex flex-col justify-center items-center">
          <button
            type="button"
            className="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-between items-center gap-1 cursor-pointer"
            onClick={toggle}
            aria-expanded={isFilterVisible}
            aria-controls={filter.code}
            aria-label={filter.label}
          >
            <div className="flex-1 flex items-center gap-2.5">
              <div className="flex-1 text-surface-on-surface text-base font-bold leading-normal text-left">
                {filter.label}
              </div>
            </div>
            <span
              className="flex items-center justify-center"
              aria-hidden="true"
            >
              <ChevronDownIcon
                width={24}
                height={24}
                className={cx(
                  "transition-transform",
                  isFilterVisible && "rotate-180",
                )}
              />
            </span>
          </button>
        </div>
      )}

      {(isFilterVisible || displayMode === "dropdown") && (
        <div
          id={filter.code}
          className="self-stretch flex flex-col justify-start items-start gap-4"
        >
          <fieldset className="self-stretch flex flex-col justify-start items-start gap-4">
            <legend className="sr-only">{filter.name}</legend>
            {options.map((option) => (
              <label
                key={option.id}
                htmlFor={`${idPrefix}${option.id}`}
                className="self-stretch inline-flex justify-start items-start gap-2 cursor-pointer"
              >
                <div className="w-4 self-stretch pt-[3px] flex justify-start items-start gap-2.5">
                  <Checkbox
                    id={`${idPrefix}${option.id}`}
                    checked={isChecked(option.id)}
                    onChange={() => selectValue(option.id)}
                  />
                </div>
                <div className="flex-1 inline-flex flex-col justify-start items-start gap-0.5">
                  <div className="inline-flex justify-start items-center gap-1">
                    <div className="flex-1 text-surface-on-surface text-base font-normal leading-normal">
                      {getTranslatedProperty(option, "name")}
                    </div>
                  </div>
                </div>
              </label>
            ))}
          </fieldset>
        </div>
      )}
    </div>
  );
}

// packages/cms-base/components/listing-filters/SwFilterProperties.vue
<script
  setup
  lang="ts"
  generic="
    ListingFilter extends {
      code: string;
      label: string;
      name: string;
      options: Array<Schemas['PropertyGroupOption']>;
      entities: Array<Schemas['ProductManufacturer']>;
    }
  "
>
import { inject, ref } from "vue";
import { getTranslatedProperty } from "@shopware-pwa/helpers-next";
import type { Schemas } from "#shopware";

const props = defineProps<{
  filter: ListingFilter;
}>();

const emits = defineEmits<{
  (e: "select-value", value: { code: string; value: unknown }): void;
}>();
const selectedOptionIds = inject<string[]>("selectedOptionIds");
const isFilterVisible = ref<boolean>(false);
const toggle = () => {
  isFilterVisible.value = !isFilterVisible.value;
};
</script>

<template>
  <div class="border-b border-gray-200 py-6 px-5">
    <h2 class="-my-3 flow-root">
      <button
        type="button"
        class="flex w-full items-center justify-between bg-white py-2 text-base text-gray-400 hover:text-gray-500"
        @click="toggle"
      >
        <span class="font-medium text-gray-900 text-left">{{
          props.filter.label
        }}</span>
        <span class="ml-6 flex items-center">
          <i
            :class="[
              !isFilterVisible
                ? 'i-carbon-chevron-down'
                : 'i-carbon-chevron-up',
            ]"
          />
        </span>
      </button>
    </h2>
    <transition name="fade" mode="out-in">
      <div v-show="isFilterVisible" :id="props.filter.code" class="pt-6">
        <fieldset class="space-y-4">
          <legend class="sr-only">{{ props.filter.name }}</legend>
          <div
            v-for="option in props.filter.options || props.filter.entities"
            :key="`${option.id}-${selectedOptionIds?.includes(option.id)}`"
            class="flex items-center"
          >
            <input
              :id="`filter-mobile-${props.filter.code}-${option.id}`"
              :checked="selectedOptionIds?.includes(option.id)"
              :name="props.filter.name"
              :value="option.name"
              :aria-label="`${option.name} filter`"
              type="checkbox"
              class="h-4 w-4 border-gray-300 rounded text-indigo-600 focus:ring-indigo-500"
              @click="
                emits('select-value', {
                  code: props.filter.code,
                  value: option.id,
                })
              "
            />

            <div v-if="option.media?.url">
              <img
                loading="lazy"
                class="ml-2 h-4 w-4"
                :src="option.media.url"
                :alt="option.media.translated?.alt || ''"
                :class="{
                  'border-blue border-2': selectedOptionIds?.includes(
                    option.id,
                  ),
                }"
              />
            </div>
            <div
              v-else-if="option.colorHexCode"
              class="ml-2 h-4 w-4"
              :style="`background-color: ${option.colorHexCode}`"
              :class="{
                'border-blue border-2': selectedOptionIds?.includes(option.id),
              }"
            />
            <label
              :for="`filter-mobile-${props.filter.code}-${option.id}`"
              class="ml-3 text-gray-600"
            >
              {{ getTranslatedProperty(option, "name") }}
            </label>
          </div>
        </fieldset>
      </div>
    </transition>
  </div>
</template>
<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: all 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
