// templates/react-starter-template/features/account/components/RegistrationForm.tsx
"use client";

import {
  BaseButton,
  useCmsActions,
} from "@shopware/cms-base-layer-react/client";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import type { ChangeEvent, FormEvent } from "react";

import { CountrySelect } from "@/components/form/CountrySelect";
import { InputField } from "@/components/form/InputField";
import { SelectField } from "@/components/form/SelectField";
import { resolveRedirectFromSearch } from "@/features/account/redirect";
import {
  REGISTRATION_MIN_LENGTHS,
  emptyRegistrationValues,
  toRegistrationInput,
  validateRegistration,
} from "@/features/account/registrationSchema";
import type {
  AccountType,
  RegistrationField,
  RegistrationValues,
} from "@/features/account/registrationSchema";
import { useSessionActions } from "@/features/session/components/SessionActionsContext";
import { useContentLang } from "@/i18n/ContentLanguageProvider";
import { useLocalePath, useTranslations } from "@/i18n/I18nProvider";
import type { CountryOption } from "@/platform/shopware/reads/countryOptions";

type Touched = Partial<Record<RegistrationField, boolean>>;

export type RegistrationFormProps = {
  countries: CountryOption[];
  countriesUnavailable?: boolean;
  companyOnly?: boolean;
  redirectUrl?: string | null;
};

function initialValues(companyOnly: boolean): RegistrationValues {
  return {
    ...emptyRegistrationValues,
    accountType: companyOnly ? "business" : "private",
  };
}

function toAccountType(value: string): AccountType {
  return value === "business" ? "business" : "private";
}

export function RegistrationForm({
  countries,
  countriesUnavailable = false,
  companyOnly = false,
  redirectUrl = null,
}: RegistrationFormProps) {
  const router = useRouter();
  const { register } = useSessionActions();
  const { notify } = useCmsActions();
  const t = useTranslations();
  const contentLang = useContentLang();
  const localePath = useLocalePath();
  const [values, setValues] = useState<RegistrationValues>(() =>
    initialValues(companyOnly),
  );
  const [touched, setTouched] = useState<Touched>({});
  const [submitted, setSubmitted] = useState(false);
  const [pending, setPending] = useState(false);
  const [navigating, startNavigation] = useTransition();
  const [refreshing, startRefresh] = useTransition();
  const [doubleOptInCount, setDoubleOptInCount] = useState(0);
  const [focusRequest, setFocusRequest] = useState(0);
  const formRef = useRef<HTMLFormElement>(null);
  const successBoxRef = useRef<HTMLOutputElement>(null);

  const busy = pending || navigating;
  const doubleOptInPending = doubleOptInCount > 0;

  const business = values.accountType === "business";
  const selectedCountry =
    countries.find((country) => country.id === values.countryId) ?? null;
  const states = selectedCountry?.states ?? [];
  const countryHasStates = states.length > 0;
  const errors = validateRegistration(values, { countryHasStates }, t);
  const minLengthHint = (min: number) =>
    t("account.registration.minLengthHint", { min }, min);
  const accountTypeOptions = [
    { label: t("form.accountType.private"), value: "private" },
    { label: t("form.accountType.business"), value: "business" },
  ];

  const errorFor = (field: RegistrationField) =>
    submitted || touched[field] ? errors[field] : undefined;

  const setField = <K extends RegistrationField>(
    field: K,
    value: RegistrationValues[K],
  ) => setValues((current) => ({ ...current, [field]: value }));

  const touch = (field: RegistrationField) => () =>
    setTouched((current) => ({ ...current, [field]: true }));

  const inputHandler =
    (field: RegistrationField) =>
    (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
      setField(field, event.target.value);

  const handleCountryChange = useCallback((countryId: string) => {
    setValues((current) =>
      current.countryId === countryId
        ? current
        : { ...current, countryId, countryStateId: "" },
    );
  }, []);

  useEffect(() => {
    if (doubleOptInCount === 0) return;
    successBoxRef.current?.scrollIntoView?.({ block: "nearest" });
  }, [doubleOptInCount]);

  useEffect(() => {
    if (focusRequest === 0) return;
    formRef.current
      ?.querySelector<HTMLElement>('[aria-invalid="true"]')
      ?.focus();
  }, [focusRequest]);

  function retryCountries() {
    if (refreshing) return;
    startRefresh(() => {
      router.refresh();
    });
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (busy) return;
    setSubmitted(true);
    if (
      Object.keys(validateRegistration(values, { countryHasStates }, t)).length
    ) {
      setFocusRequest((count) => count + 1);
      return;
    }

    setPending(true);
    try {
      const result = await register(toRegistrationInput(values));
      if (!result.ok) return;
      if (result.doubleOptIn) {
        setValues(initialValues(companyOnly));
        setTouched({});
        setSubmitted(false);
        setDoubleOptInCount((count) => count + 1);
        return;
      }
      const target = resolveRedirectFromSearch(
        window.location.search,
        redirectUrl,
      );
      startNavigation(() => {
        router.push(localePath(target));
      });
    } catch (cause) {
      notify({
        type: "error",
        message: cause instanceof Error ? cause.message : String(cause),
      });
    } finally {
      setPending(false);
    }
  }

  return (
    <div>
      <output ref={successBoxRef} aria-live="polite" className="block">
        {doubleOptInPending ? (
          <span className="mb-4 block border-t border-b border-states-success bg-states-success-container px-4 py-3 text-states-on-success-container">
            {t("account.messages.signUpSuccess")}
          </span>
        ) : null}
      </output>
      <div className="mb-6">
        <h2 id="sign-up-heading" className="text-2xl font-bold">
          {t("account.signUpHeader")}
        </h2>
        <p className="text-sm text-surface-on-surface-variant">
          {t("account.signUpSubHeader")}
        </p>
        <p className="mt-2 text-sm text-surface-on-surface-variant">
          {t("form.requiredFieldsNote")}
        </p>
      </div>
      <form
        ref={formRef}
        className="relative w-full"
        data-testid="registration-form"
        aria-labelledby="sign-up-heading"
        noValidate
        onSubmit={(event) => {
          void handleSubmit(event);
        }}
      >
        <div className="mb-10 grid grid-cols-12 gap-5">
          {companyOnly ? null : (
            <SelectField
              className="col-span-12"
              id="accountType"
              data-testid="registration-account-type-select"
              label={t("form.accountType.title")}
              options={accountTypeOptions}
              value={values.accountType}
              onChange={(event) =>
                setField("accountType", toAccountType(event.target.value))
              }
              onBlur={touch("accountType")}
              error={errorFor("accountType")}
            />
          )}
          <InputField
            className="col-span-12 md:col-span-4"
            id="firstName"
            data-testid="registration-first-name-input"
            label={t("form.firstName")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.firstName)}
            required
            autoComplete="given-name"
            value={values.firstName}
            onChange={inputHandler("firstName")}
            onBlur={touch("firstName")}
            error={errorFor("firstName")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="lastName"
            data-testid="registration-last-name-input"
            label={t("form.lastName")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.lastName)}
            required
            autoComplete="family-name"
            value={values.lastName}
            onChange={inputHandler("lastName")}
            onBlur={touch("lastName")}
            error={errorFor("lastName")}
          />
          <InputField
            className="col-span-12 md:col-span-6"
            id="emailAddress"
            data-testid="registration-email-input"
            type="email"
            label={t("form.email")}
            required
            autoComplete="email"
            value={values.email}
            onChange={inputHandler("email")}
            onBlur={touch("email")}
            error={errorFor("email")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="password"
            data-testid="registration-password-input"
            type="password"
            label={t("form.password")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.password)}
            required
            autoComplete="new-password"
            value={values.password}
            onChange={inputHandler("password")}
            onBlur={touch("password")}
            error={errorFor("password")}
          />
          {business ? (
            <InputField
              className="col-span-12 md:col-span-4"
              id="vatId"
              data-testid="registration-vatid-input"
              label={t("form.vatId")}
              value={values.vatId}
              onChange={inputHandler("vatId")}
              onBlur={touch("vatId")}
              error={errorFor("vatId")}
            />
          ) : null}
        </div>

        <h3
          id="address-heading"
          className="mb-5 block border-b border-outline-outline-variant pb-2 font-bold"
        >
          {t("account.yourAddress")}
        </h3>
        <fieldset
          className="mb-5 grid min-w-0 grid-cols-12 gap-5"
          aria-labelledby="address-heading"
        >
          {business ? (
            <InputField
              className="col-span-12 md:col-span-4"
              id="company"
              data-testid="registration-company-input"
              label={t("form.company")}
              required
              autoComplete="organization"
              value={values.company}
              onChange={inputHandler("company")}
              onBlur={touch("company")}
              error={errorFor("company")}
            />
          ) : null}
          <InputField
            className="col-span-12 md:col-span-4"
            id="street"
            data-testid="registration-street-input"
            label={t("form.streetAddress")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.street)}
            required
            autoComplete="street-address"
            value={values.street}
            onChange={inputHandler("street")}
            onBlur={touch("street")}
            error={errorFor("street")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="zipcode"
            data-testid="registration-zipcode-input"
            label={t("form.postalCode")}
            required
            autoComplete="postal-code"
            value={values.zipcode}
            onChange={inputHandler("zipcode")}
            onBlur={touch("zipcode")}
            error={errorFor("zipcode")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="city"
            data-testid="registration-city-input"
            label={t("form.city")}
            required
            autoComplete="address-level2"
            value={values.city}
            onChange={inputHandler("city")}
            onBlur={touch("city")}
            error={errorFor("city")}
          />
          <div className="col-span-12 flex gap-6 md:col-span-8">
            <div className="w-full">
              <CountrySelect
                className="w-full"
                id="country"
                label={t("form.country")}
                placeholder={t("form.chooseCountry")}
                countries={countries}
                value={values.countryId}
                onChange={handleCountryChange}
                onBlur={touch("countryId")}
                error={errorFor("countryId")}
                loadError={countriesUnavailable}
                required
              />
              {countriesUnavailable ? (
                <BaseButton
                  variant="secondary"
                  size="small"
                  className="mt-2"
                  aria-busy={refreshing}
                  onClick={retryCountries}
                >
                  {t("listing.retry")}
                </BaseButton>
              ) : null}
            </div>
            {countryHasStates ? (
              <SelectField
                className="w-full"
                id="state"
                data-testid="checkout-pi-state-input"
                label={t("form.state")}
                placeholder={t("form.chooseState")}
                required
                autoComplete="address-level1"
                optionsLang={contentLang}
                options={states.map((state) => ({
                  label: state.name,
                  value: state.id,
                }))}
                value={values.countryStateId}
                onChange={inputHandler("countryStateId")}
                onBlur={touch("countryStateId")}
                error={errorFor("countryStateId")}
              />
            ) : null}
          </div>
        </fieldset>
        <div className="mb-5 text-right">
          <BaseButton
            type="submit"
            data-testid="registration-submit-button"
            aria-busy={busy}
            aria-disabled={busy || undefined}
            className="aria-disabled:cursor-not-allowed aria-disabled:opacity-50"
          >
            {t("form.submit")}
          </BaseButton>
        </div>
      </form>
    </div>
  );
}

// templates/vue-demo-store/app/components/account/RegistrationForm.vue
<script setup lang="ts">
import { customValidators } from "@@/i18n/utils/i18n-validators";
import { ApiClientError } from "@shopware/api-client";
import { useVuelidate } from "@vuelidate/core";
const { required, minLength, email, requiredIf } = customValidators();

const props = defineProps<{
  customerGroupId?: string;
  companyOnly?: boolean;
}>();

const { getSalutations } = useSalutations();
const { getStatesForCountry } = useCountries();
const { register, isLoggedIn } = useUser();
const { pushError } = useNotifications();

const router = useRouter();
const loading = ref<boolean>();
const doubleOptInBox = useTemplateRef("doubleOptInBox");
const showDoubleOptInBox = ref(false);
const { t } = useI18n();
if (import.meta.client && isLoggedIn.value) {
  // redirect to account page if user is logged in
  navigateTo({ path: "/account" });
}

watch(isLoggedIn, (isLoggedIn) => {
  if (isLoggedIn) {
    navigateTo({ path: "/account" });
  }
});

const initialState = {
  requestedGroupId: props.customerGroupId,
  accountType: props.companyOnly ? "business" : "private",
  salutationId: "",
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  vatIds: [null],
  billingAddress: {
    company: null,
    street: "",
    zipcode: "",
    city: "",
    countryId: "",
    countryStateId: "",
  },
};

const state = reactive(JSON.parse(JSON.stringify(initialState)));

const rules = computed(() => ({
  accountType: {
    required,
  },
  firstName: {
    required,
    minLength: minLength(3),
  },
  lastName: {
    required,
    minLength: minLength(3),
  },
  email: {
    required,
    email,
  },
  password: {
    required,
    minLength: minLength(8),
  },
  billingAddress: {
    company: {
      required: requiredIf(() => state.accountType === "business"),
    },
    street: {
      required,
      minLength: minLength(3),
    },
    zipcode: {
      required,
    },
    city: {
      required,
    },
    countryId: {
      required,
    },
    countryStateId: {
      required: requiredIf(() => {
        return !!getStatesForCountry(state.billingAddress.countryId)?.length;
      }),
    },
  },
}));

const $v = useVuelidate(rules, state);
const { resolveApiErrors } = useApiErrorsResolver("account_login");

const invokeSubmit = async () => {
  $v.value.$touch();
  const valid = await $v.value.$validate();
  if (valid) {
    try {
      loading.value = true;
      const response = await register(state);
      if (response?.doubleOptInRegistration) {
        Object.assign(state, JSON.parse(JSON.stringify(initialState)));
        showDoubleOptInBox.value = true;
        await nextTick();
        doubleOptInBox.value?.scrollIntoView();
        $v.value.$reset();
      } else if (response?.active) router.push("/");
    } catch (error) {
      if (error instanceof ApiClientError) {
        const errors = resolveApiErrors(error.details.errors);
        for (const error of errors) {
          pushError(error);
        }
      }
    } finally {
      loading.value = false;
    }
  }
};

useBreadcrumbs([
  {
    name: t("breadcrumbs.register"),
    path: "/register",
  },
]);
</script>
<template>
  <div class="max-w-screen-xl mx-auto px-6 sm:px-4">
    <div
      v-if="showDoubleOptInBox"
      ref="doubleOptInBox"
      class="bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3 mb-4"
    >
      {{ $t("account.messages.signUpSuccess") }}
    </div>
    <form
      class="w-full relative mt-10"
      data-testid="registration-form"
      @submit.prevent="invokeSubmit"
    >
      <h3 class="block border-b-1 mb-5 pb-2 font-bold text-xl">
        {{ $t("account.signUpHeader") }}
      </h3>
      <div class="grid grid-cols-12 gap-5 mb-10">
        <div class="col-span-12">
          <label for="accountType">{{ $t("form.accountType.title") }} *</label>
          <select
            v-if="!companyOnly"
            id="accountType"
            v-model="state.accountType"
            name="accountType"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            data-testid="registration-account-type-select"
            @blur="$v.accountType.$touch()"
          >
            <option value="private">
              {{ $t("form.accountType.private") }}
            </option>
            <option value="business">
              {{ $t("form.accountType.business") }}
            </option>
          </select>
        </div>
        <div class="col-span-12">
          <label for="salutation">{{ $t("form.salutation") }}</label>
          <select
            id="salutation"
            v-model="state.salutationId"
            name="salutation"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="'border-secondary-300 focus:border-indigo-500'"
            data-testid="registration-salutation-select"
          >
            <option selected value="">
              {{ $t("form.chooseSalutation") }}
            </option>
            <option
              v-for="salutation in getSalutations"
              :key="salutation.id"
              :value="salutation.id"
            >
              {{ salutation.displayName }}
            </option>
          </select>
        </div>

        <div class="col-span-12 md:col-span-4">
          <label for="first-name">{{ $t("form.firstName") }} *</label>
          <input
            id="first-name"
            v-model="state.firstName"
            name="first-name"
            type="text"
            autocomplete="given-name"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.firstName.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.firstNamePlaceholder')"
            data-testid="registration-first-name-input"
            @blur="$v.firstName.$touch()"
          />
          <span
            v-if="$v.firstName.$error && $v.firstName.$errors[0]?.$message"
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.firstName.$errors[0].$message }}
          </span>
        </div>

        <div class="col-span-12 md:col-span-4">
          <label for="last-name">{{ $t("form.lastName") }} *</label>
          <input
            id="last-name"
            v-model="state.lastName"
            name="last-name"
            type="text"
            autocomplete="family-name"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.lastName.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.lastNamePlaceholder')"
            data-testid="registration-last-name-input"
            @blur="$v.lastName.$touch()"
          />
          <span
            v-if="$v.lastName.$error && $v.lastName.$errors[0]?.$message"
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.lastName.$errors[0].$message }}
          </span>
        </div>

        <div class="col-span-12 md:col-span-6">
          <label for="email-address">{{ $t("form.email") }} *</label>
          <input
            id="email-address"
            v-model="state.email"
            name="email"
            type="email"
            autocomplete="email"
            :class="[
              $v.email.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :placeholder="$t('form.emailPlaceholder')"
            data-testid="registration-email-input"
            @blur="$v.email.$touch()"
          />
          <span
            v-if="$v.email.$error && $v.email.$errors[0]?.$message"
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.email.$errors[0].$message }}
          </span>
        </div>

        <div class="col-span-12 md:col-span-4">
          <label for="password">{{ $t("form.password") }} *</label>
          <input
            id="password"
            v-model="state.password"
            name="password"
            type="password"
            autocomplete="current-password"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.password.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.passwordPlaceholder')"
            data-testid="registration-password-input"
            @blur="$v.password.$touch()"
          />
          <span
            v-if="$v.password.$error && $v.password.$errors[0]?.$message"
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.password.$errors[0].$message }}
          </span>
        </div>
        <div
          v-if="state.accountType === 'business'"
          class="col-span-12 md:col-span-4"
        >
          <label for="vatId">{{ $t("form.vatId") }}</label>
          <input
            id="vatId"
            v-model="state.vatIds[0]"
            name="vatId"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :placeholder="$t('form.vatIdPlaceholder')"
            data-testid="registration-vatid-input"
            @blur="$v.vatIds.$touch()"
          />
        </div>
      </div>

      <h3 class="block border-b-1 mb-5 pb-2 font-bold text-xl">
        {{ $t("account.yourAddress") }}
      </h3>
      <div class="grid grid-cols-12 gap-5 mb-10">
        <div
          v-if="state.accountType === 'business'"
          class="col-span-12 md:col-span-4"
        >
          <label for="company">{{ $t("form.company") }} *</label>
          <input
            id="company"
            v-model="state.billingAddress.company"
            name="company"
            type="text"
            autocomplete="company"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.billingAddress.company.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.companyPlaceholder')"
            data-testid="registration-company-input"
            @blur="$v.billingAddress.company.$touch()"
          />
          <span
            v-if="
              $v.billingAddress.company.$error &&
              $v.billingAddress.company.$errors[0]?.$message
            "
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.billingAddress.company.$errors[0].$message }}
          </span>
        </div>
        <div class="col-span-12 md:col-span-4">
          <label for="street">{{ $t("form.streetAddress") }} *</label>
          <input
            id="street"
            v-model="state.billingAddress.street"
            name="street"
            type="text"
            autocomplete="street-address"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.billingAddress.street.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.streetPlaceholder')"
            data-testid="registration-street-input"
            @blur="$v.billingAddress.street.$touch()"
          />
          <span
            v-if="
              $v.billingAddress.street.$error &&
              $v.billingAddress.street.$errors[0]?.$message
            "
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.billingAddress.street.$errors[0].$message }}
          </span>
        </div>

        <div class="col-span-12 md:col-span-4">
          <label for="zipcode">{{ $t("form.postalCode") }} *</label>
          <input
            id="zipcode"
            v-model="state.billingAddress.zipcode"
            name="zipcode"
            type="text"
            autocomplete="postal-code"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.billingAddress.zipcode.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.postalCodePlaceholder')"
            data-testid="registration-zipcode-input"
            @blur="$v.billingAddress.zipcode.$touch()"
          />
          <span
            v-if="
              $v.billingAddress.zipcode.$error &&
              $v.billingAddress.zipcode.$errors[0]?.$message
            "
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.billingAddress.zipcode.$errors[0].$message }}
          </span>
        </div>

        <div class="col-span-12 md:col-span-4">
          <label for="city">{{ $t("form.city") }} *</label>
          <input
            id="city"
            v-model="state.billingAddress.city"
            name="city"
            type="text"
            autocomplete="address-level2"
            class="appearance-none relative block w-full px-3 py-2 border placeholder-secondary-500 text-secondary-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:z-10 sm:text-sm"
            :class="[
              $v.billingAddress.city.$error
                ? 'border-red-600 focus:border-red-600'
                : 'border-secondary-300 focus:border-indigo-500',
            ]"
            :placeholder="$t('form.cityPlaceholder')"
            data-testid="registration-city-input"
            @blur="$v.billingAddress.city.$touch()"
          />
          <span
            v-if="
              $v.billingAddress.city.$error &&
              $v.billingAddress.city.$errors[0]?.$message
            "
            class="pt-1 text-sm text-red-600 focus:ring-primary border-secondary-300"
          >
            {{ $v.billingAddress.city.$errors[0].$message }}
          </span>
        </div>

        <SharedCountryStateInput
          v-model:country-id="state.billingAddress.countryId"
          v-model:state-id="state.billingAddress.countryStateId"
          :country-id-validation="$v.billingAddress.countryId"
          :state-id-validation="$v.billingAddress.countryStateId"
          class="col-span-12 md:col-span-4"
        />
      </div>
      <div class="mb-5 text-right">
        <button
          class="group relative py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-75 w-full md:w-auto"
          type="submit"
          data-testid="registration-submit-button"
        >
          {{ $t("form.submit") }}
        </button>
      </div>
    </form>
  </div>
</template>
