// packages/cms-base-layer-react/src/components/core/CmsGenericElement.tsx
import type { CSSProperties } from "react";

import type { Schemas } from "#shopware";

import type { CmsContext } from "../../context";
import { cx } from "../../helpers/cx";
import { getCmsLayout } from "../../helpers/layout";
import {
  createCmsElement,
  getCmsComponentName,
  resolveCmsComponent,
} from "../../registry";
import { CmsNoComponent } from "./CmsNoComponent";

export type CmsGenericElementProps = {
  content?: Schemas["CmsSlot"];
  ctx: CmsContext;
  className?: string;
  style?: CSSProperties;
};

export function CmsGenericElement({
  content,
  ctx,
  className,
  style,
}: CmsGenericElementProps) {
  if (!content) return null;

  if (resolveCmsComponent(ctx.registry, content)) {
    const layout = getCmsLayout(content);
    return createCmsElement(ctx.registry, {
      content,
      ctx,
      className: cx(layout.className, className) || undefined,
      style: { ...layout.margins, ...style },
    });
  }

  if (process.env.NODE_ENV !== "production") {
    console.warn(
      `[CMS] Element type "${content.type}" is not implemented.\n  → Create a component named "${getCmsComponentName(content)}" and register it under elements["${content.type}"].\n  📖 Docs: https://developer.shopware.com/frontends/guides/cms/create-elements`,
    );
    return <CmsNoComponent content={content} />;
  }

  return null;
}

// packages/cms-base-layer/app/components/public/cms/CmsGenericElement.vue
<script setup lang="ts">
import { resolveCmsComponent } from "@shopware/composables";
import { getCmsLayoutConfiguration } from "@shopware/helpers";
import { h, resolveComponent } from "vue";

import type { Schemas } from "#shopware";

const props = defineProps<{
  content: Schemas["CmsSlot"];
}>();

const DynamicRender = () => {
  const {
    resolvedComponent,
    componentName,
    isResolved,
    componentNameToResolve,
  } = resolveCmsComponent(props.content);
  if (resolvedComponent) {
    if (!isResolved)
      return h("div", {}, `Problem resolving component: ${componentName}`);

    const { cssClasses, layoutStyles } = getCmsLayoutConfiguration(
      props.content,
    );
    return h(resolvedComponent, {
      content: props.content,
      style: layoutStyles,
      class: cssClasses,
    });
  }
  if (import.meta.dev) {
    console.warn(
      `[CMS] Element type "${componentName}" is not implemented.\n  → Create a component named "${componentNameToResolve}.vue" to render it.\n  📖 Docs: https://developer.shopware.com/frontends/guides/cms/create-elements`,
    );
    return h(resolveComponent("CmsNoComponent"), { content: props.content });
  }
  return h("div", {}, "");
};
</script>

<template>
  <DynamicRender />
</template>
