// packages/cms-base-layer-react/src/components/block/CmsBlockTextTwoColumn.tsx
import { cx } from "../../helpers/cx";
import { getSlotContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsBlockTextTwoColumn as CmsBlockTextTwoColumnContent } from "../../types";
import { CmsGenericElement } from "../core/CmsGenericElement";

export function CmsBlockTextTwoColumn({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsBlockTextTwoColumnContent>) {
  const leftContent = getSlotContent(content, "left");
  const rightContent = getSlotContent(content, "right");

  return (
    <article
      className={cx(
        "cms-block-text-two-column grid md:grid-cols-2 gap-5 md:gap-20",
        className,
      )}
      style={style}
    >
      <CmsGenericElement
        content={leftContent}
        ctx={ctx}
        className="cms-block-text-two-column__text"
      />
      <CmsGenericElement
        content={rightContent}
        ctx={ctx}
        className="cms-block-text-two-column__text"
      />
    </article>
  );
}

// packages/cms-base-layer/components/public/cms/block/CmsBlockTextTwoColumn.vue
<script setup lang="ts">
import type { CmsBlockTextTwoColumn } from "@shopware/composables";
import { useCmsBlock } from "#imports";

const props = defineProps<{
  content: CmsBlockTextTwoColumn;
}>();

const { getSlotContent } = useCmsBlock(props.content);

const leftContent = getSlotContent("left");
const rightContent = getSlotContent("right");
</script>

<template>
  <article class="cms-block-text-two-column grid sm:grid-cols-2 gap-5 md:gap-20">
    <CmsGenericElement
      :content="leftContent"
      class="cms-block-text-two-column__text"
    />
    <CmsGenericElement
      :content="rightContent"
      class="cms-block-text-two-column__text"
    />
  </article>
</template>
