// templates/vue-starter-template/app/components/account/RegistrationForm.vue
<script setup lang="ts">
import { useRegle } from "@regle/core";
import { useTemplateRef } from "vue";

import type { Schemas, operations } from "#shopware";

const {
  redirectUrl,
  customerGroupId,
  companyOnly = false,
} = defineProps<{
  customerGroupId?: string;
  redirectUrl?: string | null;
  companyOnly?: boolean;
}>();

const { register, isLoggedIn } = useUser();
const { handleApiError } = useApiErrorsResolver("account_registration_form");

const loading = ref<boolean>();
const doubleOptInBox = useTemplateRef("doubleOptInBox");
const showDoubleOptInBox = ref(false);

const { push } = useRouter();
const localePath = useLocalePath();
const { formatLink } = useInternationalization(localePath);

if (import.meta.client && isLoggedIn.value) {
  const path = (redirectUrl ?? formatLink("/account")) as string;
  navigateTo({ path });
}

watch(isLoggedIn, (isLoggedIn) => {
  if (isLoggedIn) {
    navigateTo({ path: redirectUrl || "/account" });
  }
});

type RegistrationFormState = Omit<
  operations["register post /account/register"]["body"],
  "storefrontUrl"
>;

const initialState: RegistrationFormState = {
  accountType: companyOnly ? "business" : "private",
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  vatIds: [""],
  billingAddress: {
    id: "",
    customerId: "",
    firstName: "",
    lastName: "",
    company: "",
    street: "",
    zipcode: "",
    city: "",
    countryId: "",
    countryStateId: "",
  },
  acceptedDataProtection: true,
};

const state = reactive<RegistrationFormState>(
  JSON.parse(JSON.stringify(initialState)),
);

const accountTypeModel = computed({
  get: () => state.accountType ?? "private",
  set: (value: "private" | "business") => {
    state.accountType = value;
  },
});

const vatIdModel = computed({
  get: () => state.vatIds?.[0] ?? "",
  set: (value: string) => {
    if (state.vatIds) state.vatIds[0] = value;
    else state.vatIds = [value];
  },
});

const companyModel = computed({
  get: () => state.billingAddress.company ?? "",
  set: (value: string) => {
    state.billingAddress.company = value;
  },
});

const zipcodeModel = computed({
  get: () => state.billingAddress.zipcode ?? "",
  set: (value: string) => {
    state.billingAddress.zipcode = value;
  },
});

const countryIdModel = computed({
  get: () => state.billingAddress.countryId ?? "",
  set: (value: string) => {
    state.billingAddress.countryId = value;
  },
});

const countryStateIdModel = computed({
  get: () => state.billingAddress.countryStateId ?? "",
  set: (value: string) => {
    state.billingAddress.countryStateId = value;
  },
});
const countryHasStates = ref(false);

function handleCountryStatesChange(states: Schemas["CountryState"][]) {
  countryHasStates.value = states.length > 0;
}

const { r$ } = useRegle(
  state,
  registrationFormRules(
    computed(() => state.accountType ?? "private"),
    computed(() => state.billingAddress.countryId),
    countryHasStates,
  ),
);
const invokeSubmit = async () => {
  r$.$touch();
  const { valid } = await r$.$validate();
  if (valid) {
    try {
      loading.value = true;
      const response = await register({
        ...state,
        ...(customerGroupId ? { requestedGroupId: customerGroupId } : {}),
      });
      if (response?.doubleOptInRegistration) {
        Object.assign(state, JSON.parse(JSON.stringify(initialState)));
        showDoubleOptInBox.value = true;
        await nextTick();
        doubleOptInBox.value?.scrollIntoView();
        r$.$reset();
      } else if (response?.active) await push(formatLink("/"));
    } catch (error) {
      handleApiError(error);
    } finally {
      loading.value = false;
    }
  }
};
</script>
<template>
  <div>
    <div
      v-if="showDoubleOptInBox"
      ref="doubleOptInBox"
      class="bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3 mb-4"
      role="status"
      aria-live="polite"
    >
      {{ $t("account.messages.signUpSuccess") }}
    </div>
    <div class="mb-1 p-5">
      <h2 id="sign-up-heading" class="text-2xl font-bold">
        {{ $t("account.signUpHeader") }}
      </h2>
      <p class="text-sm text-text-bg-surface-surface-disabled">
        {{ $t("account.signUpSubHeader") }}
      </p>
    </div>
    <form
      class="w-full relative px-5"
      data-testid="registration-form"
      aria-labelledby="sign-up-heading"
      @submit.prevent="invokeSubmit"
    >
      <div class="grid grid-cols-12 gap-5 mb-10">
        <FormAccountTypeSelect
          v-if="!companyOnly"
          class="col-span-12"
          v-model="accountTypeModel"
          dataTestId="registration-account-type-select"
          id="accountType"
        />

        <FormInputField
          class="col-span-12 md:col-span-4"
          id="firstName"
          v-model="state.firstName"
          autocomplete="given-name"
          :label="$t('form.firstName')"
          :errorMessage="r$.firstName.$errors[0]"
          @blur="r$.firstName.$touch()"
          dataTestId="registration-first-name-input"
        />

        <FormInputField
          class="col-span-12 md:col-span-4"
          id="lastName"
          v-model="state.lastName"
          autocomplete="family-name"
          :label="$t('form.lastName')"
          :errorMessage="r$.lastName.$errors[0]"
          @blur="r$.lastName.$touch()"
          dataTestId="registration-last-name-input"
        />

        <FormInputField
          class="col-span-12 md:col-span-6"
          id="emailAddress"
          v-model="state.email"
          autocomplete="email"
          :label="$t('form.email')"
          :errorMessage="r$.email.$errors[0]"
          @blur="r$.email.$touch()"
          dataTestId="registration-email-input"
        />

        <FormInputField
          class="col-span-12 md:col-span-4"
          id="password"
          v-model="state.password"
          autocomplete="new-password"
          type="password"
          :label="$t('form.password')"
          :errorMessage="r$.password.$errors[0]"
          @blur="r$.password.$touch()"
          dataTestId="registration-password-input"
        />

        <FormInputField
          v-if="state.accountType === 'business'"
          class="col-span-12 md:col-span-4"
          id="vatId"
          v-model="vatIdModel"
          :label="$t('form.vatId')"
          @blur="r$.vatIds?.$touch()"
          dataTestId="registration-vatid-input"
        />
      </div>

      <h3 id="address-heading" class="block border-b-1 mb-5 pb-2 font-bold">
        {{ $t("account.yourAddress") }}
      </h3>
      <div
        class="grid grid-cols-12 gap-5 mb-5"
        aria-labelledby="address-heading"
      >
        <FormInputField
          v-if="state.accountType === 'business'"
          class="col-span-12 md:col-span-4"
          id="company"
          v-model="companyModel"
          autocomplete="company"
          :label="$t('form.company')"
          dataTestId="registration-company-input"
          @blur="r$.billingAddress.company.$touch()"
          :errorMessage="r$.billingAddress.company.$errors[0]"
        />

        <FormInputField
          class="col-span-12 md:col-span-4"
          id="street"
          v-model="state.billingAddress.street"
          autocomplete="street-address"
          :label="$t('form.streetAddress')"
          dataTestId="registration-street-input"
          @blur="r$.billingAddress.street.$touch()"
          :errorMessage="r$.billingAddress.street.$errors[0]"
        />

        <FormInputField
          class="col-span-12 md:col-span-4"
          :label="$t('form.postalCode')"
          id="zipcode"
          v-model="zipcodeModel"
          autocomplete="postal-code"
          dataTestId="registration-zipcode-input"
          @blur="r$.billingAddress.zipcode.$touch()"
          :errorMessage="r$.billingAddress.zipcode.$errors[0]"
        />

        <FormInputField
          class="col-span-12 md:col-span-4"
          :label="$t('form.city')"
          id="city"
          v-model="state.billingAddress.city"
          autocomplete="address-level2"
          dataTestId="registration-city-input"
          @blur="r$.billingAddress.city.$touch()"
          :errorMessage="r$.billingAddress.city.$errors[0]"
        />

        <SharedCountryStateInput
          v-model:country-id="countryIdModel"
          v-model:state-id="countryStateIdModel"
          :country-id-validation="r$.billingAddress.countryId"
          :state-id-validation="r$.billingAddress.countryStateId"
          class="col-span-12 md:col-span-8"
          @states-change="handleCountryStatesChange"
        />
      </div>
      <div class="mb-5 text-right">
        <FormBaseButton
          :label="$t('form.submit')"
          type="submit"
          :aria-busy="loading"
          data-testid="registration-submit-button"
        />
      </div>
    </form>
  </div>
</template>

// templates/react-starter-template/features/account/components/RegistrationForm.tsx
"use client";

import {
  BaseButton,
  useCmsActions,
} from "@shopware/cms-base-layer-react/client";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import type { ChangeEvent, FormEvent } from "react";

import { CountrySelect } from "@/components/form/CountrySelect";
import { InputField } from "@/components/form/InputField";
import { SelectField } from "@/components/form/SelectField";
import { resolveRedirectFromSearch } from "@/features/account/redirect";
import {
  REGISTRATION_MIN_LENGTHS,
  emptyRegistrationValues,
  toRegistrationInput,
  validateRegistration,
} from "@/features/account/registrationSchema";
import type {
  AccountType,
  RegistrationField,
  RegistrationValues,
} from "@/features/account/registrationSchema";
import { useSessionActions } from "@/features/session/components/SessionActionsContext";
import { useContentLang } from "@/i18n/ContentLanguageProvider";
import { useLocalePath, useTranslations } from "@/i18n/I18nProvider";
import type { CountryOption } from "@/platform/shopware/reads/countryOptions";

type Touched = Partial<Record<RegistrationField, boolean>>;

export type RegistrationFormProps = {
  countries: CountryOption[];
  countriesUnavailable?: boolean;
  companyOnly?: boolean;
  redirectUrl?: string | null;
};

function initialValues(companyOnly: boolean): RegistrationValues {
  return {
    ...emptyRegistrationValues,
    accountType: companyOnly ? "business" : "private",
  };
}

function toAccountType(value: string): AccountType {
  return value === "business" ? "business" : "private";
}

export function RegistrationForm({
  countries,
  countriesUnavailable = false,
  companyOnly = false,
  redirectUrl = null,
}: RegistrationFormProps) {
  const router = useRouter();
  const { register } = useSessionActions();
  const { notify } = useCmsActions();
  const t = useTranslations();
  const contentLang = useContentLang();
  const localePath = useLocalePath();
  const [values, setValues] = useState<RegistrationValues>(() =>
    initialValues(companyOnly),
  );
  const [touched, setTouched] = useState<Touched>({});
  const [submitted, setSubmitted] = useState(false);
  const [pending, setPending] = useState(false);
  const [navigating, startNavigation] = useTransition();
  const [refreshing, startRefresh] = useTransition();
  const [doubleOptInCount, setDoubleOptInCount] = useState(0);
  const [focusRequest, setFocusRequest] = useState(0);
  const formRef = useRef<HTMLFormElement>(null);
  const successBoxRef = useRef<HTMLOutputElement>(null);

  const busy = pending || navigating;
  const doubleOptInPending = doubleOptInCount > 0;

  const business = values.accountType === "business";
  const selectedCountry =
    countries.find((country) => country.id === values.countryId) ?? null;
  const states = selectedCountry?.states ?? [];
  const countryHasStates = states.length > 0;
  const errors = validateRegistration(values, { countryHasStates }, t);
  const minLengthHint = (min: number) =>
    t("account.registration.minLengthHint", { min }, min);
  const accountTypeOptions = [
    { label: t("form.accountType.private"), value: "private" },
    { label: t("form.accountType.business"), value: "business" },
  ];

  const errorFor = (field: RegistrationField) =>
    submitted || touched[field] ? errors[field] : undefined;

  const setField = <K extends RegistrationField>(
    field: K,
    value: RegistrationValues[K],
  ) => setValues((current) => ({ ...current, [field]: value }));

  const touch = (field: RegistrationField) => () =>
    setTouched((current) => ({ ...current, [field]: true }));

  const inputHandler =
    (field: RegistrationField) =>
    (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
      setField(field, event.target.value);

  const handleCountryChange = useCallback((countryId: string) => {
    setValues((current) =>
      current.countryId === countryId
        ? current
        : { ...current, countryId, countryStateId: "" },
    );
  }, []);

  useEffect(() => {
    if (doubleOptInCount === 0) return;
    successBoxRef.current?.scrollIntoView?.({ block: "nearest" });
  }, [doubleOptInCount]);

  useEffect(() => {
    if (focusRequest === 0) return;
    formRef.current
      ?.querySelector<HTMLElement>('[aria-invalid="true"]')
      ?.focus();
  }, [focusRequest]);

  function retryCountries() {
    if (refreshing) return;
    startRefresh(() => {
      router.refresh();
    });
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (busy) return;
    setSubmitted(true);
    if (
      Object.keys(validateRegistration(values, { countryHasStates }, t)).length
    ) {
      setFocusRequest((count) => count + 1);
      return;
    }

    setPending(true);
    try {
      const result = await register(toRegistrationInput(values));
      if (!result.ok) return;
      if (result.doubleOptIn) {
        setValues(initialValues(companyOnly));
        setTouched({});
        setSubmitted(false);
        setDoubleOptInCount((count) => count + 1);
        return;
      }
      const target = resolveRedirectFromSearch(
        window.location.search,
        redirectUrl,
      );
      startNavigation(() => {
        router.push(localePath(target));
      });
    } catch (cause) {
      notify({
        type: "error",
        message: cause instanceof Error ? cause.message : String(cause),
      });
    } finally {
      setPending(false);
    }
  }

  return (
    <div>
      <output ref={successBoxRef} aria-live="polite" className="block">
        {doubleOptInPending ? (
          <span className="mb-4 block border-t border-b border-states-success bg-states-success-container px-4 py-3 text-states-on-success-container">
            {t("account.messages.signUpSuccess")}
          </span>
        ) : null}
      </output>
      <div className="mb-6">
        <h2 id="sign-up-heading" className="text-2xl font-bold">
          {t("account.signUpHeader")}
        </h2>
        <p className="text-sm text-surface-on-surface-variant">
          {t("account.signUpSubHeader")}
        </p>
        <p className="mt-2 text-sm text-surface-on-surface-variant">
          {t("form.requiredFieldsNote")}
        </p>
      </div>
      <form
        ref={formRef}
        className="relative w-full"
        data-testid="registration-form"
        aria-labelledby="sign-up-heading"
        noValidate
        onSubmit={(event) => {
          void handleSubmit(event);
        }}
      >
        <div className="mb-10 grid grid-cols-12 gap-5">
          {companyOnly ? null : (
            <SelectField
              className="col-span-12"
              id="accountType"
              data-testid="registration-account-type-select"
              label={t("form.accountType.title")}
              options={accountTypeOptions}
              value={values.accountType}
              onChange={(event) =>
                setField("accountType", toAccountType(event.target.value))
              }
              onBlur={touch("accountType")}
              error={errorFor("accountType")}
            />
          )}
          <InputField
            className="col-span-12 md:col-span-4"
            id="firstName"
            data-testid="registration-first-name-input"
            label={t("form.firstName")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.firstName)}
            required
            autoComplete="given-name"
            value={values.firstName}
            onChange={inputHandler("firstName")}
            onBlur={touch("firstName")}
            error={errorFor("firstName")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="lastName"
            data-testid="registration-last-name-input"
            label={t("form.lastName")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.lastName)}
            required
            autoComplete="family-name"
            value={values.lastName}
            onChange={inputHandler("lastName")}
            onBlur={touch("lastName")}
            error={errorFor("lastName")}
          />
          <InputField
            className="col-span-12 md:col-span-6"
            id="emailAddress"
            data-testid="registration-email-input"
            type="email"
            label={t("form.email")}
            required
            autoComplete="email"
            value={values.email}
            onChange={inputHandler("email")}
            onBlur={touch("email")}
            error={errorFor("email")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="password"
            data-testid="registration-password-input"
            type="password"
            label={t("form.password")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.password)}
            required
            autoComplete="new-password"
            value={values.password}
            onChange={inputHandler("password")}
            onBlur={touch("password")}
            error={errorFor("password")}
          />
          {business ? (
            <InputField
              className="col-span-12 md:col-span-4"
              id="vatId"
              data-testid="registration-vatid-input"
              label={t("form.vatId")}
              value={values.vatId}
              onChange={inputHandler("vatId")}
              onBlur={touch("vatId")}
              error={errorFor("vatId")}
            />
          ) : null}
        </div>

        <h3
          id="address-heading"
          className="mb-5 block border-b border-outline-outline-variant pb-2 font-bold"
        >
          {t("account.yourAddress")}
        </h3>
        <fieldset
          className="mb-5 grid min-w-0 grid-cols-12 gap-5"
          aria-labelledby="address-heading"
        >
          {business ? (
            <InputField
              className="col-span-12 md:col-span-4"
              id="company"
              data-testid="registration-company-input"
              label={t("form.company")}
              required
              autoComplete="organization"
              value={values.company}
              onChange={inputHandler("company")}
              onBlur={touch("company")}
              error={errorFor("company")}
            />
          ) : null}
          <InputField
            className="col-span-12 md:col-span-4"
            id="street"
            data-testid="registration-street-input"
            label={t("form.streetAddress")}
            hint={minLengthHint(REGISTRATION_MIN_LENGTHS.street)}
            required
            autoComplete="street-address"
            value={values.street}
            onChange={inputHandler("street")}
            onBlur={touch("street")}
            error={errorFor("street")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="zipcode"
            data-testid="registration-zipcode-input"
            label={t("form.postalCode")}
            required
            autoComplete="postal-code"
            value={values.zipcode}
            onChange={inputHandler("zipcode")}
            onBlur={touch("zipcode")}
            error={errorFor("zipcode")}
          />
          <InputField
            className="col-span-12 md:col-span-4"
            id="city"
            data-testid="registration-city-input"
            label={t("form.city")}
            required
            autoComplete="address-level2"
            value={values.city}
            onChange={inputHandler("city")}
            onBlur={touch("city")}
            error={errorFor("city")}
          />
          <div className="col-span-12 flex gap-6 md:col-span-8">
            <div className="w-full">
              <CountrySelect
                className="w-full"
                id="country"
                label={t("form.country")}
                placeholder={t("form.chooseCountry")}
                countries={countries}
                value={values.countryId}
                onChange={handleCountryChange}
                onBlur={touch("countryId")}
                error={errorFor("countryId")}
                loadError={countriesUnavailable}
                required
              />
              {countriesUnavailable ? (
                <BaseButton
                  variant="secondary"
                  size="small"
                  className="mt-2"
                  aria-busy={refreshing}
                  onClick={retryCountries}
                >
                  {t("listing.retry")}
                </BaseButton>
              ) : null}
            </div>
            {countryHasStates ? (
              <SelectField
                className="w-full"
                id="state"
                data-testid="checkout-pi-state-input"
                label={t("form.state")}
                placeholder={t("form.chooseState")}
                required
                autoComplete="address-level1"
                optionsLang={contentLang}
                options={states.map((state) => ({
                  label: state.name,
                  value: state.id,
                }))}
                value={values.countryStateId}
                onChange={inputHandler("countryStateId")}
                onBlur={touch("countryStateId")}
                error={errorFor("countryStateId")}
              />
            ) : null}
          </div>
        </fieldset>
        <div className="mb-5 text-right">
          <BaseButton
            type="submit"
            data-testid="registration-submit-button"
            aria-busy={busy}
            aria-disabled={busy || undefined}
            className="aria-disabled:cursor-not-allowed aria-disabled:opacity-50"
          >
            {t("form.submit")}
          </BaseButton>
        </div>
      </form>
    </div>
  );
}
