// packages/cms-base-layer/app/components/public/cms/CmsGenericBlock.vue
<script setup lang="ts">
import { resolveCmsComponent } from "@shopware/composables";
import {
  getBackgroundImageUrl,
  getCmsLayoutConfiguration,
} from "@shopware/helpers";
import { h, provide, resolveComponent } from "vue";

import type { Schemas } from "#shopware";

import { useTypedAppConfig } from "../../../composables/useTypedAppConfig";
import { getImageSizes } from "../../../helpers/cms/getImageSizes";

const props = defineProps<{
  content: Schemas["CmsBlock"];
}>();

const appConfig = useTypedAppConfig();

const slotCount = props.content.slots?.length || 1;
provide("cms-block-slot-count", slotCount);
provide("cms-image-sizes", getImageSizes(slotCount, appConfig.imageSizes));

const DynamicRender = () => {
  const { resolvedComponent, componentName, componentNameToResolve } =
    resolveCmsComponent(props.content);

  if (resolvedComponent) {
    const { cssClasses, layoutStyles } = getCmsLayoutConfiguration(
      props.content,
    );

    if (layoutStyles.backgroundImage) {
      layoutStyles.backgroundImage = getBackgroundImageUrl(
        layoutStyles.backgroundImage,
        props.content,
        {
          format: appConfig.backgroundImage?.format,
          quality: appConfig.backgroundImage?.quality,
        },
      );
    }

    const containerStyles = {
      backgroundColor: layoutStyles.backgroundColor,
      backgroundImage: layoutStyles.backgroundImage,
      backgroundSize: layoutStyles.backgroundSize,
    };

    layoutStyles.backgroundColor = null;
    layoutStyles.backgroundImage = null;
    layoutStyles.backgroundSize = null;
    return h(
      "div",
      {
        style: containerStyles,
      },
      h(resolvedComponent, {
        content: props.content,
        style: layoutStyles,
        class: cssClasses,
      }),
    );
  }
  if (import.meta.dev) {
    console.warn(
      `[CMS] Block type "${componentName}" is not implemented.\n  → Create a component named "${componentNameToResolve}.vue" to render it.\n  📖 Docs: https://developer.shopware.com/frontends/guides/cms/create-blocks`,
    );
    return h(resolveComponent("CmsNoComponent"), { content: props.content });
  }
  return h("div", {}, "");
};
</script>

<template>
  <DynamicRender />
</template>

// packages/cms-base-layer-react/src/components/core/CmsGenericBlock.tsx
import type { Schemas } from "#shopware";

import type { CmsContext } from "../../context";
import { getImageSizes } from "../../helpers/imageSizes";
import { getCmsLayout } from "../../helpers/layout";
import {
  createCmsElement,
  getCmsComponentName,
  resolveCmsComponent,
} from "../../registry";
import { CmsNoComponent } from "./CmsNoComponent";

export type CmsGenericBlockProps = {
  content: Schemas["CmsBlock"];
  ctx: CmsContext;
};

export function CmsGenericBlock({ content, ctx }: CmsGenericBlockProps) {
  if (!resolveCmsComponent(ctx.registry, content)) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(
        `[CMS] Block type "${content.type}" is not implemented.\n  → Create a component named "${getCmsComponentName(content)}" and register it under blocks["${content.type}"].\n  📖 Docs: https://developer.shopware.com/frontends/guides/cms/create-blocks`,
      );
      return <CmsNoComponent content={content} />;
    }
    return null;
  }

  const slotCount = content.slots?.length || 1;
  const blockCtx: CmsContext = {
    ...ctx,
    slotCount,
    imageSizes: getImageSizes(slotCount, ctx.config.imageSizes),
  };
  const layout = getCmsLayout(content, {
    backgroundImage: ctx.config.backgroundImage,
  });

  return (
    <div style={layout.background}>
      {createCmsElement(ctx.registry, {
        content,
        ctx: blockCtx,
        className: layout.className || undefined,
        style: layout.margins,
      })}
    </div>
  );
}
