// packages/cms-base-layer-react/src/components/section/CmsSectionSidebar.tsx
import { cx } from "../../helpers/cx";
import { getPositionContent } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsSectionSidebar as CmsSectionSidebarContent } from "../../types";
import { CmsGenericBlock } from "../core/CmsGenericBlock";

export function CmsSectionSidebar({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsSectionSidebarContent>) {
  const sidebarBlocks = getPositionContent(content, "sidebar");
  const mainBlocks = getPositionContent(content, "main");
  const hideSidebarOnMobile = content.mobileBehavior === "hidden";
  const fullWidth = content.sizingMode === "full_width";
  const sectionCtx = { ...ctx, sectionLayout: "sidebar" as const };

  return (
    <div
      className={cx(
        "self-stretch flex flex-col lg:flex-row items-stretch gap-16",
        fullWidth && "px-6",
        className,
      )}
      style={style}
    >
      <aside
        className={
          hideSidebarOnMobile
            ? "hidden lg:block"
            : "w-full lg:w-72 xl:w-80 flex-shrink-0 bg-surface-surface flex flex-col justify-start items-stretch gap-4 lg:sticky lg:top-20 px-4 lg:px-0"
        }
      >
        {sidebarBlocks.map((block) => (
          <div key={block.id} className="w-full">
            <CmsGenericBlock content={block} ctx={sectionCtx} />
          </div>
        ))}
      </aside>
      <div className="flex-1 flex flex-col justify-start items-stretch gap-20">
        {mainBlocks.map((block) => (
          <div key={block.id} className="w-full">
            <CmsGenericBlock content={block} ctx={sectionCtx} />
          </div>
        ))}
      </div>
    </div>
  );
}

// packages/cms-base-layer/app/components/public/cms/section/CmsSectionSidebar.vue
<script setup lang="ts">
import { useCmsSection } from "@shopware/composables";
import type { CmsSectionSidebar } from "@shopware/composables";
import { computed } from "vue";

const props = defineProps<{
  content: CmsSectionSidebar;
}>();
const { getPositionContent, section } = useCmsSection(props.content);

const sidebarBlocks = getPositionContent("sidebar");
const mainBlocks = getPositionContent("main");
const mobileBehavior = computed(() => props.content.mobileBehavior);
const fullWidth = computed(() => section.sizingMode === "full_width");
</script>

<template>
  <div class="self-stretch flex flex-col lg:flex-row items-stretch gap-16" :class="{
    'px-6': fullWidth,
  }">
    <aside :class="{
      'w-full lg:w-72 xl:w-80 flex-shrink-0 bg-surface-surface flex flex-col justify-start items-stretch gap-4 lg:sticky lg:top-20':
        mobileBehavior !== 'hidden',
      'hidden lg:block': mobileBehavior === 'hidden',
    }">
      <div v-for="cmsBlock in sidebarBlocks" :key="cmsBlock.id" class="w-full">
        <CmsGenericBlock :content="cmsBlock" />
      </div>
    </aside>
    <main class="flex-1 flex flex-col justify-start items-stretch gap-20">
      <div v-for="cmsBlock in mainBlocks" :key="cmsBlock.id" class="w-full">
        <CmsGenericBlock :content="cmsBlock" />
      </div>
    </main>
  </div>
</template>
