// packages/cms-base-layer-react/src/components/shared/SwFilterRating.tsx
"use client";

import { useId, useState } from "react";

import { cx } from "../../helpers/cx";
import { ChevronDownIcon, StarFilledIcon, StarIcon } from "../icons";
import type {
  ListingFilter,
  ListingFilterChangeEvent,
  ListingFilterDisplayMode,
} from "./listingFilterTypes";

export type SwFilterRatingProps = {
  filter: ListingFilter;
  selectedFilters: { rating?: number };
  displayMode?: ListingFilterDisplayMode;
  onSelectValue: (event: ListingFilterChangeEvent) => void;
};

const STARS = [1, 2, 3, 4, 5];

export function SwFilterRating({
  filter,
  selectedFilters,
  displayMode = "accordion",
  onSelectValue,
}: SwFilterRatingProps) {
  const [isHoverActive, setIsHoverActive] = useState(false);
  const [hoveredIndex, setHoveredIndex] = useState(0);
  const [isFilterVisible, setIsFilterVisible] = useState(false);
  const panelId = useId();
  const toggle = () => setIsFilterVisible((visible) => !visible);

  const displayedScore = isHoverActive
    ? hoveredIndex
    : (selectedFilters.rating ?? 0);

  const hoverRating = (key: number) => {
    setHoveredIndex(key);
    setIsHoverActive(true);
  };

  const onChangeRating = (key: number) => {
    const newValue = selectedFilters.rating !== key ? key : undefined;
    onSelectValue({ code: filter.code, value: newValue });
  };

  return (
    <div className="self-stretch flex flex-col justify-start items-start gap-4">
      {displayMode === "accordion" && (
        <div className="self-stretch flex flex-col justify-center items-center">
          <button
            type="button"
            className="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-between items-center gap-1 cursor-pointer"
            onClick={toggle}
            aria-expanded={isFilterVisible}
            aria-controls={panelId}
          >
            <div className="flex-1 flex items-center gap-2.5">
              <div className="flex-1 text-surface-on-surface text-base font-bold leading-normal text-left">
                {filter.label}
              </div>
            </div>
            <span
              className="flex items-center justify-center"
              aria-hidden="true"
            >
              <ChevronDownIcon
                width={24}
                height={24}
                className={cx(
                  "transition-transform",
                  isFilterVisible && "rotate-180",
                )}
              />
            </span>
          </button>
        </div>
      )}

      {(isFilterVisible || displayMode === "dropdown") && (
        <div
          id={panelId}
          className="self-stretch flex flex-col justify-start items-start gap-4"
        >
          <div className="flex flex-row items-center gap-2 mt-2">
            {STARS.map((index) => {
              const Star = displayedScore >= index ? StarFilledIcon : StarIcon;
              return (
                <button
                  key={index}
                  type="button"
                  className="h-6 w-6 cursor-pointer"
                  aria-pressed={selectedFilters.rating === index}
                  aria-label={`${index} star${index !== 1 ? "s" : ""}`}
                  onMouseLeave={() => setIsHoverActive(false)}
                  onBlur={() => setIsHoverActive(false)}
                  onMouseOver={() => hoverRating(index)}
                  onFocus={() => hoverRating(index)}
                  onClick={() => {
                    hoverRating(index);
                    onChangeRating(index);
                  }}
                >
                  <Star className="h-6 w-6" aria-hidden="true" />
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

// packages/cms-base-layer/app/components/listing-filters/SwFilterRating.vue
<script
  setup
  lang="ts"
  generic="
    ListingFilter extends {
      code: string;
      label: string;
    }
  "
>
import ChevronDownIcon from "@cms-assets/chevron-down-xs.svg";
import ChevronUpIcon from "@cms-assets/chevron-up-xs.svg";
import StarEmptyIcon from "@cms-assets/star-empty.svg";
import StarFilledIcon from "@cms-assets/star-filled.svg";
import { computed, ref } from "vue";
import type { Schemas } from "#shopware";

const emits =
  defineEmits<
    (e: "select-value", value: { code: string; value: unknown }) => void
  >();

const props = defineProps<{
  filter: ListingFilter;
  selectedFilters: Schemas["ProductListingResult"]["currentFilters"];
}>();
const isHoverActive = ref(false);
const hoveredIndex = ref(0);
const displayedScore = computed(() =>
  isHoverActive.value ? hoveredIndex.value : props.selectedFilters?.rating || 0,
);

const hoverRating = (key: number) => {
  hoveredIndex.value = key;
  isHoverActive.value = true;
};
const onChangeRating = () => {
  const newValue =
    props.selectedFilters?.rating !== hoveredIndex.value
      ? hoveredIndex.value
      : undefined;
  emits("select-value", { code: props.filter?.code, value: newValue });
};

const isFilterVisible = ref<boolean>(false);
const toggle = () => {
  isFilterVisible.value = !isFilterVisible.value;
};
</script>

<template>
  <div class="self-stretch flex flex-col justify-start items-start gap-4">
    <div data-icon="true" data-level="1" data-state="Default" class="self-stretch flex flex-col justify-start items-start">
      <button
        @click="toggle"
        :aria-expanded="isFilterVisible"
        :aria-controls="`filter-${props.filter.code}`"
        class="self-stretch py-3 border-b border-outline-outline-variant flex justify-between items-center gap-1 bg-transparent w-full cursor-pointer focus:outline-none"
      >
        <div class="text-surface-on-surface text-base font-bold font-['Inter'] leading-normal text-left">
          {{ props.filter.label }}
        </div>
        <img v-if="!isFilterVisible" :src="ChevronDownIcon" alt="Expand filter" class="w-6 h-6" />
        <img v-else :src="ChevronUpIcon" alt="Collapse filter" class="w-6 h-6" />
      </button>
    </div>
    <Transition name="fade">
      <div
        v-if="isFilterVisible"
        :id="`filter-${props.filter.code}`"
        :aria-hidden="!isFilterVisible"
        class="self-stretch flex flex-col justify-start items-start gap-4"
      >
      <div class="flex flex-row items-center gap-2 mt-2">
        <img
          v-for="i in 5"
          :key="i"
          class="h-6 w-6 cursor-pointer"
          :src="displayedScore >= i ? StarFilledIcon : StarEmptyIcon"
          @mouseleave="isHoverActive = false"
          @click="hoverRating(i); onChangeRating()"
          @mouseover="hoverRating(i)"
          alt=""
        />
      </div>
      </div>
    </Transition>
  </div>
</template>
<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: all 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
