// packages/cms-base-layer-react/src/components/shared/SwFilterProperties.tsx
"use client";

import { getTranslatedProperty } from "@shopware/helpers";
import { useId, useState } from "react";

import { cx } from "../../helpers/cx";
import { ChevronDownIcon } from "../icons";
import { Checkbox } from "../ui/Checkbox";
import type {
  ListingFilter,
  ListingFilterChangeEvent,
  ListingFilterDisplayMode,
} from "./listingFilterTypes";

export type SwFilterPropertiesProps = {
  filter: ListingFilter;
  selectedFilters: { manufacturer?: string[]; properties?: string[] };
  displayMode?: ListingFilterDisplayMode;
  onSelectValue: (event: ListingFilterChangeEvent) => void;
};

export function SwFilterProperties({
  filter,
  selectedFilters,
  displayMode = "accordion",
  onSelectValue,
}: SwFilterPropertiesProps) {
  const [isFilterVisible, setIsFilterVisible] = useState(false);
  const toggle = () => setIsFilterVisible((visible) => !visible);
  const idPrefix = useId();

  const selectedIds =
    filter.code === "manufacturer"
      ? (selectedFilters.manufacturer ?? [])
      : (selectedFilters.properties ?? []);
  const isChecked = (id: string) => selectedIds.includes(id);

  const selectValue = (id: string) => {
    const emitCode =
      filter.code === "manufacturer" ? "manufacturer" : "properties";
    onSelectValue({ code: emitCode, value: id });
  };

  const options = filter.options ?? filter.entities ?? [];

  return (
    <div className="self-stretch flex flex-col justify-start items-start gap-4">
      {displayMode === "accordion" && (
        <div className="self-stretch flex flex-col justify-center items-center">
          <button
            type="button"
            className="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-between items-center gap-1 cursor-pointer"
            onClick={toggle}
            aria-expanded={isFilterVisible}
            aria-controls={filter.code}
            aria-label={filter.label}
          >
            <div className="flex-1 flex items-center gap-2.5">
              <div className="flex-1 text-surface-on-surface text-base font-bold leading-normal text-left">
                {filter.label}
              </div>
            </div>
            <span
              className="flex items-center justify-center"
              aria-hidden="true"
            >
              <ChevronDownIcon
                width={24}
                height={24}
                className={cx(
                  "transition-transform",
                  isFilterVisible && "rotate-180",
                )}
              />
            </span>
          </button>
        </div>
      )}

      {(isFilterVisible || displayMode === "dropdown") && (
        <div
          id={filter.code}
          className="self-stretch flex flex-col justify-start items-start gap-4"
        >
          <fieldset className="self-stretch flex flex-col justify-start items-start gap-4">
            <legend className="sr-only">{filter.name}</legend>
            {options.map((option) => (
              <label
                key={option.id}
                htmlFor={`${idPrefix}${option.id}`}
                className="self-stretch inline-flex justify-start items-start gap-2 cursor-pointer"
              >
                <div className="w-4 self-stretch pt-[3px] flex justify-start items-start gap-2.5">
                  <Checkbox
                    id={`${idPrefix}${option.id}`}
                    checked={isChecked(option.id)}
                    onChange={() => selectValue(option.id)}
                  />
                </div>
                <div className="flex-1 inline-flex flex-col justify-start items-start gap-0.5">
                  <div className="inline-flex justify-start items-center gap-1">
                    <div className="flex-1 text-surface-on-surface text-base font-normal leading-normal">
                      {getTranslatedProperty(option, "name")}
                    </div>
                  </div>
                </div>
              </label>
            ))}
          </fieldset>
        </div>
      )}
    </div>
  );
}

// packages/cms-base-layer/app/components/listing-filters/SwFilterProperties.vue
<script
  setup
  lang="ts"
  generic="
    ListingFilter extends {
      code: string;
      label: string;
      name: string;
      options: Array<Schemas['PropertyGroupOption']>;
      entities: Array<Schemas['ProductManufacturer']>;
    }
  "
>
import { getTranslatedProperty } from "@shopware/helpers";
import { computed, ref } from "vue";
import type { Schemas } from "#shopware";

const props = defineProps<{
  filter: ListingFilter;
  selectedFilters: {
    manufacturer?: string[];
    properties?: string[];
    [key: string]: unknown;
  };
}>();

const emits =
  defineEmits<
    (e: "select-value", value: { code: string; value: unknown }) => void
  >();

const isFilterVisible = ref<boolean>(false);
const toggle = () => {
  isFilterVisible.value = !isFilterVisible.value;
};

const selectedIds = computed(() => {
  if (props.filter.code === "manufacturer") {
    return props.selectedFilters?.manufacturer || [];
  }
  return props.selectedFilters?.properties || [];
});

const getChecked = (id: string) =>
  computed<boolean>({
    get: () => {
      return selectedIds.value.includes(id);
    },
    set: () => {
      const emitCode =
        props.filter.code === "manufacturer" ? "manufacturer" : "properties";
      emits("select-value", {
        code: emitCode,
        value: id,
      });
    },
  });
</script>

<template>
  <div class="self-stretch flex flex-col justify-start items-start gap-4">
    <div class="self-stretch flex flex-col justify-center items-center">
      <div 
        class="self-stretch py-3 border-b border-outline-outline-variant inline-flex justify-between items-center gap-1 cursor-pointer"
        @click="toggle"
        role="button"
        tabindex="0"
        :aria-expanded="isFilterVisible"
        :aria-controls="props.filter.code"
        @keydown.enter="toggle"
        @keydown.space.prevent="toggle"
      >
        <div class="flex-1 flex items-center gap-2.5">
          <div class="flex-1 text-surface-on-surface text-base font-bold leading-normal text-left">
            {{ props.filter.label }}
          </div>
        </div>
        <SwIconButton 
          type="ghost" 
          :aria-label="isFilterVisible ? 'Collapse filter' : 'Expand filter'"
          tabindex="-1"
        >
          <SwChevronIcon :direction="isFilterVisible ? 'up' : 'down'" :size="24" />
        </SwIconButton>
      </div>
    </div>
    <transition name="filter-collapse">
      <div v-if="isFilterVisible" :id="props.filter.code" class="self-stretch flex flex-col justify-start items-start gap-4">
        <fieldset class="self-stretch flex flex-col justify-start items-start gap-4">
        <legend class="sr-only">{{ props.filter.name }}</legend>
        <label
          v-for="option in props.filter.options || props.filter.entities"
          :key="`${option.id}-${selectedIds.includes(option.id)}`"
          class="self-stretch inline-flex justify-start items-start gap-2 cursor-pointer"
          @click="emits('select-value', { code: props.filter.code === 'manufacturer' ? 'manufacturer' : 'properties', value: option.id })"
        >
          <div class="w-4 self-stretch pt-[3px] flex justify-start items-start gap-2.5">
            <SwCheckbox
              :label="''"
              :description="undefined"
              :disabled="false"
              :model-value="getChecked(option.id).value"
              @update:model-value="() => emits('select-value', { code: props.filter.code === 'manufacturer' ? 'manufacturer' : 'properties', value: option.id })"
              @click.stop
            />
          </div>
          <div class="flex-1 inline-flex flex-col justify-start items-start gap-0.5">
            <div class="inline-flex justify-start items-center gap-1">
              <div class="flex-1 text-surface-on-surface text-base font-normal leading-normal">
                {{ getTranslatedProperty(option, 'name') }}
              </div>
            </div>
          </div>
        </label>
        </fieldset>
      </div>
    </transition>
  </div>
</template>
<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: all 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.filter-collapse-enter-active,
.filter-collapse-leave-active {
  transition: max-height 240ms ease, opacity 200ms ease;
  overflow: hidden;
}
.filter-collapse-enter-from,
.filter-collapse-leave-to {
  max-height: 0;
  opacity: 0;
}
.filter-collapse-enter-to,
.filter-collapse-leave-from {
  max-height: 800px;
  opacity: 1;
}
</style>
