// packages/cms-base-layer-react/src/components/element/CmsElementProductSlider.tsx
import { getConfigValue } from "../../helpers/slots";
import type { CmsComponentProps } from "../../registry";
import type { CmsElementProductSlider as CmsElementProductSliderContent } from "../../types";
import { SwProductCard } from "../shared/SwProductCard";
import { CmsElementProductSliderContainer } from "./CmsElementProductSliderContainer";
import { parseMinWidth } from "./sliderLayout";

export function CmsElementProductSlider({
  content,
  ctx,
  className,
  style,
}: CmsComponentProps<CmsElementProductSliderContent>) {
  const products = content.data?.products ?? [];
  const verticalAlign = getConfigValue(content, "verticalAlign");
  const rootStyle = verticalAlign
    ? { alignContent: verticalAlign, ...style }
    : style;

  return (
    <div className={className} style={rootStyle}>
      <CmsElementProductSliderContainer
        title={getConfigValue(content, "title")}
        border={!!getConfigValue(content, "border")}
        elMinWidth={parseMinWidth(getConfigValue(content, "elMinWidth"))}
        slotCount={ctx.slotCount}
        verticalAlign={verticalAlign || ""}
        navigation={getConfigValue(content, "navigation") === true}
        autoplay={!!getConfigValue(content, "rotate")}
      >
        {products.map((product) => (
          <SwProductCard
            key={product.id}
            className="h-full"
            product={product}
            ctx={ctx}
            layoutType={getConfigValue(content, "boxLayout")}
            displayMode={getConfigValue(content, "displayMode")}
          />
        ))}
      </CmsElementProductSliderContainer>
    </div>
  );
}

// templates/vue-demo-store/components/cms/element/CmsElementProductSlider.vue
<script setup lang="ts">
import type { CmsElementProductSlider } from "@shopware-pwa/composables-next";
import {
  // SliderElementConfig,
  useCmsElementConfig,
} from "@shopware-pwa/composables-next";
// import { ComputedRef } from "vue";
import SwSlider from "../../SwSlider.vue";
import SwProductCard from "../../SwProductCard.vue";

const props = defineProps<{
  content: CmsElementProductSlider;
}>();
const { getConfigValue } = useCmsElementConfig(props.content);

const productSlider = ref<HTMLElement>();
const products = computed(() => props.content?.data?.products ?? []);
// const config: ComputedRef<SliderElementConfig> = computed(() => ({
//   minHeight: {
//     value: "300px",
//     source: "static",
//   },
//   verticalAlign: {
//     source: "static",
//     value: getConfigValue("verticalAlign") || "",
//   },
//   displayMode: {
//     value: "contain",
//     source: "static",
//   },
//   navigationDots: {
//     value: "",
//     source: "static",
//   },
//   navigationArrows: {
//     value: getConfigValue("navigation") ? "outside" : "",
//     source: "static",
//   },
// }));
const autoplay = computed(() => getConfigValue("rotate"));
const title = computed(() => getConfigValue("title"));
const border = computed(() => getConfigValue("border"));

const breakpoints = ref({
  768: {
    itemsToShow: 4,
    itemsToScroll: 2,
    gap: '2rem'
  },
})
</script>
<template>
  <div ref="productSlider" class="cms-element-product-slider">
    <h3 class="mb-8 text-center font-semibold" v-if="title">
      {{ title }}
    </h3>
    <div :class="{ 'py-5 border border-gray-300': border }">
      <SwSlider
        :itemsToScroll="1"
        :itemsToShow="2.5"
        :breakpoints="breakpoints"
        :navigationDots="'outside'"
        :navigationArrows="'inside'"
        gap="1rem"
      >
        <SwProductCard
          v-for="product of products"
          class="w-full h-full"
          :key="product.id"
          :product="product"
          :layoutType="getConfigValue('boxLayout')"
          :displayMode="getConfigValue('displayMode')"
        />
      </SwSlider>
    </div>
  </div>
</template>
