// packages/cms-base-layer-react/src/components/shared/SwProductCard.tsx
import {
  getProductFromPrice,
  getProductManufacturerName,
  getProductName,
  getProductUrl,
} from "@shopware/helpers";
import type { CSSProperties } from "react";

import type { Schemas } from "#shopware";

import type { CmsClientContext } from "../../context";
import { cx } from "../../helpers/cx";
import { prefixUrl } from "../../helpers/resolveUrl";
import { withTranslationDefaults } from "../../translations";
import type { BoxLayout, DisplayMode } from "../../types";
import { SwProductCardDetails } from "./SwProductCardDetails";
import { SwProductCardImage } from "./SwProductCardImage";

export type SwProductCardProps = {
  product: Schemas["Product"];
  ctx: CmsClientContext;
  layoutType?: BoxLayout;
  displayMode?: DisplayMode;
  className?: string;
  style?: CSSProperties;
};

const translationDefaults = {
  product: {
    addedToWishlist: "has been added to wishlist.",
    removedFromTheWishlist: "has been removed from wishlist.",
    reason: "Reason",
    cannotAddToWishlist: "cannot be added to wishlist.",
    addedToCart: "has been added to cart.",
    viewCart: "View cart",
    addToCart: "Add to cart",
    details: "Details",
    badges: {
      topseller: "Tip",
    },
    addToWishlist: "Add to wishlist",
    removeFromWishlist: "Remove from wishlist",
  },
  errors: {
    "product-stock-reached":
      "The product {name} is only available {quantity} times",
  },
};

export function SwProductCard({
  product,
  ctx,
  layoutType = "standard",
  className,
  style,
}: SwProductCardProps) {
  const translations = withTranslationDefaults(
    ctx.translations,
    translationDefaults,
  );
  const fromPrice = getProductFromPrice(product);
  const productName = getProductName({ product });
  const productManufacturer = getProductManufacturerName(product);
  const productLink = prefixUrl(getProductUrl(product), ctx.urlPrefix);
  const cartLink = prefixUrl("/checkout/cart", ctx.urlPrefix);

  return (
    <div
      className={cx(
        "p-px flex flex-col justify-start items-start overflow-hidden",
        className,
      )}
      style={style}
    >
      <SwProductCardImage
        product={product}
        ctx={ctx}
        translations={translations}
        productLink={productLink}
      />
      <SwProductCardDetails
        product={product}
        ctx={ctx}
        productName={productName}
        productManufacturer={productManufacturer}
        translations={translations}
        fromPrice={fromPrice}
        productLink={productLink}
        cartLink={cartLink}
        layoutType={layoutType}
      />
    </div>
  );
}

// packages/cms-base-layer/app/components/SwProductCard.vue
<script setup lang="ts">
import { ApiClientError } from "@shopware/api-client";
import type { BoxLayout, DisplayMode } from "@shopware/composables";
import { useCmsTranslations } from "@shopware/composables";
import {
  buildUrlPrefix,
  getProductFromPrice,
  getProductManufacturerName,
  getProductName,
  getProductRoute,
} from "@shopware/helpers";
import { getCmsTranslate } from "@shopware/helpers";
import { defu } from "defu";
import { computed, ref, toRef } from "vue";

import {
  useAddToCart,
  useCartErrorParamsResolver,
  useCartNotification,
  useNotifications,
  useProductWishlist,
  useUrlResolver,
} from "#imports";
import type { Schemas } from "#shopware";

const { pushSuccess, pushError } = useNotifications();
const { getErrorsCodes } = useCartNotification();
const { resolveCartError } = useCartErrorParamsResolver();

const {
  product: productProp,
  layoutType = "standard",
  displayMode = "standard",
  isProductListing = false,
} = defineProps<{
  product: Schemas["Product"];
  layoutType?: BoxLayout;
  displayMode?: DisplayMode;
  isProductListing?: boolean;
}>();

type Translations = {
  product: {
    addedToWishlist: string;
    removedFromTheWishlist: string;
    reason: string;
    cannotAddToWishlist: string;
    addedToCart: string;
    addToCart: string;
    details: string;
    badges: {
      topseller: string;
    };
    addToWishlist: string;
    removeFromWishlist: string;
  };
  errors: {
    [key: string]: string;
  };
};

let translations: Translations = {
  product: {
    addedToWishlist: "has been added to wishlist.",
    removedFromTheWishlist: "has been removed from wishlist.",
    reason: "Reason",
    cannotAddToWishlist: "cannot be added to wishlist.",
    addedToCart: "has been added to cart.",
    addToCart: "Add to cart",
    details: "Details",
    badges: {
      topseller: "Tip",
    },
    addToWishlist: "Add to wishlist",
    removeFromWishlist: "Remove from wishlist",
  },
  errors: {
    "product-stock-reached":
      "The product {name} is only available {quantity} times",
  },
};

translations = defu(useCmsTranslations(), translations) as Translations;

const product = toRef(() => productProp);

const { addToCart } = useAddToCart(product);

const { addToWishlist, removeFromWishlist, isInWishlist } = useProductWishlist(
  product.value.id,
);
const isLoading = ref(false);

const toggleWishlistProduct = async () => {
  isLoading.value = true;

  try {
    if (!isInWishlist.value) {
      await addToWishlist();
      pushSuccess(
        `${product?.value.translated.name} ${translations.product.addedToWishlist}`,
      );
    } else {
      await removeFromWishlist();
      pushSuccess(
        `${product?.value.translated.name} ${translations.product.removedFromTheWishlist}`,
      );
    }
  } catch (error) {
    if (error instanceof ApiClientError) {
      const reason = error.details.errors?.[0]?.detail
        ? `${translations.product.reason}: ${error.details.errors?.[0]?.detail}`
        : "";
      return pushError(
        `${product?.value.translated.name} ${translations.product.cannotAddToWishlist}\n${reason}`,
        {
          timeout: 5000,
        },
      );
    }
  } finally {
    isLoading.value = false;
  }
};

const addToCartProxy = async () => {
  await addToCart();
  const errors = getErrorsCodes();
  for (const element of errors) {
    const { messageKey, params } = resolveCartError(element);
    if (translations.errors[messageKey])
      pushError(getCmsTranslate(translations.errors[messageKey], params));
  }

  if (!errors.length)
    pushSuccess(
      `${product?.value.translated.name} ${translations.product.addedToCart}`,
    );
};

const fromPrice = getProductFromPrice(product.value);
const productName = computed(() => getProductName({ product: product.value }));
const productManufacturer = computed(() =>
  getProductManufacturerName(product.value),
);

const { getUrlPrefix } = useUrlResolver();
const productLink = computed(() =>
  buildUrlPrefix(getProductRoute(product.value), getUrlPrefix()),
);
</script>

<template>
  <div class="p-px flex flex-col justify-start items-start overflow-hidden">
    <SwProductCardImage
      :product="product"
      :translations="translations"
      :isInWishlist="isInWishlist"
      :isLoading="isLoading"
      :toggleWishlist="toggleWishlistProduct"
      :productLink="productLink"
    />
    <SwProductCardDetails
      :product="product"
      :productName="productName"
      :productManufacturer="productManufacturer"
      :translations="translations"
      :fromPrice="fromPrice"
      :addToCartProxy="addToCartProxy"
      :productLink="productLink"
      :layoutType="layoutType"
    />
  </div>
</template>
