// packages/cms-base-layer-react/src/components/shared/SwProductCardDetails.tsx
import Link from "next/link";

import type { Schemas } from "#shopware";

import type { BoxLayout } from "../../types";
import { SwListingProductPrice } from "./SwListingProductPrice";
import type { ProductPriceContext } from "./SwListingProductPrice";
import { SwProductCardAddToCartButton } from "./SwProductCardActions";
import { SwProductRating } from "./SwProductRating";

export type SwProductCardDetailsTranslations = {
  product: {
    addToCart: string;
    addedToCart: string;
    viewCart: string;
    details: string;
  };
  errors: Record<string, string>;
};

export type SwProductCardDetailsProps = {
  product: Schemas["Product"];
  ctx: ProductPriceContext;
  productName: string | null;
  productManufacturer?: string | null;
  translations: SwProductCardDetailsTranslations;
  fromPrice?: number;
  productLink: string;
  cartLink: string;
  layoutType?: BoxLayout;
};

const DETAILS_LINK_CLASS =
  "self-stretch w-full inline-flex justify-center items-center gap-2 rounded font-bold transition-colors focus:outline-hidden focus:ring-2 focus:ring-offset-2 px-4 py-3 text-base bg-brand-primary hover:bg-brand-primary-hover text-brand-on-primary focus:ring-brand-primary";

export function SwProductCardDetails({
  product,
  ctx,
  productName,
  productManufacturer,
  translations,
  fromPrice,
  productLink,
  cartLink,
  layoutType,
}: SwProductCardDetailsProps) {
  const isMinimalLayout = layoutType === "minimal";

  return (
    <div className="self-stretch p-2 flex flex-col justify-between items-start gap-4 flex-1">
      <div className="self-stretch flex flex-col justify-start items-start gap-4">
        <div className="self-stretch flex flex-col justify-start items-start gap-2">
          <div className="self-stretch flex flex-col justify-start items-start gap-1">
            {productManufacturer ? (
              <div className="self-stretch text-surface-on-surface text-sm font-bold leading-tight">
                {productManufacturer}
              </div>
            ) : null}

            <Link
              href={productLink}
              className="self-stretch text-surface-on-surface text-2xl font-normal font-serif leading-9 overflow-hidden line-clamp-2 break-words min-h-[4.5rem]"
              data-testid="product-box-product-name-link"
            >
              {productName}
            </Link>
          </div>
        </div>

        {isMinimalLayout ? (
          <SwProductRating
            rating={product.ratingAverage ?? 0}
            reviewCount={product.productReviews?.length ?? 0}
            className="mt-4"
          />
        ) : (
          <SwListingProductPrice
            product={product}
            ctx={ctx}
            data-testid="product-box-product-price"
          />
        )}
      </div>

      {isMinimalLayout ? null : fromPrice ? (
        <Link href={productLink} className={DETAILS_LINK_CLASS}>
          <span>{translations.product.details}</span>
        </Link>
      ) : (
        <SwProductCardAddToCartButton
          productId={product.id}
          productName={productName ?? ""}
          available={!!product.available}
          cartLink={cartLink}
          translations={{
            addToCart: translations.product.addToCart,
            addedToCart: translations.product.addedToCart,
            viewCart: translations.product.viewCart,
            errors: translations.errors,
          }}
        />
      )}
    </div>
  );
}

// packages/cms-base-layer/app/components/SwProductCardDetails.vue
<script setup lang="ts">
import type { BoxLayout } from "@shopware/composables";
import type { UrlRouteOutput } from "@shopware/helpers";
import { computed } from "vue";
import type { Schemas } from "#shopware";

type Translations = {
  product: {
    addToCart: string;
    details: string;
  };
  errors: {
    [key: string]: string;
  };
};

const props = defineProps<{
  product: Schemas["Product"];
  productName: string | null;
  productManufacturer?: string | null;
  translations: Translations;
  fromPrice?: number;
  addToCartProxy: () => Promise<void>;
  productLink: UrlRouteOutput;
  layoutType?: BoxLayout;
}>();

const isMinimalLayout = computed(() => props.layoutType === "minimal");
</script>
<template>
  <div class="self-stretch p-2 flex flex-col justify-between items-start gap-4 flex-1">
    <div class="self-stretch flex flex-col justify-start items-start gap-4">
      <div class="self-stretch flex flex-col justify-start items-start gap-2">
        <div class="self-stretch flex flex-col justify-start items-start gap-1">
          <div v-if="productManufacturer"
            class="self-stretch text-surface-on-surface text-sm font-bold leading-tight">
            {{ productManufacturer }}
          </div>

          <RouterLink :to="productLink"
            class="self-stretch text-surface-on-surface text-2xl font-normal font-serif leading-9 overflow-hidden line-clamp-2 break-words min-h-[4.5rem]"
            data-testid="product-box-product-name-link">
            {{ productName }}
          </RouterLink>
        </div>
      </div>

      <!-- Star rating for minimal layout -->
      <SwProductRating
        v-if="isMinimalLayout"
        :rating="product?.ratingAverage ?? 0"
        :review-count="product?.productReviews?.length ?? 0"
        class="mt-4"
      />

      <!-- Price for standard layout -->
      <SwListingProductPrice v-else :product="product" data-testid="product-box-product-price" />
    </div>

    <!-- CTA buttons only for non-minimal layout -->
    <template v-if="!isMinimalLayout">
      <SwBaseButton variant="primary" v-if="!fromPrice" size="medium" :disabled="!product?.available" block
        data-testid="add-to-cart-button" @click="addToCartProxy">
        {{ translations.product.addToCart }}
      </SwBaseButton>

      <RouterLink v-else :to="productLink" class="self-stretch">
        <SwBaseButton block>
          {{ translations.product.details }}
        </SwBaseButton>
      </RouterLink>
    </template>
  </div>
</template>
