// packages/cms-base-layer-react/src/components/shared/SwProductListingFilter.tsx
"use client";

import type { CSSProperties } from "react";

import { cx } from "../../helpers/cx";
import type { CmsTranslations } from "../../translations";
import type {
  ListingFilter,
  ListingFilterChangeEvent,
  ListingFilterDisplayMode,
  SelectedListingFilters,
} from "./listingFilterTypes";
import { SwFilterCategories } from "./SwFilterCategories";
import { SwFilterPrice } from "./SwFilterPrice";
import { SwFilterProperties } from "./SwFilterProperties";
import { SwFilterRating } from "./SwFilterRating";
import { SwFilterShippingFree } from "./SwFilterShippingFree";

export type SwProductListingFilterProps = {
  filter: ListingFilter;
  selectedManufacturer: string[];
  selectedProperties: string[];
  selectedCategories?: string[];
  selectedMinPrice: number | undefined;
  selectedMaxPrice: number | undefined;
  selectedRating: number | undefined;
  selectedShippingFree: boolean | undefined;
  displayMode?: ListingFilterDisplayMode;
  rootCategoryId?: string;
  translations?: CmsTranslations;
  onFilterChange: (event: ListingFilterChangeEvent) => void;
  className?: string;
  style?: CSSProperties;
};

export function SwProductListingFilter({
  filter,
  selectedManufacturer,
  selectedProperties,
  selectedCategories = [],
  selectedMinPrice,
  selectedMaxPrice,
  selectedRating,
  selectedShippingFree,
  displayMode = "accordion",
  rootCategoryId,
  translations,
  onFilterChange,
  className,
  style,
}: SwProductListingFilterProps) {
  const selectedFilters: SelectedListingFilters = {
    price: { min: selectedMinPrice, max: selectedMaxPrice },
    rating: selectedRating,
    "shipping-free": selectedShippingFree,
    manufacturer: selectedManufacturer,
    properties: selectedProperties,
    categories: selectedCategories,
  };

  const renderFilter = () => {
    switch (filter.code) {
      case "manufacturer":
        return (
          <SwFilterProperties
            filter={filter}
            selectedFilters={selectedFilters}
            displayMode={displayMode}
            onSelectValue={onFilterChange}
          />
        );
      case "categories":
        return (
          <SwFilterCategories
            filter={filter}
            selectedFilters={selectedFilters}
            displayMode={displayMode}
            rootCategoryId={rootCategoryId}
            translations={translations}
            onSelectValue={onFilterChange}
          />
        );
      case "price":
        return (
          <SwFilterPrice
            filter={filter}
            selectedFilters={selectedFilters}
            displayMode={displayMode}
            translations={translations}
            onSelectValue={onFilterChange}
          />
        );
      case "rating":
        return (
          <SwFilterRating
            filter={filter}
            selectedFilters={selectedFilters}
            displayMode={displayMode}
            onSelectValue={onFilterChange}
          />
        );
      case "shipping-free":
        return (
          <SwFilterShippingFree
            filter={filter}
            selectedFilters={selectedFilters}
            displayMode={displayMode}
            translations={translations}
            onSelectValue={onFilterChange}
          />
        );
      default:
        return "options" in filter ? (
          <SwFilterProperties
            filter={filter}
            selectedFilters={selectedFilters}
            displayMode={displayMode}
            onSelectValue={onFilterChange}
          />
        ) : null;
    }
  };

  return (
    <div
      data-testid={`listing-filter-${filter.code}`}
      className={cx(className) || undefined}
      style={style}
    >
      {renderFilter()}
    </div>
  );
}

// packages/cms-base-layer/app/components/SwProductListingFilter.vue
<script setup lang="ts" generic="ListingFilter extends { code: string }">
import { computed } from "vue";
import type { Component } from "vue";

import SwFilterCategoriesVue from "./listing-filters/SwFilterCategories.vue";
import SwFilterPriceVue from "./listing-filters/SwFilterPrice.vue";
import SwFilterPropertiesVue from "./listing-filters/SwFilterProperties.vue";
import SwFilterRatingVue from "./listing-filters/SwFilterRating.vue";
import SwFilterShippingFreeVue from "./listing-filters/SwFilterShippingFree.vue";

const {
  filter,
  selectedManufacturer,
  selectedProperties,
  selectedCategories = new Set<string>(),
  selectedMinPrice,
  selectedMaxPrice,
  selectedRating,
  selectedShippingFree,
  displayMode = "accordion",
} = defineProps<{
  filter: ListingFilter;
  selectedManufacturer: Set<string>;
  selectedProperties: Set<string>;
  selectedCategories?: Set<string>;
  selectedMinPrice: number | undefined;
  selectedMaxPrice: number | undefined;
  selectedRating: number | undefined;
  selectedShippingFree: boolean | undefined;
  displayMode?: "accordion" | "dropdown";
}>();

const emit = defineEmits<{
  "filter-change": [{ code: string; value: string | number | boolean }];
}>();

const transformedFilters = computed(() => ({
  price: {
    min: selectedMinPrice,
    max: selectedMaxPrice,
  },
  rating: selectedRating,
  "shipping-free": selectedShippingFree,
  manufacturer: [...selectedManufacturer],
  properties: [...selectedProperties],
  categories: [...selectedCategories],
}));

const filterComponent = computed<Component | undefined>(() => {
  const componentMap: Record<string, Component> = {
    manufacturer: SwFilterPropertiesVue,
    categories: SwFilterCategoriesVue,
    price: SwFilterPriceVue,
    rating: SwFilterRatingVue,
    "shipping-free": SwFilterShippingFreeVue,
  };

  return (
    componentMap[filter.code] ||
    ("options" in filter ? SwFilterPropertiesVue : undefined)
  );
});

const handleSelectValue = ({
  code,
  value,
}: {
  code: string;
  value: string | number | boolean;
}) => {
  emit("filter-change", { code, value });
};
</script>
<template>
  <div :data-testid="`listing-filter-${filter.code}`">
    <component
      :is="filterComponent"
      :filter="filter"
      :selected-filters="transformedFilters"
      :display-mode="displayMode"
      @select-value="handleSelectValue"
    />
  </div>
</template>
